---
title: "multipathway_ASSIGN"
author: "Mumtahena Rahman"
date: "December 23, 2014"
output: pdf_document
---

```{r,echo=FALSE,cache=TRUE,include=FALSE}
library(sva)
library(ASSIGN)
library(utils)
```

Reading in the signature datasets...
```{r include=FALSE,echo=FALSE}
#setwd("~/Documents/ThesisWork/GitRepos/bild_signature_validation_old_repo/Datasets")
setwd("~/Dropbox/bild_signature/Datasets")
expr<-as.matrix(read.table("GFP18_AKT_BAD_HER2_IGF1R_RAF_ERK.tpmlog",sep='\t',row.names=1,header=1))
control<-subset(expr, select=GFP.1:GFP.12)
her2<-subset(expr, select=HER2.1:HER2.6)
akt<-subset(expr,select=AKT.1:AKT.6)
bad<-subset(expr,select=BAD.1:BAD.6)
igf1r<-subset(expr,select=IGF1R.1:IGF1R.6)
erk<-subset(expr,select=ERK.1:ERK.6)
expr_all<-cbind(control,akt,bad,her2,igf1r,erk)
dim(expr_all)
#icbp<-as.matrix(read.table("~/Documents/ThesisWork/GitRepos/bild_signature_validation_old_repo/Datasets/ICBP/icbp_Rsubread_tpmlog.txt", sep='\t', stringsAsFactors=FALSE, header=1, row.names=1))
icbp<-as.matrix(read.table("icbp_Rsubread_tpmlog.txt", sep='\t', stringsAsFactors=FALSE, header=1, row.names=1))
expr_all_f <-expr_all[apply(expr_all[,1:41]==0,1,mean) < 0.85,]
dim(expr_all_f)
expr_all_icbp_f<-merge_drop(expr_all_f,icbp,by=0)
sub<-c(12,6,6,5,6,6,55)
pdf("pca_plots.pdf")
pcaplot(expr_all_icbp_f,sub)
bat1<-as.matrix(cbind(c(colnames(expr_all_f),colnames(icbp)),c(rep(1,length(colnames(expr_all_f))),rep(2,length(colnames(icbp))))))
#bat1
combat_expr1<-ComBat(dat=expr_all_icbp_f, batch=bat1[,2], mod=NULL, numCovs=NULL)
pcaplot(combat_expr1,sub)
dev.off()
c_gfp<-subset(combat_expr1, select=GFP.1:GFP.12)
c_akt<-subset(combat_expr1, select=AKT.1:AKT.6)
c_bad<-subset(combat_expr1, select=BAD.1:BAD.6)
c_her2<-subset(combat_expr1, select=HER2.1:HER2.6)
c_igf1r<-subset(combat_expr1, select=IGF1R.1:IGF1R.6)
c_erk<-subset(combat_expr1, select=ERK.1:ERK.6)
c_test<-combat_expr1[,42:96]
basedir="~/Dropbox/bild_signatures/icbp_15_mar_all"
dir.create( basedir)

#############trying one pathways at a time in multipathway#############
#1. AKT
trainingLabela<-list(control=list(akt=1:12),akt=13:18)
sub_dir<-paste(basedir,"akt",sep='/')
dir.create( sub_dir)
assign_easy_multi(trainingData = cbind(c_gfp,c_akt),test=c_test,trainingLabel1 = trainingLabela,g=150,out_dir_base = sub_dir,single = 1)

#2. BAD
trainingLabelb<-list(control=list(bad=1:12),bad=13:18)
sub_dir<-paste(basedir,"bad",sep='/')
dir.create( sub_dir)
assign_easy_multi(trainingData = cbind(c_gfp,c_bad),test=c_test,trainingLabel1 = trainingLabelb,g=150,out_dir_base = sub_dir,single = 1)

#3. HER2
trainingLabelh<-list(control=list(her2=1:12),her2=13:17)
sub_dir<-paste(basedir,"her2",sep='/')
dir.create( sub_dir)
assign_easy_multi(trainingData = cbind(c_gfp,c_her2),test=c_test,trainingLabel1 = trainingLabelh,g=15,out_dir_base = sub_dir,single = 1)

#4. IGF1R
trainingLabeli<-list(control=list(igf1r=1:12),igf1r=13:18)
sub_dir<-paste(basedir,"igf1r",sep='/')
dir.create( sub_dir)
assign_easy_multi(trainingData = cbind(c_gfp,c_igf1r),test=c_test,trainingLabel1 = trainingLabeli,g=100,out_dir_base = sub_dir,single = 1)

#5. ERK
trainingLabele<-list(control=list(erk=1:12),erk=13:18)
sub_dir<-paste(basedir,"erk",sep='/')
dir.create( sub_dir)
assign_easy_multi(trainingData = cbind(c_gfp,c_erk),test=c_test,trainingLabel1 = trainingLabele,g=100,out_dir_base = sub_dir,single = 1)

#############trying two pathways at a time in multipathway#############
#1. HER2 & AKT
trainha<-cbind(c_gfp,c_akt,c_her2)
trainingLabelha<-list(control=list(akt=1:12,her2=1:12),akt=13:18,her2=19:23)
sub_dir=paste(basedir,"her2_akt",sep='/')
dir.create( sub_dir)
assign_easy_multi(trainingData = trainha,test=c_test,trainingLabel1 = trainingLabelha,g=c(150,15),out_dir_base = sub_dir)

#2. HER2 & BAD
trainhb<-cbind(c_gfp,c_bad,c_her2)
trainingLabelhb<-list(control=list(bad=1:12,her2=1:12),bad=13:18,her2=19:23)
sub_dir=paste(basedir,"her2_bad",sep='/')
dir.create(sub_dir)
assign_easy_multi(trainingData = trainhb,test=c_test,trainingLabel1 = trainingLabelhb,g=c(150,15),out_dir_base = sub_dir)

#3. HER2 & IGF1R
trainhi<-cbind(c_gfp,c_igf1r,c_her2)
trainingLabelhi<-list(control=list(igf1r=1:12,her2=1:12),igf1r=13:18,her2=19:23)
sub_dir=paste(basedir,"her2_igf1r",sep='/')
dir.create(sub_dir)
assign_easy_multi(trainingData = trainhi,test=c_test,trainingLabel1 = trainingLabelhi,g=c(100,15),out_dir_base = sub_dir)

#4. AKT & BAD
trainab<-cbind(c_gfp,c_akt,c_bad)
trainingLabelab<-list(control=list(akt=1:12,bad=1:12),akt=13:18,bad=19:24)
sub_dir=paste(basedir,"akt_bad",sep='/')
dir.create(sub_dir)
assign_easy_multi(trainingData = trainab,test=c_test,trainingLabel1 = trainingLabelab,g=c(150,150),out_dir_base = sub_dir)

#5. AKT & IGF1R
trainai<-cbind(c_gfp,c_akt,c_igf1r)

trainingLabelai<-list(control=list(akt=1:12,igf1r=1:12),akt=13:18,igf1r=19:24)
sub_dir=paste(basedir,"akt_igf1r",sep='/')
dir.create( sub_dir)
assign_easy_multi(trainingData = trainai,test=c_test,trainingLabel1 = trainingLabelai,g=c(150,100),out_dir_base = sub_dir)

#6. BAD & IGF1R
trainbi<-cbind(c_gfp,c_bad,c_igf1r)
trainingLabelbi<-list(control=list(bad=1:12,igf1r=1:12),bad=13:18,igf1r=19:24)
sub_dir=paste(basedir,"bad_igf1r",sep='/')
dir.create( sub_dir)
assign_easy_multi(trainingData = trainbi,test=c_test,trainingLabel1 = trainingLabelbi,g=c(150,100),out_dir_base = sub_dir)

#7. ERK & IGF1R
trainei<-cbind(c_gfp,c_erk,c_igf1r)
trainingLabelei<-list(control=list(erk=1:12,igf1r=1:12),erk=13:18,igf1r=19:24)
sub_dir=paste(basedir,"erk_igf1r",sep='/')
dir.create( sub_dir)
assign_easy_multi(trainingData = trainei,test=c_test,trainingLabel1 = trainingLabelei,g=c(100,100),out_dir_base = sub_dir)

#8. ERK & AKT
trainea<-cbind(c_gfp,c_erk,c_akt)
trainingLabelea<-list(control=list(erk=1:12,akt=1:12),erk=13:18,akt=19:24)
sub_dir=paste(basedir,"erk_akt",sep='/')
dir.create( sub_dir)
assign_easy_multi(trainingData = trainea,test=c_test,trainingLabel1 = trainingLabelea,g=c(100,150),out_dir_base = sub_dir)

#9. ERK & BAD
traineb<-cbind(c_gfp,c_erk,c_bad)
trainingLabeleb<-list(control=list(erk=1:12,bad=1:12),erk=13:18,bad=19:24)
sub_dir=paste(basedir,"erk_bad",sep='/')
dir.create( sub_dir)
assign_easy_multi(trainingData = traineb,test=c_test,trainingLabel1 = trainingLabeleb,g=c(100,150),out_dir_base = sub_dir)

#10. ERK & HER2
traineh<-cbind(c_gfp,c_erk,c_her2)
trainingLabeleh<-list(control=list(erk=1:12,her2=1:12),erk=13:18,her2=19:23)
sub_dir=paste(basedir,"erk_her2",sep='/')
dir.create( sub_dir)
assign_easy_multi(trainingData = traineh,test=c_test,trainingLabel1 = trainingLabeleh,g=c(100,15),out_dir_base = sub_dir)

#############trying three pathways at a time in multipathway#############
#1. HER2, AKT & BAD
trainhab<-cbind(c_gfp,c_akt,c_bad,c_her2)
trainingLabelhab<-list(control=list(akt=1:12,bad=1:12,her2=1:12),akt=13:18,bad=19:24,her2=25:29)
sub_dir=paste(basedir,"her2_akt_bad",sep='/')
dir.create(sub_dir)
assign_easy_multi(trainingData = trainhab,test=c_test,trainingLabel1 = trainingLabelhab,g=c(150,150,15),out_dir_base = sub_dir)

#2. HER2, BAD & IGF1R
trainhbi<-cbind(c_gfp,c_igf1r,c_bad,c_her2)
trainingLabelhbi<-list(control=list(igf1r=1:12,bad=1:12,her2=1:12),igf1r=13:18,bad=19:24,her2=25:29)
sub_dir=paste(basedir,"her2_bad_igf1r",sep='/')
dir.create(sub_dir)
assign_easy_multi(trainingData = trainhbi,test=c_test,trainingLabel1 = trainingLabelhbi,g=c(100,150,15),out_dir_base = sub_dir)

#3. AKT, BAD & IGF1R
trainabi<-cbind(c_gfp,c_akt,c_bad,c_igf1r)
trainingLabelabi<-list(control=list(akt=1:12,bad=1:12,igf1r=1:12),akt=13:18,bad=19:24,igf1r=25:30)
sub_dir=paste(basedir,"akt_bad_igf1r",sep='/')
dir.create(sub_dir)
assign_easy_multi(trainingData = trainabi,test=c_test,trainingLabel1 = trainingLabelabi,g=c(150,150,100),out_dir_base = sub_dir)

#4. AKT, BAD & ERK
trainabe<-cbind(c_gfp,c_akt,c_bad,c_erk)
trainingLabelabe<-list(control=list(akt=1:12,bad=1:12,erk=1:12),akt=13:18,bad=19:24,erk=25:30)
sub_dir=paste(basedir,"akt_bad_erk",sep='/')
dir.create(sub_dir)
assign_easy_multi(trainingData = trainabe,test=c_test,trainingLabel1 = trainingLabelabe,g=c(150,150,100),out_dir_base = sub_dir)

#5. AKT, HER2 & IGF1R
trainahi<-cbind(c_gfp,c_akt,c_her2,c_igf1r)
trainingLabelahi<-list(control=list(akt=1:12,her2=1:12,igf1r=1:12),akt=13:18,her2=19:23,igf1r=24:29)
sub_dir=paste(basedir,"akt_her2_igf1r",sep='/')
dir.create(sub_dir)
assign_easy_multi(trainingData = trainahi,test=c_test,trainingLabel1 = trainingLabelahi,g=c(150,15,100),out_dir_base = sub_dir)

#6. AKT, HER2 & ERK
trainahe<-cbind(c_gfp,c_akt,c_her2,c_erk)
trainingLabelahe<-list(control=list(akt=1:12,her2=1:12,igf1r=1:12),akt=13:18,her2=19:23,erk=24:29)
sub_dir=paste(basedir,"akt_her2_erk",sep='/')
dir.create(sub_dir)
assign_easy_multi(trainingData = trainahe,test=c_test,trainingLabel1 = trainingLabelahe,g=c(150,15,100),out_dir_base = sub_dir)

#7. AKT, IGF1R & ERK
trainaie<-cbind(c_gfp,c_akt,c_igf1r,c_erk)
trainingLabelaie<-list(control=list(akt=1:12,igf1r=1:12,erk=1:12),akt=13:18,igf1r=19:24,erk=25:30)
sub_dir=paste(basedir,"akt_igf1r_erk",sep='/')
dir.create(sub_dir)
assign_easy_multi(trainingData = trainaie,test=c_test,trainingLabel1 = trainingLabelaie,g=c(150,100,100),out_dir_base = sub_dir)

#8. BAD, IGF1R & ERK
trainbie<-cbind(c_gfp,c_bad,c_igf1r,c_erk)
trainingLabelbie<-list(control=list(bad=1:12,igf1r=1:12,erk=1:12),bad=13:18,igf1r=19:24,erk=25:30)
sub_dir=paste(basedir,"bad_igf1r_erk",sep='/')
dir.create(sub_dir)
assign_easy_multi(trainingData = trainbie,test=c_test,trainingLabel1 = trainingLabelbie,g=c(150,100,100),out_dir_base = sub_dir)

#9. BAD, HER2 & ERK
trainbhe<-cbind(c_gfp,c_bad,c_her2,c_erk)
trainingLabelbhe<-list(control=list(bad=1:12,her2=1:12,erk=1:12),bad=13:18,her2=19:23,erk=24:29)
sub_dir=paste(basedir,"bad_her2_erk",sep='/')
dir.create(sub_dir)
assign_easy_multi(trainingData = trainbhe,test=c_test,trainingLabel1 = trainingLabelbhe,g=c(150,15,100),out_dir_base = sub_dir)

#10. IGF1R, HER2 & ERK
trainihe<-cbind(c_gfp,c_igf1r,c_her2,c_erk)
trainingLabelihe<-list(control=list(igf1r=1:12,her2=1:12,erk=1:12),igf1r=13:18,her2=19:23,erk=24:29)
sub_dir=paste(basedir,"igf1r_her2_erk",sep='/')
dir.create(sub_dir)
assign_easy_multi(trainingData = trainihe,test=c_test,trainingLabel1 = trainingLabelihe,g=c(100,15,100),out_dir_base = sub_dir)

########################trying four at a time#####################
#1. AKT, BAD, HER2 & IGF1R
trainabhi<-cbind(c_gfp,c_akt,c_bad,c_her2,c_igf1r)
trainingLabelabhi<-list(control=list(akt=1:12,bad=1:12,her2=1:12,igf1r=1:12),akt=13:18, bad=19:24,her2=25:29,igf1r=30:35)
sub_dir=paste(basedir,"akt_bad_her2_igf1r",sep='/')
dir.create(sub_dir)
assign_easy_multi(trainingData = trainabhi,test=c_test,trainingLabel1 = trainingLabelabhi,g=c(150,150,15,100),out_dir_base = sub_dir)

#2. AKT, BAD, HER2 & ERK
trainabhe<-cbind(c_gfp,c_akt,c_bad,c_her2,c_erk)
trainingLabelabhe<-list(control=list(akt=1:12,bad=1:12,her2=1:12,erk=1:12),akt=13:18, bad=19:24,her2=25:29,erk=30:35)
sub_dir=paste(basedir,"akt_bad_her2_erk",sep='/')
dir.create(sub_dir)
assign_easy_multi(trainingData = trainabhe,test=c_test,trainingLabel1 = trainingLabelabhe,g=c(150,150,15,100),out_dir_base = sub_dir)

#3. AKT, BAD, IGF1R & ERK
trainabie<-cbind(c_gfp,c_akt,c_bad,c_igf1r,c_erk)
trainingLabelabie<-list(control=list(akt=1:12,bad=1:12,igf1r=1:12,erk=1:12),akt=13:18, bad=19:24,igf1r=25:30,erk=31:36)
sub_dir=paste(basedir,"akt_bad_igf1r_erk",sep='/')
dir.create(sub_dir)
assign_easy_multi(trainingData = trainabie,test=c_test,trainingLabel1 = trainingLabelabie,g=c(150,150,100,100),out_dir_base = sub_dir)

#4. AKT, IGF1R, HER2 & ERK
trainaihe<-cbind(c_gfp,c_akt,c_igf1r,c_her2,c_erk)
#trainingLabelabie<-list(control=list(akt=1:12,bad=1:12,igf1r=1:12,erk=1:12),akt=13:18, bad=19:24,igf1r=25:30,erk=31:36)

trainingLabelaihe<-list(control=list(akt=1:12,igf1r=1:12,her2=1:12,erk=1:12),akt=13:18, igf1r=19:24,her2=25:29,erk=30:35)
sub_dir=paste(basedir,"akt_igf1r_her2_erk",sep='/')
dir.create(sub_dir)
assign_easy_multi(trainingData = trainaihe,test=c_test,trainingLabel1 = trainingLabelaihe,g=c(150,100,15,100),out_dir_base = sub_dir)

#5. BAD, IGF1R, HER2 & ERK
trainbihe<-cbind(c_gfp,c_bad,c_igf1r,c_her2,c_erk)
trainingLabelbihe<-list(control=list(bad=1:12,igf1r=1:12,her2=1:12,erk=1:12),bad=13:18, igf1r=19:24,her2=25:29,erk=30:35)
sub_dir=paste(basedir,"bad_igf1r_her2_erk",sep='/')
dir.create(sub_dir)
assign_easy_multi(trainingData = trainbihe,test=c_test,trainingLabel1 = trainingLabelbihe,g=c(150,100,15,100),out_dir_base = sub_dir)


#########including all 5 pathways######
trainhall5<-cbind(c_gfp,c_akt,c_bad,c_her2,c_igf1r, c_erk)
trainingLabelall5<-list(control=list(akt=1:12,bad=1:12,her2=1:12,igf1r=1:12, erk=1:12),akt=13:18, bad=19:24,her2=25:29,igf1r=30:35, erk=36:41)
sub_dir=paste(basedir,"akt_bad_her2_igf1r_erk",sep='/')
dir.create(sub_dir)
assign_easy_multi(trainingData = trainhall5,test=c_test,trainingLabel1 = trainingLabelall5,g=c(150,150,15,100,100),out_dir_base = sub_dir)

```


```{r}

```


Read in all the predictions are make files with all results 
```{r}
# multi nonadpative 
#setwd("~/Documents/Thesiswork/ICBP/multi_icbp_expr_pc/")
setwd("~//Documents/Thesiswork/GitRepos/bild_signatures/ASSIGN_Results_Ignore_too_big/icbp_15_mar_all/")
getwd()
filenames_icbp_multi<-system("ls */*/pathway_activity_testset*", intern=TRUE)
filenames_icbp_multi

for(i in 1:length(filenames_icbp_multi))
  {
   f<-read.csv(filenames_icbp_multi[i], header=1,row.names=1) ###reading in the filess one at a time
   colnames(f)<-paste(filenames_icbp_multi[i],colnames(f),sep='/')
   if(i==1){
     data_icbp<-f
     }
   else{
     data_icbp<-cbind(data_icbp,f)
    }
  }

head(data_icbp)
View(data_icbp)
write.table(data_icbp,"~/Documents/ThesisWork/GitRepos/bild_signatures/ICBP_pathwaypredictions_all_combos.txt",sep='\t', col.names = NA,quote=F)

colnames(data_icbp)<-gsub(pattern = "/pathway_activity_testset.csv",replacement = "",x = colnames(data_icbp))
head(data_icbp)
rownames(data_icbp)[1:7]<-c("184A1","184B5","21MT1","21MT2","21NT","21PT","600MPE")
View(data_icbp)
write.table(data_icbp,"~/Documents/ThesisWork/GitRepos/bild_signatures/ICBP_pathwaypredictions_all_combos.txt",sep='\t', col.names = NA,quote=F)

setwd("~/Documents/ThesisWork/GitRepos/bild_signatures/")
drugs<-read.delim("ICBP_drugs_1.txt", header=1, sep='\t',row.names=1)
View(drugs)
head(drugs);dim(drugs)


pred_drug<-merge_drop(data_icbp,drugs,by=0)
pred_drug
dim(pred_drug)
dimnames(pred_drug)
pred_drug_only=subset(pred_drug, select=c(1:160,175,206,204,180,209,202,191))

pred_drug2=pred_drug[, c(1:160,171:260)]
head(pred_drug2)
colnames(pred_drug)
View(pred_drug_only[161:167 ])

write.table(pred_drug2,"~/Documents/ThesisWork/GitRepos/bild_signatures/ICBP_pathwaypredictions_drug_all_combos.txt",sep='\t', col.names = NA,quote=F)
getwd()

rhos=p_val=NULL
temp=temp_f=NULL
for(i in 1:160){
  for(j in 1:7) {
    #i=1
    #j=1
  pathway_drug=subset(pred_drug_only, select=c(i,160+j))
  temp_cors= cor.ci(pathway_drug, method="spearman", plot=FALSE)
  temp<-c(temp_cors$rho[2,1],temp_cors$ci[5])  
  temp<- cbind(temp[1],temp[2])
  temp_f<-rbind(temp_f,temp)
  rownames(temp_f)[j+(i-1)*7]=paste(colnames(pathway_drug)[1],colnames(pathway_drug)[2],sep='__')
  }
}


colnames(temp_f)<-c("Corr","p_val")
writeFile(temp_f, "ICBP_allpathwaycombos_drug_correlations.txt")
writeFile(temp_f, "ICBP_allpathwaycombos_drug_correlations_2.txt")


# list for chemo drugs
#list for pi3k
#list for akt
# diffent classes of chemo


getwd()



erk_preds<-temp_f[grepl("*/erk__*", rownames(temp_f)), ]
erk_preds_adapB<-erk_preds[grepl("*/adapB_*", rownames(erk_preds)), ]
writeFile(erk_preds_adapB, "ICBP_ERK_drug_cors_allcombos_adapB.txt")
erk_preds_adap_adap<-erk_preds[grepl("*/adap_adap*", rownames(erk_preds)), ]
writeFile(erk_preds_adap_adap, "ICBP_ERK_drug_cors_allcombos_adap_adap.txt")


bad_preds<-temp_f[grepl("*/bad__*", rownames(temp_f)), ]
bad_preds_adapB<-bad_preds[grepl("*/adapB_*", rownames(bad_preds)), ]
writeFile(bad_preds_adapB, "ICBP_bad_drug_cors_allcombos_adapB.txt")
bad_preds_adap_adap<-bad_preds[grepl("*/adap_adap*", rownames(bad_preds)), ]
writeFile(bad_preds_adap_adap, "ICBP_bad_drug_cors_allcombos_adap_adap.txt")

akt_preds<-temp_f[grepl("*/akt__*", rownames(temp_f)), ]
akt_preds_adapB<-akt_preds[grepl("*/adapB_*", rownames(akt_preds)), ]
writeFile(akt_preds_adapB, "ICBP_akt_drug_cors_allcombos_adapB.txt")
akt_preds_adap_adap<-akt_preds[grepl("*/adap_adap*", rownames(akt_preds)), ]
writeFile(akt_preds_adap_adap, "ICBP_akt_drug_cors_allcombos_adap_adap.txt")

her2_preds<-temp_f[grepl("*/her2__*", rownames(temp_f)), ]
her2_preds_adapB<-her2_preds[grepl("*/adapB_*", rownames(her2_preds)), ]
writeFile(her2_preds_adapB, "ICBP_her2_drug_cors_allcombos_adapB.txt")
her2_preds_adap_adap<-her2_preds[grepl("*/adap_adap*", rownames(her2_preds)), ]
writeFile(her2_preds_adap_adap, "ICBP_her2_drug_cors_allcombos_adap_adap.txt")

igf1r_preds<-temp_f[grepl("*/igf1r__*", rownames(temp_f)), ]
igf1r_preds_adapB<-igf1r_preds[grepl("*/adapB_*", rownames(igf1r_preds)), ]

writeFile(igf1r_preds_adapB, "ICBP_igf1r_drug_cors_allcombos_adapB.txt")
igf1r_preds_adap_adap<-igf1r_preds[grepl("*/adap_adap*", rownames(igf1r_preds)), ]
writeFile(igf1r_preds_adap_adap, "ICBP_igf1r_drug_cors_allcombos_adap_adap.txt")



matrix(cbind(rhos,p_val),ncol=2)

pred_drug_AKT=pred_drug_only[,c(1:80,165)]
pred_drug_AKT
dim(pred_drug_AKT)
colnames(pred_drug_only)
View(pred_drug)



sigmaAKTcors= cor.ci(pred_drug_AKT, method="spearman", plot=FALSE)
sigmaAKTcors$ci[5]
sigmaAKTcors$rho[2,1]

bind = cbind(pred_drug_only[,1], pred_drug_only[,165])
View(bind)
# cors = matrix(0,144,4)
# rownames(cors)=colnames(pred_drug)[1:144]
#colnames(cors)=c("Lapatinib","Sigma.akt.1.2.inhibitor","Temsirolimus","Everolimus")
#pathways<-data_icbp
#drugs<-drugs$Sigma.AKT1.2.inhibitor
#akt_preds<-subset(pred_drug,select=grep("/akt", colnames(pred_drug) , ignore.case=FALSE, fixed=T))
#akt_adapB<-subset(akt_preds,select=grep("/adapB_multi", colnames(akt_preds) , ignore.case=FALSE, fixed=T))
#akt_adap_adap<-subset(akt_preds,select=grep("/adap_adap_mult", colnames(akt_preds) , ignore.case=FALSE, fixed=T))
#min(corr.test(cbind(akt_preds,pred_drug$Sigma.AKT1.2.inhibitor),method="spearman", use="pairwise")$p[,33])


bad_preds<-subset(pred_drug,select=grep("/bad", colnames(pred_drug) , ignore.case=FALSE, fixed=T))
her2_preds<-subset(pred_drug,select=grep("/her2", colnames(pred_drug) , ignore.case=FALSE, fixed=T))
igf1r_preds<-subset(pred_drug,select=grep("/igf1r", colnames(pred_drug) , ignore.case=FALSE, fixed=T))
erk_preds<-subset(pred_drug,select=grep("/erk", colnames(pred_drug) , ignore.case=FALSE, fixed=T))
length(bad_preds)

adapB<-subset(pred_drug,select=grep("adapB",colnames(pred_drug)))
adapS<-subset(pred_drug,select=grep("adap_adap",colnames(pred_drug)))

##############

#### Bootstrap:
dim(data_icb)
pathways = 160 # number of pathway signatures
samplesize = nrow(pred_drug_only) # number of cell lines
n.boot = 10000 # number of bootstrap samples -- set at 10,000 or more for your final run

all_boot_cors = array(0,dim=c(160,90,n.boot)) # make a three dimensional array to store the bootstrap results

# added spearman here, it did not have it 
for (i in 1:n.boot){
  boot.sample = sample(1:samplesize,replace=T)
  all_boot_cors[,,i]=cor(pred_drug_only[boot.sample,1:160],pred_drug_only[boot.sample,161:250],use="pairwise", method="spearman")
  }

dim(akt_boot_cors) #24 x 90 x 10000

#  to test 
p_calc_compare=function(path1,path2,drug,cor_cut=0,cors=boot_cors,pathlist=pathway,druglist=drugs){
  ind_p1 = which(pathlist==path1)
  ind_p2 = which(pathlist==path2)
  ind_drug = which(druglist==drug)
  mean((cors[ind_p1,ind_drug,]-cors[ind_p2,ind_drug,])>cor_cut,na.rm=T)
}


pval_comp_akt_adapB_vs_adap_adap = p_calc_compare(combn(colnames(akt_adap_adap),1),combn(colnames(akt_adapB),1),cors=akt_boot_cors, drug="Sigma.AKT1.2.inhibitor",pathlist = colnames(akt_preds),druglist = pred_drug[171:260] )
head(pval_comp)

# # means
# cor_mean = apply(boot_cors, c(1,2), mean, na.rm=T)  ## average bootstrap cors. Should be similar to the non-boot values
# dimnames(cor_mean)=dimnames(drug_prediction_correlations_multi_spear)
# View(cor_mean)
# write.table(cor_mean,"~/Documents/ThesisWork/GitRepos/bild_signatures/cor_mean.txt",sep='\t', col.names = NA,quote=F)
# cor_means_ICBP=read.delim("~/Documents/ThesisWork/GitRepos/bild_signatures/cor_mean.txt", header=1, sep='\t',row.names=1)
# 
# #lower
# lower = apply(boot_cors, c(1,2), quantile,na.rm=T,probs=.025) ## lower 95% CI
# dimnames(lower)=dimnames(drug_prediction_correlations_multi_spear)
# write.table(lower,"~/Documents/ThesisWork/GitRepos/bild_signatures/lower.txt",sep='\t', col.names = NA,quote=F)
# cor_lower_ICBP=read.delim("~/Documents/ThesisWork/GitRepos/bild_signatures/lower.txt", header=1, sep='\t',row.names=1)
# #upper
# 
# upper = apply(boot_cors, c(1,2), quantile,na.rm=T,probs=.975) ## upper 95% CI
# dimnames(upper)=dimnames(drug_prediction_correlations_multi_spear)
# write.table(upper,"~/Documents/ThesisWork/GitRepos/bild_signatures/upper.txt",sep='\t', col.names = NA,quote=F)
# cor_upper_ICBP=read.delim("~/Documents/ThesisWork/GitRepos/bild_signatures/upper.txt", header=1, sep='\t',row.names=1)


## p-values: to test that a correlation is bigger than some value:

# is this the p-value that is it bigger than some value??
 
cor_cutoff = 0 ## i.e. to test is the correlation is > or < 0. Note this can be anything, i.e. .1, .5, etc
p_calc = function(x,direction="greater",cor_cut=0){
  if (!(direction %in% c("greater","less"))){stop("Invalid value for direction")}
  if (direction=="greater"){return(mean(x>cor_cut,na.rm=T))}
  if (direction=="less"){return(mean(x<cor_cut,na.rm=T))}
  }

head(boot_cors)
# These are not p-values, or are they, they just seem like correlations above or below a certain value
# Obtaining the cor means for all 10000 interations that are either above or below a certain value for all rows and columns. 
# I think above and below equal to 1...

View(boot_cors)
# This just contains the means from the 10000 bootstrap cor values above 0
# I dont get how you can get different p-values for the same correlation?
ps_above_0 = apply(boot_cors, c(1,2), p_calc)
dimnames(ps_above_0)=dimnames(drug_prediction_correlations_multi_spear)
View(ps_above_0)
dim(ps_above_0)

ps_below_0 = apply(boot_cors, c(1,2), p_calc,direction="less")
dimnames(ps_below_0 )=dimnames(drug_prediction_correlations_multi_spear)
View(ps_below_0)
dim(ps_below_0)

## p-values: to test two correlations against each other:
pathway = colnames(pred_drug_multi)[1:25]  ## print to see the pathway names
print(pathway)
drugs = colnames(pred_drug_multi)[36:125]  ## print to see the drug names
print(drugs)

#  to test 
p_calc_compare=function(path1,path2,drug,cor_cut=0,cors=boot_cors,pathlist=pathway,druglist=drugs){
  ind_p1 = which(pathlist==path1)
  ind_p2 = which(pathlist==path2)
  ind_drug = which(druglist==drug)
  mean((cors[ind_p1,ind_drug,]-cors[ind_p2,ind_drug,])>cor_cut,na.rm=T)
}


pval_comp = p_calc_compare("AKT_BAD.adap_multi.pathway_activity_testset.csv.akt","AKT_BAD_HER2.adap_multi.pathway_activity_testset.csv.akt","Sigma.AKT1.2.inhibitor")
head(pval_comp)

 ## pval_comp = 0.91 in this case means that AKT+BAD > AKT+BAD+HER2 in 91% of the bootstrap correlations. Thus the p-value for testing Ha: AKT+BAD > AKT+BAD+HER2 is 0.09










#######################
library(psych)
for (i in 1:length(colnames(data_icbp))){
  for (j in 1:1){ #length(colnames(drug_srt))){
    cors[i,j]=corr.test(pred_drug[,i],pred_drug$Sigma.AKT1.2.inhibitor,use="pairwise",method="spearman")
  }
}

View(drug_pre_diction_correlations_multi)
View(drug_prediction_correlations_single)

single_and_multi= rbind(drug_prediction_correlations_multi,drug_prediction_correlations_single)
plot(single_and_multi[2])
View(single_and_multi)

row.names(single_and_multi)

# for sinlge
single_and_multi[26,]
cor(single_and_multi[26,], single_and_multi[27,] ) # 0.5269367
cor(single_and_multi[26,], single_and_multi[28,] ) #0.7882588
cor(single_and_multi[26,], single_and_multi[29,] ) # 0.6173746
cor(single_and_multi[27,], single_and_multi[28,] ) # 0.2896494
cor(single_and_multi[27,], single_and_multi[29,] ) # -0.02523773
cor(single_and_multi[28,], single_and_multi[29,] ) # 0.7182353

#mutli
cor(single_and_multi[22,], single_and_multi[23,] )  #-0.6161527
cor(single_and_multi[22,], single_and_multi[24,] ) # -0.2015345
cor(single_and_multi[22,], single_and_multi[25,] ) # 0.4247083
cor(single_and_multi[23,], single_and_multi[24,] ) # -0.04692151
cor(single_and_multi[23,], single_and_multi[25,] ) # -0.4218923
cor(single_and_multi[24,], single_and_multi[25,] ) # -0.7734885

write.table(single_and_multi,"~/Documents/ThesisWork/GitRepos/bild_signatures/Correlations_ICBP_Single_Multi.txt",sep='\t', col.names = NA,quote=F)

```

Testing cor.ci

```{r}
data_icbp_small=data_icbp[,1:3]
cor(data_icbp_small)


corr.test(data_icbp_small, use= "pairwise", method= "spearman")
ci = cor.ci(data_icbp_small, use= "pairwise", method= "spearman", plot=FALSE)
ci[6]
ci$ci[5]

```


