---
title: "heatmaps using TCGA BRCA datasets"
output: html_document
---

```{r include=FALSE}
merge_drop<-function(x,y,by=0)
{
  new_m<-merge(x,y,by=by)
  rownames(new_m)<-new_m$Row.names
  return(new_m[,2:length(colnames(new_m))])
}


setwd("~/Dropbox/bild_signatures/multi_tcga_expr_pc/")
filenames<-system("ls */*/pathway_activity_testset*", intern=TRUE)
filenames<-c(filenames,system("ls */*/*/pathway_activity_testset*", intern=TRUE))
filenames

for(i in 1:length(filenames))
  {
   f<-read.csv(filenames[i], header=1,row.names=1) ###reading in the filess one at a time
  colnames(f)<-paste(filenames[i],colnames(f),sep='/')
  if(i==1){
    data<-f
    }
  else{
    data<-cbind(data,f)
    }
  }
#write.table(data,"~/Desktop/multipathway_preds.txt",sep='\t', col.names = NA,quote=F)
####correlating pathway predictions within TCGA BRCA samples using simple and bootstrap methods
prediction_correlations_multi= cor(data[1:8],data[1:8],use="na.or.complete",method="spearman")
prediction_correlations_single= cor(data[9:16],data[9:16],use="na.or.complete",method="spearman")
write.table(prediction_correlations_multi,"~/Desktop/mulit_within_cors.txt",sep='\t',col.names = NA, quote=F)
write.table(prediction_correlations_single,"~/Desktop/single_within_cors.txt",sep='\t',col.names = NA, quote=F)
#### Bootstrap:
#pathways = 25 # number of pathway signatures
samplesize = nrow(data) # number of cell lines
n.boot = 1000 # number of bootstrap samples -- set at 10,000 or more for your final run

boot_cors = array(0,dim=c(4,4,n.boot)) # make a three dimensional array to store the bootstrap results

for (i in 1:n.boot){
  boot.sample = sample(1:samplesize,replace=T)
  boot_cors[,,i]=cor(data[boot.sample,1:4],data[boot.sample,1:4],use="na.or.complete",method = "spearman")
  }
colnames(boot_cors)=rownames(boot_cors)=rownames(cor_mean)=colnames(cor_mean)=colnames(data)[1:4]
cor_mean = apply(boot_cors, c(1,2), mean, na.rm=T)  ## average bootstrap cors. Should be similar to the non-boot values
lower = apply(boot_cors, c(1,2), quantile,na.rm=T,probs=.025) ## lower 95% CI
upper = apply(boot_cors, c(1,2), quantile,na.rm=T,probs=.975) ## upper 95% CI
for (i in 1:4){
  print(c(lower[1,i],cor_mean[1,i], upper[1,i]))
  print(c(lower[2,i],cor_mean[2,i], upper[2,i]))  ## print the upper, mean, lower for first pathway and first drug
  print(c(lower[3,i],cor_mean[3,i], upper[3,i]))
  print(c(lower[4,i],cor_mean[4,i], upper[4,i]))
  }
write.table(boot_cors,"~/Desktop/boot_mulit_within_cors.txt",sep='\t',col.names = NA, quote=F)
####


drug_prediction_correlations_single= cor(pred_drug_single[1:4],pred_drug_single[15:104],use="na.or.complete")

single_and_multi= rbind(drug_prediction_correlations_multi,drug_prediction_correlations_single)

write.table(single_and_multi,"Correlations_ICBP_Single_Multi2.txt",sep='\t', col.names = NA,quote=F)

####brca patient clinical data
brca_clin<-read.table("~/Dropbox/bild_signatures/Datasets/nationwidechildrens.org_clinical_drug_brca.txt", header=1,sep='\t')
brca_clin_f<-brca_clin[3:1601,1:12]
#brca_chem<-subset(brca_clin_f, brca_clin_f$pharmaceutical_therapy_type=="Chemotherapy"&brca_clin_f$bcr_patient_barcode%in%unique(brca_clin_f$bcr_patient_barcode))
brca_chem<-brca_clin_f
brca_clincal<-read.csv("~/Dropbox/TCGA_PANCAN20_manuscript/Datasets/nationwidechildrens.org_clinical_patient_brca.txt",row.names=1, header=1,sep='\t')
brca_pat<-brca_clincal[3:1019,]
brca_pat$newID<-gsub(pattern='-', replacement='.', x=rownames(brca_pat))
brca_chem$newID<-gsub(pattern='-', replacement='.', x=brca_chem$bcr_patient_barcode)
clin<-merge(brca_chem,brca_pat,by.x='newID',by.y='newID')
brca_chem<-clin
unique(brca_chem$bcr_patient_barcode)
counter=0
for (j in 1:length(brca_chem$newID)){
    if(!is.na(pmatch(brca_chem$newID[j],rownames(data)))){
      brca_chem$newID[j]<-rownames(data)[pmatch(brca_chem$newID[j],rownames(data), duplicates.ok=F)]  
      counter=counter+1
    }
}
counter
bad_exp<-merge(data,brca_chem,by.x = 0,by.y='newID')
#filtering out the sample with no hormonal status info
all_bad<-subset(bad_exp,(bad_exp$pr_status_by_ihc!=c("[Not Evaluated]")&bad_exp$er_status_by_ihc!="[Not Evaluated]"&bad_exp$her2_status_by_ihc!=c("[Not Evaluated]")))#,"Indeterminate","Equivocal")))
all_bad<-subset(bad_exp,(bad_exp$tumor_status=="TUMOR FREE"|bad_exp$tumor_status=="WITH TUMOR")&(bad_exp$treatment_best_response=="Complete Response"|bad_exp$treatment_best_response=="Clinical Progressive Disease"))#&bad_exp$pr_status_by_ihc!="Positive"&bad_exp$er_status_by_ihc!="Positive"&bad_exp$her2_status_by_ihc!="Positive")
all_bad_vit<-subset(all_bad,all_bad$vital_status=="Alive"|all_bad$vital_status=="Dead")
all_bad_tumor_status<-subset(all_bad,all_bad$tumor_status=="TUMOR FREE"|all_bad$tumor_status=="WITH TUMOR")
par( mfrow = c( 1,1 ) ,lwd=4)

dim(all_bad)
dim(all_bad_vit)
dim(all_bad_tumor_status)

summary(all_bad$treatment_best_response)
summary(all_bad$tumor_status)
summary(all_bad$er_status_by_ihc)
summary(all_bad$pr)

alive=subset(all_bad,all_bad$vital_status=='Alive')
dead=subset(all_bad,all_bad$vital_status=="Dead")
boxplot(alive[,3]~alive$er_status_by_ihc)#,dead[,3]~dead$er_status_by_ihc)
boxplot(all_bad[,3]&all_bad$tumor_status=="Alive")
boxplot(all_bad[,3]~all_bad$vital_status)
#all_bad<-subset(bad_exp,bad_exp$treatment_best_response=="Complete Response"|bad_exp$treatment_best_response=="Clinical Progressive Disease")#|all_bad[,3]>0.45|all_bad[,3]<0.25)
#all_bad[,11]<-rank(all_bad[,11])
summary(all_bad$treatment_best_response)
summary(all_bad$tumor_status)

#com_bad<-subset(all_bad,all_bad$treatment_best_response=="Complete Response"|all_bad$tumor_status=="TUMOR FREE")
com_bad<-subset(all_bad,all_bad$tumor_status=="TUMOR FREE")
dim(com_bad)
herceptin_samples<-c('TCGA.AC.A2FB.01A.11R.A17B.07','TCGA.AQ.A04H.01B.11R.A10J.07','TCGA.BH.A0HY.01A.11R.A056.07','TCGA.E2.A3DX.01A.21R.A213.07')

com_bad_f<-com_bad[!com_bad[,1]%in%herceptin_samples,]    
dim(com_bad_f)
not_bad<-subset(all_bad,all_bad$treatment_best_response=="Clinical Progressive Disease"|all_bad$tumor_status=="WITH TUMOR")
not_bad<-subset(all_bad,all_bad$tumor_status=="WITH TUMOR")
dim(not_bad)

#write.table(not_bad,"~/Desktop/low_bad.txt",sep='\t')
##4th element sample "TCGA-A2-A3XU" received hormanal therapy(arimidex). so excluding this TCGA-A2-A3XU
not_bad<-not_bad[-7,]
par(mfrow = c(1, 1))
par(mar=c(5.6, 4.1, 1.5, 0.5)) 
boxplot(com_bad[,3],not_bad[,3],main="BAD pathway prediction in TCGA patients receiving chemotherapy",names=c("Complete Response\n or TUMOR FREE","Clinical Progressive Disease\n or WITH TUMOR"))
#text(0,0,"p-val= 2.223e-05")

t.test(com_bad_f[,3],not_bad[,3])
wilcox.test(com_bad_f[,3],not_bad[,3])

t.test(com_bad[,3],not_bad[,3])
wilcox.test(com_bad[,3],not_bad[,3])


boxplot(com_bad[,11],not_bad[,11],names=c("Complete Response\n or TUMOR FREE","Clinical Progressive Disease\n or WITH TUMOR"))
t.test(com_bad[,11],not_bad[,11])


dim(com_bad)
dim(not_bad)
```

Creating heatmaps

```{r include=FALSE}

if (!require("gplots")) {
   install.packages("gplots", dependencies = TRUE)
   library(gplots)
   }
if (!require("RColorBrewer")) {
   install.packages("RColorBrewer", dependencies = TRUE)
   library(RColorBrewer)
   }
prediction_heatmap<-function(x,type=NULL)
{
    x_m<-x[,1:4]
    colnames(x_m)<-c("AKT_multi","BAD_multi","HER2_multi","IGF1R_multi")
    heatmap.2(as.matrix(x_m),col=my_palette,margins=c(10,9),dendrogram="none", trace="none",main=paste("Multi Adap Pathway","Activation Status",type,sep = "\n "),Rowv = NULL, Colv = NULL,density.info = "none",scale = 'row')
    x_s<-subset(x, select=c(9,11,13,15))
    colnames(x_s)<-c("AKT","BAD","HER2","IGF1R")
    heatmap.2(as.matrix(x_s),col=my_palette,margins=c(10,9),dendrogram="none",Rowv = NULL, Colv = NULL, trace="none",main=paste("Single Adap Pathway"," Activation Status",type,sep = "\n"),density.info = 'none',scale = 'row')
}

pam50<-read.table("~/Dropbox/Datasets/tcga_breast_pam50.txt",sep='\t', stringsAsFactors = T,header=T, row.names=1)
partial_sample_names<-rownames(pam50)
sample_names<-rownames(data)
counter=0
for (j in 1:length(partial_sample_names)){
    if(!is.na(pmatch(partial_sample_names[j],sample_names))){
      partial_sample_names[j]<-sample_names[pmatch(partial_sample_names[j],sample_names, duplicates.ok=F)]  
      counter=counter+1
    }
}
rownames(pam50)<-partial_sample_names
my_palette <- colorRampPalette(c("darkblue","aliceblue","brown4"))(n = 299)
col_breaks = c(seq(0,0.2,length=100), seq(0.2,0.4,length=100), seq(0.4,1,length=100)) 

pred_sub<-merge_drop(data,pam50,by=0)
colnames(pred_sub)<-gsub(pattern = "pathway_activity_testset.csv",replacement = "",x = colnames(pred_sub))

```

Creating  heatmaps for predictions and drug response correlatins with pathway activity within subtypes

```{r}
basal<-subset(pred_sub,pred_sub$PAM50.mRNA=="Basal-like")
prediction_heatmap(x=basal,type = "Basal")

her<-subset(pred_sub,pred_sub$PAM50.mRNA=="HER2-enriched")
prediction_heatmap(x=her,type = "ERBB2 Amplified")

luminal<-subset(pred_sub,pred_sub$PAM50.mRNA=="Luminal A"|pred_sub$PAM50.mRNA=="Luminal B")
prediction_heatmap(x=luminal,type = "Luminal")
normal<-subset(pred_sub,pred_sub$PAM50.mRNA=="Normal-like")
prediction_heatmap(x=normal,type = "Normal-like")
```

Now, trying to see patterns across all the subtypes in ICBP breast cancer cell lines

```{r}
multi_4<- rbind(basal[,1:4],her[,1:4],luminal[,1:4],normal[,1:4])
heatmap.2(as.matrix(multi_4), RowSideColors = c(rep("gray", length(rownames(basal))),rep("blue", length(rownames(her))),rep("black", length(rownames(luminal))),rep("green",length(rownames(normal)))),col=my_palette,dendrogram="none", trace="none",margins=c(12,9),main="Multi Preds within Subtypes",scale='row',Rowv=F,Colv=F)
par(lend = 1)           # square line ends for the color legend
legend("topright",legend = c("Basal", "HER2", "Luminal","Normal-like"), col = c("gray", "blue", "black","green"),  lty= 1,lwd = 10)

single_4<-rbind(basal[,c(9,11,13,15)],her[,c(9,11,13,15)],luminal[,c(9,11,13,15)],normal[,c(9,11,13,15)])
heatmap.2(as.matrix(single_4), RowSideColors = c(rep("gray", length(rownames(basal))),rep("blue", length(rownames(her))),rep("black", length(rownames(luminal))),rep("green",length(rownames(normal)))),col=my_palette,dendrogram="none", trace="none",margins=c(12,9),main="Single Preds within Subtypes",scale="row",Rowv=F,Colv=F)
par(lend = 1)           # square line ends for the color legend
legend("topright",legend = c("Basal", "HER2", "Luminal","Normal-like"), col = c("gray", "blue", "black","green"),  lty= 1,lwd = 10)

```

```{r echo=FALSE}
time<-format(Sys.time(),"%a %b %d %X %Y")
```
This analysis was run on `r time` 

