---
title: "HER2 Signature Validation with ICBP drugs and with CCLE CNV data"
author: "Mumtahena Rahman"
date: "December 17, 2014"
output: pdf_document
---
```{r include=FALSE}
library(sva)
library(ASSIGN)
setwd("~/Dropbox/Datasets/")
merge_drop<-function(x,y,by=0)
{
  new_m<-merge(x,y,by=by)
  rownames(new_m)<-new_m$Row.names
  return(new_m[,2:length(colnames(new_m))])
}
pcaplot<-function(mat,sub,scale=T){
  if(sum(sub)!=length(mat)){
    print("verify the subscripts...exiting now")
    }
  else{
    pca_mat <- prcomp(t(mat), center=T,scale=scale)
    plot(pca_mat)
    plot(pca_mat$x[,1],pca_mat$x[,2])
    index= 1
    for(i in 1:length(sub)){
      #print(rownames(pca_mat$x)[index:sub[i]+index-1],"has color", )
      print(i)
      if(i==1){
        points(pca_mat$x[1:sub[i]],pca_mat$x[1:sub[i],2],col=i+1)
        }
      else if(i==length(sub)){
         points(pca_mat$x[index:length(rownames(pca_mat$x))],pca_mat$x[index:length(rownames(pca_mat$x)),2],col=i+1)
         }
      else{
        points(pca_mat$x[index:index+sub[i]],pca_mat$x[index:index+sub[i],2],col=i+1)
        }
       index=index+sub[i]
      }
  }
}
```
Reading datasets in...and calling assign..

```{r, cache=TRUE, include=FALSE}
feature<-as.matrix(read.table("~/Dropbox/Datasets/GFP18_AKT_BAD_HER2_IGF1R_RAF_ERK.tpmlog", sep='\t', stringsAsFactors=FALSE, header=1, row.names=1))
#head(feature)
icbp<-as.matrix(read.table("~/Dropbox/ICBP/icbp_Rsubread_tpmlog.txt", sep='\t', stringsAsFactors=FALSE, header=1, row.names=1))
#head(icbp)

gfp_her2<-subset(feature,select=c(GFP.1:GFP.12,HER2.1:HER2.6))
gfp_her2_1 <- gfp_her2[apply(gfp_her2[,1:17]==0,1,mean) < 0.8,]###if not removed over 83%; error occurs in batch adjustment

gfp_her2_1_icbp<-merge_drop(gfp_her2_1,icbp,by=0)
#head(gfp_her2_1_icbp)
sub<-c(12,5,55)
##############Batch adjustment is needed############
#with covariates
bat1<-as.matrix(cbind(c(colnames(gfp_her2_1),colnames(icbp)),c(rep(1,length(colnames(gfp_her2_1))),rep(2,length(colnames(icbp)))),c(rep(1,12),rep(2,5),rep(1,55))))
#head(bat1)
#bat1[,2]
mod <- model.matrix(~as.factor(bat1[,3]))
combat_expr1<-ComBat(dat=gfp_her2_1_icbp, batch=bat1[,2], mod=mod, numCovs=NULL)
pcaplot(mat = combat_expr1,sub=sub)
#Combat without covariates
combat_expr2<-ComBat(dat=gfp_her2_1_icbp, batch=bat1[,2], mod=NULL, numCovs=NULL)
pcaplot(mat = combat_expr2,sub=sub)
##########calling ASSIGN########
###making a easy to call ASSIGN function#######
assign_easy<-function(trainingData=train, testData=test, trainingLabel1=NULL,g=100,out_dir_base="~/Desktop/tmp",cov=0){
if(cov==0){
  adap_folder<-paste(out_dir,paste( "adap",g,sep=''),sep='/')
  dir.create(file.path(out_dir,paste( "adap",g,sep='')))
  nonadap_folder<-paste(out_dir,paste( "nonadap",g,sep=''),sep='/')
  dir.create(file.path(out_dir,paste( "nonadap",g,sep='')))
  }
else{
  adap_folder<-paste(out_dir,paste( "adap_cov",g,sep=''),sep='/')
  dir.create(file.path(out_dir,paste( "adap_cov",g,sep='')))
  nonadap_folder<-paste(out_dir,paste( "nonadap_cov",g,sep=''),sep='/')
  dir.create(file.path(out_dir,paste( "nonadap_cov",g,sep='')))
}

set.seed(1234)
assign.wrapper(trainingData=trainingData, testData=testData, trainingLabel=trainingLabel1, testLabel=NULL, geneList=NULL, n_sigGene=g, adaptive_B=T, adaptive_S=F, mixture_beta=F, outputDir=adap_folder, theta0=0.05, theta1=0.9, iter=2000, burn_in=1000)  

set.seed(1234)
assign.wrapper(trainingData=trainingData, testData=testData, trainingLabel=trainingLabel1, testLabel=NULL, geneList=NULL, n_sigGene=g, adaptive_B=F, adaptive_S=F, mixture_beta=F, outputDir=nonadap_folder, theta0=0.05, theta1=0.9, iter=2000, burn_in=1000)  

}



#### Use big reg genes
brgenes = read.table('~/Dropbox/EVAN/9_17/Results/ICBP/BinReg results/BinReg_dwd_bild_her2_100/model.txt',header=T)
brlist = list(her2=as.character(brgenes[-1,1]))

train_her2_cov<-combat_expr1[,1:17]
test_cov<-combat_expr1[,18:72]

train_her2<-combat_expr2[,1:17]
test<-combat_expr2[,18:72]

# dir.create("~/Desktop/tmp/her2_single_100_genelist_cov/")#, 
# set.seed(1234)
# assign.wrapper(trainingData=train_her2_cov, testData=test_cov,trainingLabel=trainingLabel1, testLabel=NULL,  geneList=brlist, n_sigGene=100, adaptive_B=F, adaptive_S=T, mixture_beta=F, outputDir="~/Desktop/tmp/her2_single_100_genelist_cov/", theta0=0.05, theta1=0.9, iter=2000, burn_in=1000)
# 
# dir.create("~/Desktop/tmp/her2_single_100_genelist_adap_cov/")#, 
# set.seed(1234)
# assign.wrapper(trainingData=train_her2_cov, testData=test_cov,trainingLabel=trainingLabel1, testLabel=NULL,  geneList=brlist, n_sigGene=100, adaptive_B=T, adaptive_S=T, mixture_beta=F, outputDir="~/Desktop/tmp/her2_single_100_genelist_cov/", theta0=0.05, theta1=0.9, iter=2000, burn_in=1000)
# 
# dir.create("~/Desktop/tmp/her2_single_100_genelist/")#, 
# set.seed(1234)
# assign.wrapper(trainingData=train_her2, testData=test,trainingLabel=trainingLabel1, testLabel=NULL,  geneList=brlist, n_sigGene=100, adaptive_B=F, adaptive_S=T, mixture_beta=F, outputDir="~/Desktop/tmp/her2_single_100_genelist/", theta0=0.05, theta1=0.9, iter=2000, burn_in=1000)
# 
# dir.create("~/Desktop/tmp/her2_single_100_genelist_adap/")#, 
# set.seed(1234)
# assign.wrapper(trainingData=train_her2, testData=test,trainingLabel=trainingLabel1, testLabel=NULL,  geneList=brlist, n_sigGene=100, adaptive_B=T, adaptive_S=T, mixture_beta=F, outputDir="~/Desktop/tmp/her2_single_100_genelist//", theta0=0.05, theta1=0.9, iter=2000, burn_in=1000)
# 
# assign_easy(trainingData=train_her2, testData = test,trainingLabel1=trainingLabel1,g=50)
# assign_easy(trainingData=train_her2, testData = test,trainingLabel1=trainingLabel1,g=25)
# assign_easy(trainingData=train_her2, testData = test,trainingLabel1=trainingLabel1,g=5)
# assign_easy(trainingData=train_her2, testData = test,trainingLabel1=trainingLabel1,g=15)
# assign_easy(trainingData=train_her2, testData = test,trainingLabel1=trainingLabel1,g=20)
# assign_easy(trainingData=train_her2_cov, testData = test_cov,trainingLabel1=trainingLabel1,g=50,cov=1)
# assign_easy(trainingData=train_her2_cov, testData = test_cov,trainingLabel1=trainingLabel1,g=25,cov=1)

setwd("~/Desktop/tmp/")
filenames<-system("ls */pathway_activity_testset*", intern=TRUE)
#filenames

for(i in 1:length(filenames))
  {
   f<-read.csv(filenames[i], header=1,row.names=1) ###reading in the filess one at a time
  colnames(f)<-filenames[i]
  if(i==1){
    data<-f
    }
  else{
    data<-cbind(data,f)
    }
  }
```

Now correlating HER2 predictions with ICBP drugs..
```{r, cache=TRUE}
drugs<-read.delim("~/Dropbox/ICBP/ICBP_drugs_1.txt", header=1, sep='\t',row.names=1)
pred_drug<-merge_drop(data,drugs,by=0)
#dim(pred_drug)
for(i in 1:length(colnames(data)))
  {
  #print(colnames(data)[i])
  print("correlation with Lapatinib..an EGFR/HER2 inhibitor")
  print(cor(pred_drug[i],pred_drug$Lapatinib,use="na.or.complete"))
#   print("correlation with BEZ235..a pi3k/mtor inhibitor")
#   print(cor(pred_drug[i],pred_drug$BEZ235,use="na.or.complete"))
#   print("correlation with Everolimus..an mtor inhibitor")
#   print(cor(pred_drug[i],pred_drug$Everolimus,use="na.or.complete"))
#   print("correlation with Temsirolimus..an mtor inhibitor")
#   print(cor(pred_drug[i],pred_drug$Temsirolimus,use="na.or.complete"))
  print("correlation with Sigma AKT1/2..an AKT  inhibitor")
  print(cor(pred_drug[i],pred_drug$Sigma.AKT1.2.inhibitor,use="na.or.complete"))
#   print("correlation with GSK2126458..an AKT  inhibitor")
#   print(cor(pred_drug[i],pred_drug$GSK2126458,use="na.or.complete"))
#   print("correlation with TRIciribine..an AKT  inhibitor")
#   print(cor(pred_drug[i],pred_drug$Triciribine,use="na.or.complete"))
#   
  }
```

If you are interested in signature gene matrix...
```{r cache=TRUE, echo=FALSE}
setwd("~/Desktop/tmp/")
out<-system("ls */*.rda", intern=TRUE)

for(i in 1:length(out))
  {
  out[i] 
  load(out[i])
  output.data$processed.data$S_matrix
  }

```

Now correlating with CNV data...
```{r echo=FALSE,cache=TRUE}
ccle_cnv<-read.table("~/Dropbox/EVAN/9_17/CCLE_copynumber_byGene_2013-12-03.txt", header=1)
rownames(ccle_cnv)<-ccle_cnv$SYMBOL
her2_cnv<-ccle_cnv["ERBB2",]
her2interested_cnv<-her2_cnv[,grep("_BREAST",colnames(her2_cnv))]

colnames(her2interested_cnv)<-gsub(pattern = "_BREAST",replacement = "",colnames(her2interested_cnv)) 
#colnames(her2interested_cnv)

cnv = matrix(her2interested_cnv["ERBB2",],ncol=1)
rownames(cnv) = names(her2interested_cnv["ERBB2",])

combined = merge_drop(cnv, data, by=0)

for(i in 2:(length(colnames(data))+1))
{

  print(paste("pearson's correlation between ERBB2 CNV and ",colnames(combined)[i]),sep='')
  print(cor(as.numeric(combined$V1),as.numeric(combined[,i]),use="na.or.complete"))

  }


```




```{r echo=FALSE}
time<-format(Sys.time(),"%a %b %d %X %Y")
```
This analysis was run on `r time` 
