resistant_or_sensitive=function(value,cutoff){
  if(value>cutoff){
  status='S'
  }
  else{
  status='R'
  }
  return (status)
}
short_to_long_TCGA_id=function(longnames=NULL,shortnames=NULL){
  counter=0
  for (j in 1:length(shortnames)){
    if(!is.na(pmatch(shortnames[j],longnames))){
      shortnames[j]<-longnames[pmatch(shortnames[j],longnames, duplicates.ok=F)]  
      counter=counter+1
    }
  }
  print(paste(counter,"names have been changed",sep= " "))
  return(shortnames)
}

merge_drop<-function(x,y,by=0,...)
{
  new_m<-merge(x,y,by=by,...)
  rownames(new_m)<-new_m$Row.names
  return(new_m[,2:length(colnames(new_m))])
}


pcaplot<-function(mat,sub,center=T,scale=T){
  if(sum(sub)!=length(mat))
    {
    print("verify the subscripts...exiting now")
    }
  else{
    pca_mat <- prcomp(t(mat), center=center,scale=scale)
    plot(pca_mat)
    plot(pca_mat$x[,1],pca_mat$x[,2])
    abline(h=0,v=0)
    for(i in length(sub):1)
      {
      print(i)
      if(i!=1)
        {
          points(pca_mat$x[sum(sub[1:i-1]):sum(sub[1:i])],pca_mat$x[sum(sub[1:i-1]):sum(sub[1:i]),2],col=i)
        }
      else #if(i==1)
        {
        points(pca_mat$x[1:sub[i]],pca_mat$x[1:sub[i],2],col=i)
        }
      }
  }
}

assign_easy<-function(trainingData=train, testData=test, trainingLabel1=NULL,g=100,out_dir_base="~/Dropbox/bild_signatures/",cov=0){
if(cov==0){
  adap_folder<-paste(out_dir,paste( "adap",g,sep=''),sep='/')
  dir.create(file.path(out_dir,paste( "adap",g,sep='')))
  nonadap_folder<-paste(out_dir,paste( "nonadap",g,sep=''),sep='/')
  dir.create(file.path(out_dir,paste( "nonadap",g,sep='')))
  }
else{
  adap_folder<-paste(out_dir,paste( "adap_cov",g,sep=''),sep='/')
  dir.create(file.path(out_dir,paste( "adap_cov",g,sep='')))
  nonadap_folder<-paste(out_dir,paste( "nonadap_cov",g,sep=''),sep='/')
  dir.create(file.path(out_dir,paste( "nonadap_cov",g,sep='')))
}

set.seed(1234)
assign.wrapper(trainingData=trainingData, testData=testData, trainingLabel=trainingLabel1, testLabel=NULL, geneList=NULL, n_sigGene=g, adaptive_B=T, adaptive_S=F, mixture_beta=F, outputDir=adap_folder, theta0=0.05, theta1=0.9, iter=2000, burn_in=1000,p_beta=0.5)  

set.seed(1234)
assign.wrapper(trainingData=trainingData, testData=testData, trainingLabel=trainingLabel1, testLabel=NULL, geneList=NULL, n_sigGene=g, adaptive_B=F, adaptive_S=F, mixture_beta=F, outputDir=nonadap_folder, theta0=0.05, theta1=0.9, iter=2000, burn_in=1000,...)  

}

## 
# 1 = true, 0 = false
assign_easy_multi<-function(trainingData=train, testData=test, trainingLabel1=NULL,g=100,out_dir_base="~/Desktop/tmp",cov=0, geneList=NULL,single=0){
if(cov==0 & single==0){
  adapB_folder<-paste(out_dir_base,paste( "adapB_multi",sep=''),sep='/')
  dir.create(file.path(out_dir_base,paste( "adapB_multi",sep='')))
  adap_adap_folder<-paste(out_dir_base,paste( "adap_adap_multi",sep=''),sep='/')
  dir.create(file.path(out_dir_base,paste( "adap_adap_multi",sep='')))
  }

else if (cov==0 & single==1){
  adapB_folder<-paste(out_dir_base,paste( "adapB_single",sep=''),sep='/')
  dir.create(file.path(out_dir_base,paste( "adapB_single",sep='')))
  adap_adap_folder<-paste(out_dir_base,paste( "adap_adap_single",sep=''),sep='/')
  dir.create(file.path(out_dir_base,paste( "adap_adap_single",sep='')))
  }


if(is.null(geneList)){
  set.seed(1234)
  assign.wrapper(trainingData=trainingData, testData=testData, trainingLabel=trainingLabel1, geneList=NULL, n_sigGene=g, adaptive_B=T, adaptive_S=F, mixture_beta=F, outputDir=adapB_folder, theta0=0.05, theta1=0.9, iter=100000, burn_in=5000)  

  set.seed(1234)
  assign.wrapper(trainingData=trainingData, testData=testData, trainingLabel=trainingLabel1, geneList=NULL, n_sigGene=g, adaptive_B=T, adaptive_S=T, mixture_beta=F, outputDir=adap_adap_folder, theta0=0.05, theta1=0.9, iter=100000, burn_in=5000) 
}
else{
  set.seed(1234)
  assign.wrapper(trainingData=trainingData, testData=testData, trainingLabel=trainingLabel1, geneList=geneList, n_sigGene=g, adaptive_B=T, adaptive_S=F, mixture_beta=F, outputDir=adapB_folder, theta0=0.05, theta1=0.9, iter=100000, burn_in=5000)  

  set.seed(1234)
  assign.wrapper(trainingData=trainingData, testData=testData, trainingLabel=trainingLabel1, geneList=geneList, n_sigGene=g, adaptive_B=T, adaptive_S=T, mixture_beta=F, outputDir=adap_adap_folder, theta0=0.05, theta1=0.9, iter=100000, burn_in=5000) 


}
}

getGeneList = function(rDataPath) {
load(rDataPath)
output.data$processed.data$diffGeneList####for a gene list
output.data$processed.data$S_matrix##signature matrix with coefficients
}


writeFile = function(variable, filename) {
write.table(variable, filename ,sep='\t', col.names = NA,quote=F)
}


combineMultiplePredictionFiles= function(fileNames, outFileName)
for(i in 1:length(fileNames))
  {
   f<-read.csv(fileNames[i], header=1,row.names=1) ###reading in the filess one at a time
  colnames(f)<-paste(fileNames[i],colnames(f),sep='/')
  if(i==1){
    data<-f
    }
  else{
    data<-cbind(data,f)
    }
  write.table(data,outFileName ,sep='\t', col.names = NA,quote=F)
  }

#sum(!rownames(temp)%in%rownames(temp1))
