---
title: "multipathway_ASSIGN"
author: "Mumtahena Rahman"
date: "December 23, 2014"
output: pdf_document
---


```{r,echo=FALSE,cache=TRUE,include=FALSE}
library(sva)
library(ASSIGN)
merge_drop<-function(x,y,by=0)
{
  new_m<-merge(x,y,by=by)
  rownames(new_m)<-new_m$Row.names
  return(new_m[,2:length(colnames(new_m))])
}

pcaplot<-function(mat,sub){
  if(sum(sub)!=length(mat))
    {
    print("verify the subscripts...exiting now")
    }
  else{
    pca_mat <- prcomp(t(mat), center=T,scale=T)
    plot(pca_mat)
    plot(pca_mat$x[,1],pca_mat$x[,2])
    index= 1
    for(i in 1:length(sub))
      {
      #print(rownames(pca_mat$x)[index:sub[i]+index-1],"has color", )
      print(i)
      if(i==1)
        {
        points(pca_mat$x[1:sub[i]],pca_mat$x[1:sub[i],2],col=i+1)
        }
       else if(i==length(sub))
         {
         points(pca_mat$x[index:length(rownames(pca_mat$x))],pca_mat$x[index:length(rownames(pca_mat$x)),2],col=i+1)
         }
       else
        {
        points(pca_mat$x[index:index+sub[i]],pca_mat$x[index:index+sub[i],2],col=i+1)
        }
       index=index+sub[i]
      }
  }
}
assign_easy_multi<-function(trainingData=train, testData=test, trainingLabel1=NULL,g=100,out_dir_base="~/Desktop/tmp",cov=0){
if(cov==0){
  adap_folder<-paste(out_dir_base,paste( "adap_multi",sep=''),sep='/')
  dir.create(file.path(out_dir_base,paste( "adap_multi",sep='')))
  nonadap_folder<-paste(out_dir_base,paste( "nonadap_multi",sep=''),sep='/')
  dir.create(file.path(out_dir_base,paste( "nonadap_multi",sep='')))
  }
else{
  adap_folder<-paste(out_dir_base,paste( "adap_cov",sep=''),sep='/')
  dir.create(file.path(out_dir_base,paste( "adap_cov",sep='')))
  nonadap_folder<-paste(out_dir_base,paste( "nonadap_cov",sep=''),sep='/')
  dir.create(file.path(out_dir_base,paste( "nonadap_cov",sep='')))
}

set.seed(1234)
assign.wrapper(trainingData=trainingData, testData=testData, trainingLabel=trainingLabel1, testLabel=NULL, geneList=NULL, n_sigGene=g, adaptive_B=T, adaptive_S=F, mixture_beta=F, outputDir=adap_folder, theta0=0.05, theta1=0.9, iter=2000, burn_in=1000)  

set.seed(1234)
assign.wrapper(trainingData=trainingData, testData=testData, trainingLabel=trainingLabel1, testLabel=NULL, geneList=NULL, n_sigGene=g, adaptive_B=F, adaptive_S=F, mixture_beta=F, outputDir=nonadap_folder, theta0=0.05, theta1=0.9, iter=2000, burn_in=1000)  

}
```
Reading in the signature datasets...
```{r include=FALSE,echo=FALSE}
setwd("~/Dropbox/bild_signatures//Datasets/")
# multi<-read.table("hmec_multi_egfr_mek_FeatureCount.tpmlog", sep='\t', header=1, row.names=1)
# multi<-multi[,order(colnames(multi))]
# control_l<-multi[,1:6]
# egfr_l<-multi[,7:12]
# control_egfr_l<-cbind(control_l,egfr_l)
# 
 expr<-as.matrix(read.table("GFP18_AKT_BAD_HER2_IGF1R_RAF_ERK.tpmlog",sep='\t',row.names=1,header=1))
control<-subset(expr, select=GFP.1:GFP.12)
her2<-subset(expr, select=HER2.1:HER2.6)
akt<-subset(expr,select=AKT.1:AKT.6)
# bad<-subset(expr,select=BAD.1:BAD.6)
igf1r<-subset(expr,select=IGF1R.1:IGF1R.6)
# expr_all<-cbind(control,akt,bad,her2,igf1r)
expr_akt_her2_igf1r<-cbind(control,akt,her2,igf1r)
# 
# egfr_18hr_expr<-merge_drop(control_egfr_l,expr_all,by=0)
# dim(egfr_18hr_expr)
# egfr_18hr_expr_f <- egfr_18hr_expr[apply(egfr_18hr_expr[,1:47]==0,1,mean) < 0.8,]
# dim(egfr_18hr_expr_f)
# 
# expr_all_f <-expr_all[apply(expr_all[,1:35]==0,1,mean) < 0.8,]
# dim(expr_all_f)
expr_akt_her2_igf1r_f <-expr_akt_her2_igf1r[apply(expr_akt_her2_igf1r[,1:29]==0,1,mean) < 0.8,]
dim(expr_akt_her2_igf1r_f)
icbp<-as.matrix(read.table("~/Dropbox/ICBP/icbp_Rsubread_tpmlog.txt", sep='\t', stringsAsFactors=FALSE, header=1, row.names=1))
# egfr_18hr_expr_icbp_f<-merge_drop(egfr_18hr_expr_f,icbp,by=0)
# expr_all_icbp_f<-merge_drop(expr_all_f,icbp,by=0)
expr_akt_her2_igf1r_icbp_f<-merge_drop(expr_akt_her2_igf1r_f,icbp,by=0)
sub_ahi<-c(12,6,5,6,55)
# pcaplot(mat = expr_akt_her2_igf1r_icbp_f,sub = sub_ahi)
# bat3<-as.matrix(cbind(c(colnames(expr_akt_her2_igf1r_f),colnames(icbp)),c(rep(1,length(colnames(expr_akt_her2_igf1r_f))),rep(2,length(colnames(icbp))))))
# bat3
# 
# combat_expr3<-ComBat(dat=expr_akt_her2_igf1r_icbp_f, batch=bat3[,2], mod=NULL, numCovs=NULL)
# pcaplot(combat_expr3,sub_ahi)

# 
# sub<-c(6,6,12,6,6,5,6,55)
# sub_e<-c(12,6,6,5,6,55)
# pcaplot(mat = egfr_18hr_expr_icbp_f,sub = sub)
# pcaplot(mat = expr_all_icbp_f,sub = sub_e)
# 
# bat1<-as.matrix(cbind(c(colnames(egfr_18hr_expr_f),colnames(icbp)),c(rep(1,length(colnames(control_egfr_l))),rep(2,length(colnames(expr_all))),rep(3,length(colnames(icbp))))))
# bat1
# bat2<-as.matrix(cbind(c(colnames(expr_all_f),colnames(icbp)),c(rep(1,length(colnames(expr_all_f))),rep(2,length(colnames(icbp))))))
# bat2
# combat_expr1<-ComBat(dat=egfr_18hr_expr_icbp_f, batch=bat1[,2], mod=NULL, numCovs=NULL)
# pcaplot(combat_expr1,sub)
# combat_expr2<-ComBat(dat=expr_all_icbp_f, batch=bat2[,2], mod=NULL, numCovs=NULL)
# pcaplot(combat_expr2,sub_e)
# 
# 
# train<-combat_expr1[,1:47]
# test<-combat_expr1[,48:102]
# 
# trainingLabel1<-list(control=list(egfr=1:6,akt=13:24,bad=13:24,her2=13:24,igf1r=13:24), egfr=7:12,akt=25:30, bad=31:36,her2=37:41,igf1r=42:47)
# #dir.create( "~/Desktop/tmp/multi_icbp")
# 
# #assign_easy_multi(trainingData = train,test=test,trainingLabel1 = trainingLabel1,g=c(15,150,150,15,100),out_dir_base = "~/Desktop/tmp/multi_icbp")
# 
# train1<-combat_expr2[,1:35]
# test1<-combat_expr2[,36:90]
# 
# trainingLabel2<-list(control=list(akt=1:12,bad=1:12,her2=1:12,igf1r=1:12),akt=13:18, bad=19:24,her2=25:29,igf1r=30:35)
# #dir.create( "~/Desktop/tmp/multi_icbp_expr")
# 
# #assign_easy_multi(trainingData = train1,test=test1,trainingLabel1 = trainingLabel2,g=c(150,150,15,100),out_dir_base = "~/Desktop/tmp/multi_icbp_expr")

# train2<-combat_expr3[,1:29]
# test2<-combat_expr3[,36:84]
# # 
# trainingLabel3<-list(control=list(akt=1:12,her2=1:12,igf1r=1:12),akt=13:18,her2=19:23,igf1r=24:29)
# 
# dir.create( "~/Desktop/tmp/multi_icbp_akt_her2_igf1r")
# # 
# assign_easy_multi(trainingData = train2,test=test2,trainingLabel1 = trainingLabel3,g=c(150,15,100),out_dir_base = "~/Desktop/tmp/multi_icbp_akt_her2_igf1r/")
```
Checking for correlation..

```{r include=FALSE}
data1<-read.csv("~/Desktop/tmp/multi_icbp/adap_multi/pathway_activity_testset.csv", row.names=1,header=1)
data2<-read.csv("~/Desktop/tmp/multi_icbp/nonadap_multi/pathway_activity_testset.csv",row.names=1,header=1)

data3<-read.csv("~/Desktop/tmp/multi_icbp_expr/adap_multi/pathway_activity_testset.csv", row.names=1,header=1)
data4<-read.csv("~/Desktop/tmp/multi_icbp_expr/nonadap_multi/pathway_activity_testset.csv",row.names=1,header=1)

data5<-read.csv("~/Desktop/tmp/multi_icbp_akt_her2_igf1r/adap_multi/pathway_activity_testset.csv", row.names=1,header=1)
data6<-read.csv("~/Desktop/tmp/multi_icbp_akt_her2_igf1r/nonadap_multi/pathway_activity_testset.csv",row.names=1,header=1)
```

Now correlating multi pathway predictions with ICBP drugs..
```{r, cache=TRUE,include=FALSE,echo=FALSE}
drugs<-read.delim("~/Dropbox/bild_signatures//Datasets/ICBP_drugs.txt", header=1, sep='\t',row.names=1)
pred_drug<-merge_drop(data1,drugs,by=0)
#dim(pred_drug)
print("for EGFR, AKT, BAD, HER2, IGF1R multipathway signatures")
for(i in 1:length(colnames(data1)))
  {
  print(colnames(data1)[i])
  print("correlation with  Gefitinib..an EGFR inhibitor")
  print(cor(pred_drug[,i],pred_drug$Gefitinib,use="na.or.complete"))
  print("correlation with  Erlotinib..an EGFR inhibitor")
  print(cor(pred_drug[,i],pred_drug$Erlotinib,use="na.or.complete"))
  print("correlation with  BIBW2992...an EGFR inhibitor")
  print(cor(pred_drug[,i],pred_drug$BIBW2992,use="na.or.complete"))
  print("correlation with  AG1478..an EGFR inhibitor")
  print(cor(pred_drug[,i],pred_drug$AG1478,use="na.or.complete"))
  print("correlation with Lapatinib..an EGFR/HER2 inhibitor")
  print(cor(pred_drug[i],pred_drug$Lapatinib,use="na.or.complete"))
  print("correlation with BEZ235..a pi3k/mtor inhibitor")
  print(cor(pred_drug[i],pred_drug$BEZ235,use="na.or.complete"))
  print("correlation with Everolimus..an mtor inhibitor")
  print(cor(pred_drug[i],pred_drug$Everolimus,use="na.or.complete"))
  print("correlation with Temsirolimus..an mtor inhibitor")
  print(cor(pred_drug[i],pred_drug$Temsirolimus,use="na.or.complete"))
  print("correlation with Sigma AKT1/2..an AKT  inhibitor")
  print(cor(pred_drug[i],pred_drug$Sigma.AKT1.2.inhibitor,use="na.or.complete"))
  print("correlation with GSK2126458..an AKT  inhibitor")
  print(cor(pred_drug[i],pred_drug$GSK2126458,use="na.or.complete"))
  print("correlation with TRIciribine..an AKT  inhibitor")
  print(cor(pred_drug[i],pred_drug$Triciribine,use="na.or.complete"))
  print("correlation with Tykerb.IGF1R..1.1...EGFR/HER2/IGF1R inhibitor")
  print(cor(pred_drug[i],pred_drug$Tykerb.IGF1R..1.1.,use="na.or.complete"))
  print("correlation with GSK1838705...an IGF1R inhibitor")
  print(cor(pred_drug[i],pred_drug$GSK1838705, use = "na.or.complete"))
#   
  }
```

Batch adjustment likely works better in this case without the EGFR signature....
```{r include=FALSE,echo=FALSE}
print("for AKT, BAD, HER2, IGF1R multipathway signatures")
pred_drug<-merge_drop(data3,drugs,by=0)
#dim(pred_drug)
for(i in 1:length(colnames(data3)))
  {
  print(colnames(data3)[i])
  print("correlation with  Gefitinib..an EGFR inhibitor")
  print(cor(pred_drug[,i],pred_drug$Gefitinib,use="na.or.complete"))
  print("correlation with  Erlotinib..an EGFR inhibitor")
  print(cor(pred_drug[,i],pred_drug$Erlotinib,use="na.or.complete"))
  print("correlation with  BIBW2992...an EGFR inhibitor")
  print(cor(pred_drug[,i],pred_drug$BIBW2992,use="na.or.complete"))
  print("correlation with  AG1478..an EGFR inhibitor")
  print(cor(pred_drug[,i],pred_drug$AG1478,use="na.or.complete"))
  print("correlation with Lapatinib..an EGFR/HER2 inhibitor")
  print(cor(pred_drug[i],pred_drug$Lapatinib,use="na.or.complete"))
  print("correlation with BEZ235..a pi3k/mtor inhibitor")
  print(cor(pred_drug[i],pred_drug$BEZ235,use="na.or.complete"))
  print("correlation with Everolimus..an mtor inhibitor")
  print(cor(pred_drug[i],pred_drug$Everolimus,use="na.or.complete"))
  print("correlation with Temsirolimus..an mtor inhibitor")
  print(cor(pred_drug[i],pred_drug$Temsirolimus,use="na.or.complete"))
  print("correlation with Sigma AKT1/2..an AKT  inhibitor")
  print(cor(pred_drug[i],pred_drug$Sigma.AKT1.2.inhibitor,use="na.or.complete"))
  print("correlation with GSK2126458..an AKT  inhibitor")
  print(cor(pred_drug[i],pred_drug$GSK2126458,use="na.or.complete"))
  print("correlation with TRIciribine..an AKT  inhibitor")
  print(cor(pred_drug[i],pred_drug$Triciribine,use="na.or.complete"))
  print("correlation with Tykerb.IGF1R..1.1...EGFR/HER2/IGF1R inhibitor")
  print(cor(pred_drug[i],pred_drug$Tykerb.IGF1R..1.1.,use="na.or.complete"))
  print("correlation with GSK1838705...an IGF1R inhibitor")
  print(cor(pred_drug[i],pred_drug$GSK1838705, use = "na.or.complete"))
#   
  }
```

Now including only AKT, HER2 and IGF1R signatures
```{r include=FALSE,echo=FALSE}
print("for AKT, HER2, IGF1R multipathway signatures")
pred_drug<-merge_drop(data5,drugs,by=0)
#dim(pred_drug)
for(i in 1:length(colnames(data5)))
  {
  print(colnames(data5)[i])
  print("correlation with  Gefitinib..an EGFR inhibitor")
  print(cor(pred_drug[,i],pred_drug$Gefitinib,use="na.or.complete"))
  print("correlation with  Erlotinib..an EGFR inhibitor")
  print(cor(pred_drug[,i],pred_drug$Erlotinib,use="na.or.complete"))
  print("correlation with  BIBW2992...an EGFR inhibitor")
  print(cor(pred_drug[,i],pred_drug$BIBW2992,use="na.or.complete"))
  print("correlation with  AG1478..an EGFR inhibitor")
  print(cor(pred_drug[,i],pred_drug$AG1478,use="na.or.complete"))
  print("correlation with Lapatinib..an EGFR/HER2 inhibitor")
  print(cor(pred_drug[i],pred_drug$Lapatinib,use="na.or.complete"))
  print("correlation with BEZ235..a pi3k/mtor inhibitor")
  print(cor(pred_drug[i],pred_drug$BEZ235,use="na.or.complete"))
  print("correlation with Everolimus..an mtor inhibitor")
  print(cor(pred_drug[i],pred_drug$Everolimus,use="na.or.complete"))
  print("correlation with Temsirolimus..an mtor inhibitor")
  print(cor(pred_drug[i],pred_drug$Temsirolimus,use="na.or.complete"))
  print("correlation with Sigma AKT1/2..an AKT  inhibitor")
  print(cor(pred_drug[i],pred_drug$Sigma.AKT1.2.inhibitor,use="na.or.complete"))
  print("correlation with GSK2126458..an AKT  inhibitor")
  print(cor(pred_drug[i],pred_drug$GSK2126458,use="na.or.complete"))
  print("correlation with TRIciribine..an AKT  inhibitor")
  print(cor(pred_drug[i],pred_drug$Triciribine,use="na.or.complete"))
  print("correlation with Tykerb.IGF1R..1.1...EGFR/HER2/IGF1R inhibitor")
  print(cor(pred_drug[i],pred_drug$Tykerb.IGF1R..1.1.,use="na.or.complete"))
  print("correlation with GSK1838705...an IGF1R inhibitor")
  print(cor(pred_drug[i],pred_drug$GSK1838705, use = "na.or.complete"))
#   
  }
```

Creating heatmaps
```{r }
multi<-read.csv("~/Desktop/tmp/multi_icbp_expr/adap_multi/pathway_activity_testset.csv", row.names=1,header=1)
single<-read.csv("~/Desktop/tmp/single_pathway_results.csv", row.names=1,header=1)
comb<-cbind(multi,single)
dim(comb)
library(gplots)
heatmap.2(as.matrix(comb[,1:4]),col=bluered,lmat=rbind( c(0, 3, 4), c(2,1,0 ) ), lwid=c(1.5, 4, 2 ), trace="none",main="Multi- pathway activity", ylab="ICBP Cell lines")
heatmap.2(as.matrix(comb[,5:8]),col=bluered,lmat=rbind( c(0, 3, 4), c(2,1,0 ) ), lwid=c(1.5, 4, 2 ), trace="none",main="Single pathway activity", ylab="ICBP Cell lines")
comb_drug<-merge_drop(comb,drugs,by=0)
plot(hclust(dist(comb_drug[,1:8]), method = "complete", members = NULL))

basal<-subset(comb_drug[,1:8],comb_drug$Transcriptional.subtype...ERBB2.status=="Basal")
heatmap.2(as.matrix(basal),col=bluered,lmat=rbind( c(0, 3, 4), c(2,1,0 ) ), lwid=c(1.5, 4, 2 ), trace="none",main="Basal subtype",scale="row")
her<-subset(comb_drug[,1:8],comb_drug$Transcriptional.subtype...ERBB2.status=="ERBB2-amp"|comb_drug$Transcriptional.subtype...ERBB2.status=="ERBB2Amp")
heatmap.2(as.matrix(basal),col=bluered,lmat=rbind( c(0, 3, 4), c(2,1,0 ) ), lwid=c(1.5, 4, 2 ), trace="none",main="HER2 amplified",scale="row")
claudin<-subset(comb_drug[,1:8],comb_drug$Transcriptional.subtype...ERBB2.status=="Claudin-low")
heatmap.2(as.matrix(claudin),col=bluered,lmat=rbind( c(0, 3, 4), c(2,1,0 ) ), lwid=c(1.5, 4, 2 ), trace="none",main="Claudin low",scale="row")
luminal<-subset(comb_drug[,1:4],comb_drug$Transcriptional.subtype...ERBB2.status=="Luminal")
heatmap.2(as.matrix(luminal),col=bluered,lmat=rbind( c(0, 3, 4), c(2,1,0 ) ), lwid=c(1.5, 4, 2 ), trace="none",main="Claudin low",scale="row")

```

```{r echo=FALSE}
time<-format(Sys.time(),"%a %b %d %X %Y")
```
This analysis was run on `r time` 
