---
title: "multipathway_ASSIGN"
author: "Mumtahena Rahman"
date: "December 23, 2014"
output: pdf_document
---


```{r,echo=FALSE,cache=TRUE,include=FALSE}
library(sva)
library(ASSIGN)
merge_drop<-function(x,y,by=0)
{
  new_m<-merge(x,y,by=by)
  rownames(new_m)<-new_m$Row.names
  return(new_m[,2:length(colnames(new_m))])
}

pcaplot<-function(mat,sub){
  if(sum(sub)!=length(mat))
    {
    print("verify the subscripts...exiting now")
    }
  else{
    pca_mat <- prcomp(t(mat), center=T,scale=T)
    plot(pca_mat)
    plot(pca_mat$x[,1],pca_mat$x[,2])
    for(i in 1:length(sub))
      {
      #print(rownames(pca_mat$x)[index:sub[i]+index-1],"has color", )
      print(i)
      if(i==1)
        {
        points(pca_mat$x[1:sub[i]],pca_mat$x[1:sub[i],2],col=i)
        }
      else if(i==length(sub))
         {
         points(pca_mat$x[sum(sub[1:i-1]):length(rownames(pca_mat$x))],pca_mat$x[sum(sub[1:i-1]):length(rownames(pca_mat$x)),2],col=i)
        }
       else
        {
          
        points(pca_mat$x[sum(sub[1:i-1]):sum(sub[1:i])],pca_mat$x[sum(sub[1:i-1]):sum(sub[1:i]),2],col=i)
        }
      }
  }
}

assign_easy_multi<-function(trainingData=train, testData=test, trainingLabel1=NULL,g=100,out_dir_base="~/Desktop/tmp",cov=0){
if(cov==0){
  adap_folder<-paste(out_dir_base,paste( "adap_multi",sep=''),sep='/')
  dir.create(file.path(out_dir_base,paste( "adap_multi",sep='')))
  nonadap_folder<-paste(out_dir_base,paste( "nonadap_multi",sep=''),sep='/')
  dir.create(file.path(out_dir_base,paste( "nonadap_multi",sep='')))
  }
else{
  adap_folder<-paste(out_dir_base,paste( "adap_cov",sep=''),sep='/')
  dir.create(file.path(out_dir_base,paste( "adap_cov",sep='')))
  nonadap_folder<-paste(out_dir_base,paste( "nonadap_cov",sep=''),sep='/')
  dir.create(file.path(out_dir_base,paste( "nonadap_cov",sep='')))
}

set.seed(1234)
assign.wrapper(trainingData=trainingData, testData=testData, trainingLabel=trainingLabel1, testLabel=NULL, geneList=NULL, n_sigGene=g, adaptive_B=T, adaptive_S=F, mixture_beta=F, outputDir=adap_folder, theta0=0.05, theta1=0.9, iter=10000, burn_in=1000)  

set.seed(1234)
assign.wrapper(trainingData=trainingData, testData=testData, trainingLabel=trainingLabel1, testLabel=NULL, geneList=NULL, n_sigGene=g, adaptive_B=F, adaptive_S=F, mixture_beta=F, outputDir=nonadap_folder, theta0=0.05, theta1=0.9, iter=10000, burn_in=1000)  

}
# training_label_generation<-function(items,sub,label){
#   print(dim(items))
#   print(sub)
#   print(label)
#   {
#     traininglabel=list(control=list(for(i in 2:length(sub)){label[i]=1:sub[i]}),)
#     trainingLabel1<-list(control=list(egfr=1:6,akt=13:24,bad=13:24,her2=13:24,igf1r=13:24), egfr=7:12,akt=25:30, bad=31:36,her2=37:41,igf1r=42:47)
#   }
#   
# }
```
Reading in the signature datasets...
```{r include=FALSE,echo=FALSE}
setwd("~/Dropbox/bild_signatures/Datasets/")
expr<-as.matrix(read.table("GFP18_AKT_BAD_HER2_IGF1R_RAF_ERK.tpmlog",sep='\t',row.names=1,header=1))
control<-subset(expr, select=GFP.1:GFP.12)
her2<-subset(expr, select=HER2.1:HER2.6)
akt<-subset(expr,select=AKT.1:AKT.6)
bad<-subset(expr,select=BAD.1:BAD.6)
igf1r<-subset(expr,select=IGF1R.1:IGF1R.6)
expr_all<-cbind(control,akt,bad,her2,igf1r)
icbp<-as.matrix(read.table("~/Dropbox/ICBP/icbp_Rsubread_tpmlog.txt", sep='\t', stringsAsFactors=FALSE, header=1, row.names=1))
expr_all_f <-expr_all[apply(expr_all[,1:35]==0,1,mean) < 0.85,]
dim(expr_all_f)
expr_all_icbp_f<-merge_drop(expr_all_f,icbp,by=0)
sub<-c(12,6,6,5,6,55)
pcaplot(expr_all_icbp_f,sub)
bat1<-as.matrix(cbind(c(colnames(expr_all_f),colnames(icbp)),c(rep(1,length(colnames(expr_all_f))),rep(2,length(colnames(icbp))))))
#bat1
combat_expr1<-ComBat(dat=expr_all_icbp_f, batch=bat1[,2], mod=NULL, numCovs=NULL)
pcaplot(combat_expr1,sub)
c_gfp<-subset(combat_expr1, select=GFP.1:GFP.12)
c_akt<-subset(combat_expr1, select=AKT.1:AKT.6)
c_bad<-subset(combat_expr1, select=BAD.1:BAD.6)
c_her2<-subset(combat_expr1, select=HER2.1:HER2.6)
c_igf1r<-subset(combat_expr1, select=IGF1R.1:IGF1R.6)

#############trying two pathways at a time in multipathway#############
#1. HER2 & AKT
trainha<-cbind(c_gfp,c_akt,c_her2)
testha<-combat_expr1[,36:90]
trainingLabelha<-list(control=list(akt=1:12,her2=1:12),akt=13:18,her2=19:23)
dir.create( "~/Desktop/tmp/multi_icbp_expr_pc/Her2_AKT")
# 
assign_easy_multi(trainingData = trainha,test=testha,trainingLabel1 = trainingLabelha,g=c(150,15),out_dir_base = "~/Desktop/tmp/multi_icbp_expr_pc/Her2_AKT/")

#2. HER2 & BAD

trainhb<-cbind(c_gfp,c_bad,c_her2)
testhb<-combat_expr1[,36:90]
trainingLabelhb<-list(control=list(bad=1:12,her2=1:12),bad=13:18,her2=19:23)
dir.create( "~/Desktop/tmp/multi_icbp_expr_pc/Her2_BAD")
# 
assign_easy_multi(trainingData = trainhb,test=testhb,trainingLabel1 = trainingLabelhb,g=c(150,15),out_dir_base = "~/Desktop/tmp/multi_icbp_expr_pc/Her2_BAD/")

#3. HER2 & IGF1R
trainhi<-cbind(c_gfp,c_igf1r,c_her2)
testhi<-combat_expr1[,36:90]
trainingLabelhi<-list(control=list(igf1r=1:12,her2=1:12),igf1r=13:18,her2=19:23)
dir.create( "~/Desktop/tmp/multi_icbp_expr_pc/Her2_IGF1R")
# 
assign_easy_multi(trainingData = trainhi,test=testhi,trainingLabel1 = trainingLabelhi,g=c(100,15),out_dir_base = "~/Desktop/tmp/multi_icbp_expr_pc/Her2_IGF1R/")

#4. AKT & BAD
trainab<-cbind(c_gfp,c_akt,c_bad)
testab<-combat_expr1[,36:90]
trainingLabelab<-list(control=list(akt=1:12,bad=1:12),akt=13:18,bad=19:24)
dir.create( "~/Desktop/tmp/multi_icbp_expr_pc/AKT_BAD")
# 
assign_easy_multi(trainingData = trainab,test=testab,trainingLabel1 = trainingLabelab,g=c(150,150),out_dir_base = "~/Desktop/tmp/multi_icbp_expr_pc/AKT_BAD/")

#5. AKT & IGF1R
trainai<-cbind(c_gfp,c_akt,c_igf1r)
testai<-combat_expr1[,36:90]
trainingLabelai<-list(control=list(akt=1:12,igf1r=1:12),akt=13:18,igf1r=19:24)
dir.create( "~/Desktop/tmp/multi_icbp_expr_pc/AKT_IGF1R")
# 
assign_easy_multi(trainingData = trainai,test=testai,trainingLabel1 = trainingLabelai,g=c(150,100),out_dir_base = "~/Desktop/tmp/multi_icbp_expr_pc/AKT_IGF1R")

#6. BAD & IGF1R
trainbi<-cbind(c_gfp,c_bad,c_igf1r)
testbi<-combat_expr1[,36:90]
trainingLabelbi<-list(control=list(bad=1:12,igf1r=1:12),bad=13:18,igf1r=19:24)
dir.create( "~/Desktop/tmp/multi_icbp_expr_pc/BAD_IGF1R")
# 
assign_easy_multi(trainingData = trainbi,test=testbi,trainingLabel1 = trainingLabelbi,g=c(150,100),out_dir_base = "~/Desktop/tmp/multi_icbp_expr_pc/BAD_IGF1R")

#############trying three pathways at a time in multipathway#############
#1. HER2, AKT & BAD
trainhab<-cbind(c_gfp,c_akt,c_bad,c_her2)
testhab<-combat_expr1[,36:90]
trainingLabelhab<-list(control=list(akt=1:12,bad=1:12,her2=1:12),akt=13:18,bad=19:24,her2=25:29)
dir.create( "~/Desktop/tmp/multi_icbp_expr_pc/AKT_BAD_HER2")
# 
assign_easy_multi(trainingData = trainhab,test=testhab,trainingLabel1 = trainingLabelhab,g=c(150,150,15),out_dir_base = "~/Desktop/tmp/multi_icbp_expr_pc/AKT_BAD_HER2")

#2. HER2, BAD & IGF1R
trainhbi<-cbind(c_gfp,c_igf1r,c_bad,c_her2)
testhbi<-combat_expr1[,36:90]
trainingLabelhbi<-list(control=list(igf1r=1:12,bad=1:12,her2=1:12),igf1r=13:18,bad=19:24,her2=25:29)
dir.create( "~/Desktop/tmp/multi_icbp_expr_pc/IGF1R_BAD_HER2")
# 
assign_easy_multi(trainingData = trainhbi,test=testhbi,trainingLabel1 = trainingLabelhbi,g=c(100,150,15),out_dir_base = "~/Desktop/tmp/multi_icbp_expr_pc/IGF1R_BAD_HER2")

#3. AKT, BAD & IGF1R
trainabi<-cbind(c_gfp,c_akt,c_bad,c_igf1r)
testabi<-combat_expr1[,36:90]
trainingLabelabi<-list(control=list(akt=1:12,bad=1:12,igf1r=1:12),akt=13:18,bad=19:24,igf1r=25:30)
dir.create( "~/Desktop/tmp/multi_icbp_expr_pc/AKT_BAD_IGF1R")
# 
assign_easy_multi(trainingData = trainhabi,test=testabi,trainingLabel1 = trainingLabelabi,g=c(150,150,100),out_dir_base = "~/Desktop/tmp/multi_icbp_expr_pc/AKT_BAD_IGF1R")

########################trying all four at once#####################
trainhall<-cbind(c_gfp,c_akt,c_bad,c_her2,c_igf1r)
testall<-combat_expr1[,36:90]
trainingLabel<-list(control=list(akt=1:12,bad=1:12,her2=1:12,igf1r=1:12),akt=13:18, bad=19:24,her2=25:29,igf1r=30:35)
dir.create( "~/Desktop/tmp/multi_icbp_expr_pc/all_4")
# 
assign_easy_multi(trainingData = trainhall,test=testall,trainingLabel1 = trainingLabel,g=c(150,150,15,100),out_dir_base = "~/Desktop/tmp/multi_icbp_expr_pc/all_4")

```
Checking for correlation..

```{r include=FALSE}
setwd("~/Dropbox/bild_signatures/multi_icbp_expr_pc/")
filenames<-system("ls */adap*/pathway_activity_testset*", intern=TRUE)
filenames

for(i in 1:length(filenames))
  {
   f<-read.csv(filenames[i], header=1,row.names=1) ###reading in the filess one at a time
  colnames(f)<-paste(filenames[i],colnames(f),sep='/')
  if(i==1){
    data<-f
    }
  else{
    data<-cbind(data,f)
    }
  }
#write.table(data,"~/Desktop/multipathway_preds.txt",sep='\t', col.names = NA,quote=F)
```

Now correlating multi pathway predictions with ICBP drugs..
```{r, cache=TRUE,include=FALSE,echo=FALSE}
#drugs<-read.delim("~/Dropbox/bild_signatures/Datasets/ICBP_drugs.txt", header=1, sep='\t',row.names=1)
drugs<-read.delim("~/Documents/ThesisWork/GitRepos/u01project/SignatureValidations/EGFR/ICBP/ICBP_drugs.txt", header=1, sep='\t',row.names=1)
data<-read.delim("~/Documents/ThesisWork/GitRepos/bild_signatures/Results/predictions//multipathway_preds.txt", header=1, sep='\t',row.names=1) 
data_trans=t(data)
write.table(data_trans,"~/Desktop/multipathway_preds_trans.txt",sep='\t', col.names = NA,quote=F)
data_single=read.csv("~/Documents/ThesisWork/GitRepos/bild_signatures/Results/predictions/single_pathway_results.csv") 


#AKT
cor(data$AKT_BAD.adap_multi.pathway_activity_testset.csv.akt, data$AKT_IGF1R.adap_multi.pathway_activity_testset.csv.akt, use="na.or.complete" )
cor(data$AKT_BAD.adap_multi.pathway_activity_testset.csv.akt, data$Her2_AKT.adap_multi.pathway_activity_testset.csv.akt, ,use="na.or.complete" )
cor(data$AKT_BAD.adap_multi.pathway_activity_testset.csv.akt, data$AKT_BAD_HER2.adap_multi.pathway_activity_testset.csv.akt, use="na.or.complete" )
cor(data$AKT_BAD.adap_multi.pathway_activity_testset.csv.akt, data$AKT_BAD_IGF1R.adap_multi.pathway_activity_testset.csv.akt, use="na.or.complete" )
cor(data$AKT_BAD.adap_multi.pathway_activity_testset.csv.akt, data$all_4.adap_multi.pathway_activity_testset.csv.akt, use="na.or.complete" )
cor(data$Her2_AKT.adap_multi.pathway_activity_testset.csv.akt, data$AKT_BAD_IGF1R.adap_multi.pathway_activity_testset.csv.akt,use="na.or.complete" )
cor(data$Her2_AKT.adap_multi.pathway_activity_testset.csv.akt,data$AKT_BAD_HER2.adap_multi.pathway_activity_testset.csv.akt,use="na.or.complete")
cor(data$Her2_AKT.adap_multi.pathway_activity_testset.csv.akt, data$AKT_BAD_IGF1R.adap_multi.pathway_activity_testset.csv.akt, use="na.or.complete" )
cor(data$Her2_AKT.adap_multi.pathway_activity_testset.csv.akt, data$all_4.adap_multi.pathway_activity_testset.csv.akt, use="na.or.complete" )
cor(data$AKT_IGF1R.adap_multi.pathway_activity_testset.csv.akt, data$AKT_BAD_HER2.adap_multi.pathway_activity_testset.csv.akt, use="na.or.complete" )
cor(data$AKT_IGF1R.adap_multi.pathway_activity_testset.csv.akt, data$AKT_BAD_IGF1R.adap_multi.pathway_activity_testset.csv.akt, use="na.or.complete" )
cor(data$AKT_IGF1R.adap_multi.pathway_activity_testset.csv.akt, data$all_4.adap_multi.pathway_activity_testset.csv.akt, use="na.or.complete" )
cor(data$AKT_BAD_HER2.adap_multi.pathway_activity_testset.csv.akt, data$AKT_BAD_IGF1R.adap_multi.pathway_activity_testset.csv.akt, use="na.or.complete" )
cor(data$AKT_BAD_HER2.adap_multi.pathway_activity_testset.csv.akt, data$all_4.adap_multi.pathway_activity_testset.csv.akt, use="na.or.complete" )
cor(data$AKT_BAD_IGF1R.adap_multi.pathway_activity_testset.csv.akt, data$all_4.adap_multi.pathway_activity_testset.csv.akt, use="na.or.complete" )

#BAD

#HER2
cor(data$AKT_BAD_HER2.adap_multi.pathway_activity_testset.csv.her2, data$Her2_AKT.adap_multi.pathway_activity_testset.csv.her2, use="na.or.complete" )
cor(data$AKT_BAD_HER2.adap_multi.pathway_activity_testset.csv.her2, data$Her2_BAD.adap_multi.pathway_activity_testset.csv.her2, use="na.or.complete" )
cor(data$Her2_AKT.adap_multi.pathway_activity_testset.csv.her2, data$Her2_BAD.adap_multi.pathway_activity_testset.csv.her2, use="na.or.complete" )


#IGFR
cor(data$AKT_BAD_IGF1R.adap_multi.pathway_activity_testset.csv.igf1r, data$AKT_IGF1R.adap_multi.pathway_activity_testset.csv.igf1r, use="na.or.complete" )
cor(data$AKT_BAD_IGF1R.adap_multi.pathway_activity_testset.csv.igf1r, data$BAD_IGF1R.adap_multi.pathway_activity_testset.csv.igf1r, use="na.or.complete" )
cor(data$BAD_IGF1R.adap_multi.pathway_activity_testset.csv.igf1r, data$AKT_IGF1R.adap_multi.pathway_activity_testset.csv.igf1r, use="na.or.complete" )



# multi all four
cor(data$all_4.adap_multi.pathway_activity_testset.csv.akt, data$all_4.adap_multi.pathway_activity_testset.csv.igf1r,use="na.or.complete") # 0.1874326
cor(data$all_4.adap_multi.pathway_activity_testset.csv.akt, data$all_4.adap_multi.pathway_activity_testset.csv.bad,use="na.or.complete") # -0.4327576
cor(data$all_4.adap_multi.pathway_activity_testset.csv.akt, data$all_4.adap_multi.pathway_activity_testset.csv.her2,use="na.or.complete") # 0.26
cor(data$all_4.adap_multi.pathway_activity_testset.csv.her2, data$all_4.adap_multi.pathway_activity_testset.csv.igf1r,use="na.or.complete") #-0.41
cor(data$all_4.adap_multi.pathway_activity_testset.csv.her2, data$all_4.adap_multi.pathway_activity_testset.csv.bad,use="na.or.complete") #-0.34
cor(data$all_4.adap_multi.pathway_activity_testset.csv.bad, data$all_4.adap_multi.pathway_activity_testset.csv.igf1r,use="na.or.complete") #-0.46


cor(data_single$akt_s_a, data_single$igf1r_s_a, use="na.or.complete") #0.01
cor(data_single$akt_s_a, data_single$bad_s_a, use="na.or.complete") #0.45 #AKT and BAD correlated
cor(data_single$igf1r_s_a, data_single$bad_s_a, use="na.or.complete") #-0.51 #IGFR and BAD neg correlation
cor(data_single$igf1r_s_a, data_single$her2_s_a, use="na.or.complete") #0.01 
cor(data_single$akt_s_a, data_single$her2_s_a, use="na.or.complete") #0.33  AKT and Her2 predictions corelated
cor(data_single$bad, data_single$her2_s_a, use="na.or.complete") #0.03

#do it for all of them (Shelley will do this)


View(data_single)
row.names(data_single)=data_single[,1]
View(data_single)
data_single=data_single[,-1]
View(data_single)
# mk2206<-read.table("~/Desktop/Drug reponse analysis/bildlab_drug response/mk2206.txt",sep='\t',row.names=1,header=1)
# mk2206

View(data)
View(drugs)
pred_drug<-merge_drop(data,drugs,by=0)
View(pred_drug)
=======
data_all<-cbind(data,single)
pred_drug<-merge_drop(data_all,drugs,by=0)
drug_srt<-subset(drugs,select = c("Lapatinib","Sigma.AKT1.2.inhibitor","Temsirolimus","Everolimus"))
pred_drug<-merge_drop(data_all,drug_srt,by=0)

# mk2206<-subset(mk2206,select="Sensitivity..logEC50")
# pred_drug<-merge_drop(pred_drug,mk2206,by=0)
#dim(pred_drug)
View(pred_drug)
dim(pred_drug)


pred_drug_multi<-merge_drop(data,drugs,by=0)
pred_drug_single<-merge_drop(data_single,drugs,by=0)

drug_prediction_correlations_multi= cor(pred_drug_multi[1:25],pred_drug_multi[36:125],use="na.or.complete")
View(pred_drug_multi)
View(pred_drug_single)
ncol(pred_drug_single)
pred_drug_single[15]
drug_prediction_correlations_single= cor(pred_drug_single[1:4],pred_drug_single[15:104],use="na.or.complete")
colnames(pred_drug)<-gsub(pattern = "pathway_activity_testset.csv",replacement = "",x = colnames(pred_drug))
head(pred_drug)


cors = matrix(0,54,4)
rownames(cors)=colnames(pred_drug)[1:54]
colnames(cors)=c("Lapatinib","Sigma.akt.1.2.inhibitor","Temsirolimus","Everolimus")
pathways<-pred_drug[,1:54]
drugs<-pred_drug[,55:58]

for (i in 1:length(colnames(data))){
  for (j in 1:length(colnames(drug_srt))){
    cors[i,j]=cor(pathways[,i],drugs[,j],use="pairwise.complete.obs")
  }
}


View(drug_pre_diction_correlations_multi)
View(drug_prediction_correlations_single)



single_and_multi= rbind(drug_prediction_correlations_multi,drug_prediction_correlations_single)
plot(single_and_multi[2])
View(single_and_multi)

row.names(single_and_multi)

# for sinlge
cor(single_and_multi[26,], single_and_multi[27,] ) # 0.5269367
cor(single_and_multi[26,], single_and_multi[28,] ) #0.7882588
cor(single_and_multi[26,], single_and_multi[29,] ) # 0.6173746
cor(single_and_multi[27,], single_and_multi[28,] ) # 0.2896494
cor(single_and_multi[27,], single_and_multi[29,] ) # -0.02523773
cor(single_and_multi[28,], single_and_multi[29,] ) # 0.7182353

#mutli

cor(single_and_multi[22,], single_and_multi[23,] )  #-0.6161527
cor(single_and_multi[22,], single_and_multi[24,] ) # -0.2015345
cor(single_and_multi[22,], single_and_multi[25,] ) # 0.4247083
cor(single_and_multi[23,], single_and_multi[24,] ) # -0.04692151
cor(single_and_multi[23,], single_and_multi[25,] ) # -0.4218923
cor(single_and_multi[24,], single_and_multi[25,] ) # -0.7734885


write.table(single_and_multi,"~/Documents/ThesisWork/GitRepos/bild_signatures/Correlations_ICBP_Single_Multi.txt",sep='\t', col.names = NA,quote=F)

# do with non_adpative
# run assign single nonadaptive


#for(i in 1:length(colnames(data)))
  {
  #print(colnames(data)[i])
  #write.table(colnames(data)[i], file = "output.csv", row.names = FALSE, 
              #append = TRUE, col.names = FALSE, sep = ", ")
#   print("correlation with MK2206..an AKT  inhibitor")
#   print(cor(pred_drug[i],as.numeric(pred_drug$Sensitivity..logEC50),use="na.or.complete"))
  #print("correlation with Sigma AKT1/2..an AKT  inhibitor")
  
# cor(pred_drug[i],pred_drug$Sigma.AKT1.2.inhibitor,use="na.or.complete")
  #print("correlation with GSK2126458..an AKT  inhibitor")
  #print(cor(pred_drug[i],pred_drug$GSK2126458,use="na.or.complete"))
  #print("correlation with TRIciribine..an AKT  inhibitor")
  #print(cor(pred_drug[i],pred_drug$Triciribine,use="na.or.complete"))
=======
# for(i in 1:length(colnames(data)))
#   {
#   print(colnames(data)[i])
#   print("correlation with MK2206..an AKT  inhibitor")
#   print(cor(pred_drug[i],as.numeric(pred_drug$Sensitivity..logEC50),use="na.or.complete"))
#   print("correlation with Sigma AKT1/2..an AKT  inhibitor")
#   print(cor(pred_drug[i],pred_drug$Sigma.AKT1.2.inhibitor,use="na.or.complete"))
#   print("correlation with GSK2126458..an AKT  inhibitor")
#   print(cor(pred_drug[i],pred_drug$GSK2126458,use="na.or.complete"))
#   print("correlation with TRIciribine..an AKT  inhibitor")
#   print(cor(pred_drug[i],pred_drug$Triciribine,use="na.or.complete"))
#   print("correlation with Lapatinib...EGFR/HER2 inhibitor")
#   print(cor(pred_drug[i],pred_drug$Lapatinib,use="na.or.complete"))
>>>>>>> 2fac797b6fb95768996bf82bab2763ae0f043efa
#   print("correlation with Tykerb.IGF1R..1.1...EGFR/HER2/IGF1R inhibitor")
#   print(cor(pred_drug[i],pred_drug$Tykerb.IGF1R..1.1.,use="na.or.complete"))
#   print("correlation with GSK1838705...an IGF1R inhibitor")
#   print(cor(pred_drug[i],pred_drug$GSK1838705, use = "na.or.complete"))
<<<<<<< HEAD
# #  
  
}





# what we have done so far in term of cors is the AKT drugs to all combos on multi-path/single predictions.
# THE IGF1R predictions where good with AKT inhibitors 
# Shelley should correlate other drugs with all predictions. 
  -# Don't have bad drugs
  # HER2 with labpatinib, BIBW2206
  
  # we hav
  

=======
# # #   
#   }

```


Creating heatmaps
```{r }

if (!require("gplots")) {
   install.packages("gplots", dependencies = TRUE)
   library(gplots)
   }
if (!require("RColorBrewer")) {
   install.packages("RColorBrewer", dependencies = TRUE)
   library(RColorBrewer)
   }
multi<-data#read.table("~/Desktop/multipathway_preds.txt", sep='\t',row.names=1,header=1)
single<-read.csv("~/Dropbox/bild_signatures/multi_icbp_expr_pc/single_pathway_results.csv", row.names=1,header=1)
my_palette <- colorRampPalette(c("darkblue","aliceblue","brown4"))(n = 299)
col_breaks = c(seq(0,0.2,length=100), seq(0.2,0.4,length=100), seq(0.4,1,length=100)) 
# creates a 5 x 5 inch image
png("heatmaps_in_r.png",    # create PNG for the heat map        
  width = 5*300,        # 5 x 300 pixels
  height = 5*300,
  res = 300,            # 300 pixels per inch
  pointsize = 8)  
comb<-cbind(multi,single)
dim(comb)
colnames(comb)<-gsub(pattern = "adap_multi.pathway_activity_testset.csv",replacement = "A",x = colnames(comb))
#colnames(comb)<-gsub(pattern = "non",replacement = "NA",x = colnames(comb))
pdf(file='~/Dropbox/bild_signatures//bild_signatures/activity_subtype.pdf')

heatmap.2(as.matrix(comb),col=my_palette,margins=c(12,9),Rowv=F,Colv=F,dendrogram="none", trace="none",main="All possibilities",breaks = col_breaks)
heatmap.2(as.matrix(comb[,47:50]),col=my_palette,trace="none",main="Multipathway activity",margins=c(12,9),Rowv =F,Colv=F,dendrogram="none",ylab="ICBP Cell lines",breaks = col_breaks)
heatmap.2(as.matrix(comb[,51:54]),margins=c(12,9),col=my_palette, Rowv=F,Colv=F,dendrogram="none",trace="none",main="Single pathway activity",ylab="ICBP Cell lines",scale = "row")

comb_drug<-merge_drop(comb,drugs,by=0)
#plot(hclust(dist(comb_drug[,1:48]), method = "complete", members = NULL))
<<<<<<< HEAD

basal<-subset(comb_drug,comb_drug$Transcriptional.subtype...ERBB2.status=="Basal")
heatmap.2(as.matrix(basal[,22:25]),col=my_palette,margins=c(12,9),dendrogram="none", trace="none",main="Basal Multi")
heatmap.2(as.matrix(basal[,26:29]),col=my_palette,margins=c(12,9),dendrogram="none",lmat=rbind( c(0, 3, 4), c(2,1,0 ) ), lwid=c(1.5, 4, 2 ), trace="none",main="Basal single")
cor(basal[,22],basal$Sigma.AKT1.2.inhibitor,use="pairwise")

her<-subset(comb_drug[,1:44],comb_drug$Transcriptional.subtype...ERBB2.status=="ERBB2-amp"|comb_drug$Transcriptional.subtype...ERBB2.status=="ERBB2Amp")
heatmap.2(as.matrix(her[,22:25]),col=my_palette,dendrogram="none",lmat=rbind( c(0, 3, 4), c(2,1,0 ) ), lwid=c(1.5, 4, 2 ), trace="none",margins=c(12,9),main="HER2 Multi")
heatmap.2(as.matrix(her[,26:29]),col=my_palette,dendrogram="none",lmat=rbind( c(0, 3, 4), c(2,1,0 ) ), lwid=c(1.5, 4, 2 ), trace="none",margins=c(12,9),main="HER2 Single",scale="column")
cor(her[,22],her$Sigma.AKT1.2.inhibitor,use="pairwise")

claudin<-subset(comb_drug,comb_drug$Transcriptional.subtype...ERBB2.status=="Claudin-low")
heatmap.2(as.matrix(claudin[,22:25]),col=my_palette,dendrogram="none",lmat=rbind( c(0, 3, 4), c(2,1,0 ) ), lwid=c(1.5, 4, 2 ), trace="none",margins=c(12,9),main="Claudin Multi")
heatmap.2(as.matrix(claudin[,26:29]),col=my_palette,dendrogram="none",lmat=rbind( c(0, 3, 4), c(2,1,0 ) ), lwid=c(1.5, 4, 2 ), trace="none",margins=c(12,9),main="Claudin Single",scale="column")
cor(claudin[,22],claudin$Sigma.AKT1.2.inhibitor,use="na.or.complete")

luminal<-subset(comb_drug,comb_drug$Transcriptional.subtype...ERBB2.status=="Luminal")
heatmap.2(as.matrix(luminal[,22:25]),col=my_palette,dendrogram="none",lmat=rbind( c(0, 3, 4), c(2,1,0 ) ), lwid=c(1.5, 4, 2 ), trace="none",margins=c(12,9),main="Luminal Multi")
heatmap.2(as.matrix(luminal[,26:29]),col=my_palette,dendrogram="none",lmat=rbind( c(0, 3, 4), c(2,1,0 ) ), lwid=c(1.5, 4, 2 ), trace="none",margins=c(12,9),main="Luminal Single",scale="row")
=======
# write(file="~/Dropbox/bild_signatures/bild_signatures/pathway prediction drug response results.xls","Correlations for pathway predictions with Lapatinib and Sigma.AKT.inhibitor in BASAL subtype",append = T)
# write('',file="~/Dropbox/bild_signatures/bild_signatures/pathway prediction drug response results.xls", append=T)
basal<-subset(comb_drug,comb_drug$Transcriptional.subtype...ERBB2.status=="Basal")
# write("For Lapatinib",file="~/Dropbox/bild_signatures/bild_signatures/pathway prediction drug response results.xls", append =T)
# write(paste(colnames(basal)[1:54],cor(basal[,1:54],basal$Lapatinib,use="pairwise.complete.obs"),sep='\t'), file="~/Dropbox/bild_signatures/bild_signatures/pathway prediction drug response results.xls", append = T)
# write("For Sigma AKT inhibitor",file="~/Dropbox/bild_signatures/bild_signatures/pathway prediction drug response results.xls", append =T)
# write(paste(colnames(basal)[1:54],cor(basal[,1:54],basal$Sigma.AKT1.2.inhibitor,use="pairwise.complete.obs"),sep='\t'),file="~/Dropbox/bild_signatures/bild_signatures/pathway prediction drug response results.xls",append = T)

par(mfrow = c(2,1))
heatmap.2(as.matrix(basal[,47:50]),col=my_palette,margins=c(12,9),dendrogram="none", trace="none",main="Basal Multi",Rowv = NULL, Colv = NULL)
heatmap.2(as.matrix(basal[,51:54]),col=my_palette,margins=c(12,9),dendrogram="none",Rowv = NULL, Colv = NULL, trace="none",main="Basal single")


her<-subset(comb_drug,comb_drug$Transcriptional.subtype...ERBB2.status=="ERBB2-amp"|comb_drug$Transcriptional.subtype...ERBB2.status=="ERBB2Amp")
# wrtie(paste(colnames(her)[1:54],cor(her[,1:54],her$Lapatinib,use="pairwise.complete.obs"),sep='\t'),file="~/Dropbox/bild_signatures/bild_signatures/pathway prediction drug response results.xls",append = T)
# write("For Sigma AKT inhibitor",file="~/Dropbox/bild_signatures/bild_signatures/pathway prediction drug response results.xls", append =T)
# write(paste(colnames(her),cor(her[,1:54],her$Sigma.AKT1.2.inhibitor,use="pairwise.complete.obs"),sep='\t'),file="~/Dropbox/bild_signatures/bild_signatures/pathway prediction drug response results.xls",append = T)
# 

heatmap.2(as.matrix(her[,43:54]),col=my_palette,dendrogram="none",lmat=rbind( c(0, 3, 4), c(2,1,0 ) ), lwid=c(1.5, 4, 2 ), trace="none",margins=c(14,9),main="HER2 Multi",Rowv=F, Colv=F)
heatmap.2(as.matrix(her[,51:54]),col=my_palette,dendrogram="none",lmat=rbind( c(0, 3, 4), c(2,1,0 ) ), lwid=c(1.5, 4, 2 ), trace="none",margins=c(12,9),main="HER2 Single",Rowv=F, Colv=F,scale = "row")


claudin<-subset(comb_drug,comb_drug$Transcriptional.subtype...ERBB2.status=="Claudin-low")
cor(claudin[,1:54],claudin$Lapatinib,use="pairwise.complete.obs")# variance zero in this group
cor(claudin[,1:54],claudin$Sigma.AKT1.2.inhibitor,use="pairwise.complete.obs")

heatmap.2(as.matrix(claudin[,47:50]),col=my_palette,dendrogram="none",trace="none",margins=c(12,9),main="Claudin Multi",,Rowv=F, Colv=F)
heatmap.2(as.matrix(claudin[,51:54]),col=my_palette,dendrogram="none", trace="none",margins=c(12,9),main="Claudin Single",scale="row",,Rowv=F, Colv=F)
cor(claudin[,22],claudin$Sigma.AKT1.2.inhibitor,use="na.or.complete")

luminal<-subset(comb_drug,comb_drug$Transcriptional.subtype...ERBB2.status=="Luminal")
cor(luminal[,47:50],luminal$Lapatinib,use="pairwise.complete.obs")
cor(luminal[,51:54],luminal$Sigma.AKT1.2.inhibitor,use="pairwise.complete.obs")
heatmap.2(as.matrix(luminal[,47:50]),col=my_palette,dendrogram="none", trace="none",margins=c(12,9),main="Luminal Multi",Rowv=F, Colv=F)
heatmap.2(as.matrix(luminal[,47:50]),col=my_palette,dendrogram="none",trace="none",margins=c(12,9),main="Luminal Single",scale="row",Rowv=F, Colv=F)
>>>>>>> 2fac797b6fb95768996bf82bab2763ae0f043efa
cor(luminal[,22],luminal$Sigma.AKT1.2.inhibitor,use="na.or.complete")
multi_4<-rbind(basal[,43:46],her[,43:46],claudin[,43:46],luminal[,43:46])
png("heatmaps_multi_adap.png",width = 5*300,height = 5*300,res = 800, pointsize = 8)  
heatmap.2(as.matrix(multi_4), RowSideColors = c(rep("gray", length(rownames(basal))),rep("blue", length(rownames(her))),rep("black", length(rownames(claudin))),rep("green",length(rownames(luminal)))),col=my_palette,dendrogram="none", trace="none",margins=c(15,10),main="Multi Preds within Subtypes",scale="row",Rowv=F)
par(lend = 10)           # square line ends for the color legend
legend("topright",legend = c("Basal", "HER2", "Claudin","Luminal"), col = c("gray", "blue", "black","green"),  lty= 1,lwd = 10)
dev.off()
single_4<-rbind(basal[,51:54],her[,51:54],claudin[,51:54],luminal[,51:54])
heatmap.2(as.matrix(single_4), RowSideColors = c(rep("gray", length(rownames(basal))),rep("blue", length(rownames(her))),rep("black", length(rownames(claudin))),rep("green",length(rownames(luminal)))),col=my_palette,dendrogram="none", trace="none",margins=c(12,9),main="Single Preds within Subtypes",scale="row",Rowv=F)
par(lend = 10)           # square line ends for the color legend
legend("topright",legend = c("Basal", "HER2", "Claudin","Luminal"), col = c("gray", "blue", "black","green"),  lty= 1,lwd = 10)

dev.off()
```

```{r echo=FALSE}
time<-format(Sys.time(),"%a %b %d %X %Y")
```
This analysis was run on `r time` 
