---
title: "multipathway_ASSIGN"
author: "Mumtahena Rahman"
date: "December 23, 2014"
output: pdf_document
---

```{r,echo=FALSE,cache=TRUE,include=FALSE}
library(sva)
library(ASSIGN)
library(utils)
library(devtools)
install_github("wevanjohnson/ASSIGN",ref="adapt_gene_only")
library(ASSIGN)


```

Reading in the signature datasets...
```{r include=FALSE,echo=FALSE}
source("~/Dropbox/bild_signatures//bild_signatures/Rmarkdowns_scripts//Key_ASSIGN_functions.Rmd")
#setwd("~/Documents/ThesisWork/GitRepos/bild_signature_validation_old_repo/Datasets")
setwd("/Users/mumtahenarahman/Dropbox/bild_signature/Datasets/")
expr<-as.matrix(read.table("/Users/mumtahenarahman/Dropbox/Datasets/GFP18_AKT_BAD_HER2_IGF1R_RAF_ERK.tpmlog",sep='\t',row.names=1,header=1))
control<-subset(expr, select=GFP.1:GFP.12)
her2<-subset(expr, select=HER2.1:HER2.6)
akt<-subset(expr,select=AKT.1:AKT.6)
bad<-subset(expr,select=BAD.1:BAD.6)
igf1r<-subset(expr,select=IGF1R.1:IGF1R.6)
raf<-subset(expr,select=RAF.1:RAF.6)
erk<-subset(expr,select=ERK.1:ERK.6)
expr_all<-cbind(control,akt,bad,her2,igf1r,raf,erk)
dim(expr_all)
expr_all_f <-expr_all[apply(expr_all[,1:47]==0,1,mean) < 0.85,]

##Luise's signatures
multi<-read.table("~/Dropbox/egfr_opt/hmec_multi_egfr_mek_FeatureCount.tpmlog", sep='\t', header=1, row.names=1)
head(multi)
dim(multi)
multi<-multi[,order(colnames(multi))]
head(multi)
colnames(multi)
control_l<-multi[,1:6]
egfr_l<-multi[,7:12]
control_egfr_l<-cbind(control_l,egfr_l)
setwd("~/Dropbox/egfr_opt/")
gfp <- read.table("36hr_gfp_TPMlog.txt",header = 1, row.names=1)
dim(gfp)
egfr<- read.table("36hr_EGFR_train_TPMlog.txt",header = 1, row.names=1)
dim(egfr)
gfp_egfr_36<-cbind(gfp,egfr)
all_egfr<-merge_drop(control_egfr_l,gfp_egfr_36)
dim(all_egfr)
sub=c(6,6,9,9)
pcaplot(mat = all_egfr,sub = sub,center = T,scale = F)
bat<-as.matrix(cbind(c(colnames(all_egfr)),as.numeric(c(rep(1,12),rep(2,18)))))
egfr_all_f <-all_egfr[apply(all_egfr[,1:30]==0,1,mean) < 0.9,]
combat_expr<-ComBat(dat=egfr_all_f, batch=bat[,2], mod=NULL, numCovs=NULL)
pcaplot(combat_expr,sub)
trainingLabel<-list(control=list(egfr=1:6),egfr=7:12)
basedir=getwd()
sub_dir<-paste(basedir,"egfr_f_25_egfr_gene_list",sep='/')
dir.create(sub_dir)
assign_easy_multi(trainingData = combat_expr[,1:12],test=combat_expr[,13:30],trainingLabel1 = trainingLabel,g=25,out_dir_base = sub_dir,single = 1)
sub_dir<-paste(basedir,"egfr_f_25_L_egfr_gene_list",sep='/')
dir.create(sub_dir)
trainingLabel<-list(control=list(egfr=1:9),egfr=10:18)
assign_easy_multi(trainingData = all_egfr[,13:30],test=all_egfr[,1:12],trainingLabel1 = trainingLabel,g=25,out_dir_base = sub_dir,single = 1)


icbp<-read.table("icbp_Rsubread_tpmlog.txt", sep='\t', header=1, row.names=1)
dim(icbp)

#gfp_egfr_multi_f <- merge_drop(control_egfr_l,expr_all_f)
#dim(gfp_egfr_multi_f)

icbp<-as.matrix(read.table("~/Dropbox/bild_signatures/Datasets/icbp_Rsubread_tpmlog.txt", sep='\t', stringsAsFactors=FALSE, header=1, row.names=1))


#gfp_egfr_icbp_f<-merge_drop(gfp_egfr_multi_f,icbp,by=0)
icbp_expr_all_f<-merge_drop(expr_all_f,icbp,by=0)
colnames(icbp_expr_all_f)
sub<-c(12,6,6,5,6,6,6,55)
pdf("pca_plots_4_30.pdf")
pcaplot(mat = icbp_expr_all_f,sub = sub)
length(colnames(icbp_expr_all_f))
bat1<-as.matrix(cbind(c(colnames(icbp_expr_all_f)),as.numeric(c(rep(1,47),rep(2,55)))))
combat_expr1<-ComBat(dat=icbp_expr_all_f, batch=bat1[,2], mod=NULL, numCovs=NULL,par.prior = T,prior.plots = T)
pcaplot(combat_expr1,sub)
dev.off()
basedir="~/Dropbox/bild_signatures/icbp_15_april_assign_adap_//"
dir.create( basedir)
c_gfp<-subset(combat_expr1, select=GFP.1:GFP.12)
c_akt<-subset(combat_expr1, select=AKT.1:AKT.6)
c_bad<-subset(combat_expr1, select=BAD.1:BAD.6)
c_her2<-subset(combat_expr1, select=HER2.1:HER2.6)
c_igf1r<-subset(combat_expr1, select=IGF1R.1:IGF1R.6)
c_raf<-subset(combat_expr1, select=RAF.1:RAF.6)
c_erk<-subset(combat_expr1, select=ERK.1:ERK.6)

c_test<-combat_expr1[,48:102]


paths<-c("AKT","BAD","HER2","IGF1R","RAF1","ERK")
paths_1<-combn(paths,1,simplify = F)
paths_2<-combn(paths,2,simplify = F)
paths_3<-combn(paths,3,simplify = F)
paths_4<-combn(paths,4,simplify = F)
paths_5<-combn(paths,5,simplify = F)
paths_6<-combn(paths,6,simplify = F)

#############trying one pathways at a time in multipathway#############
#1. AKT
trainingLabela<-list(control=list(akt=1:12),akt=13:18)
sub_dir<-paste(basedir,"akt_150_gene_list",sep='/')
dir.create( sub_dir)
assign_easy_multi(trainingData = cbind(c_gfp,c_akt),test=c_test,trainingLabel1 = trainingLabela,g=150,out_dir_base = sub_dir,single = 1)

trainingLabela<-list(control=list(akt=1:12),akt=13:18)
sub_dir<-paste(basedir,"akt_200_gene_list",sep='/')
dir.create( sub_dir)
assign_easy_multi(trainingData = cbind(c_gfp,c_akt),test=c_test,trainingLabel1 = trainingLabela,g=200,out_dir_base = sub_dir,single = 1)


#2. BAD
trainingLabelb<-list(control=list(bad=1:12),bad=13:18)
sub_dir<-paste(basedir,"bad_150_gene_list",sep='/')
dir.create( sub_dir)
assign_easy_multi(trainingData = cbind(c_gfp,c_bad),test=c_test,trainingLabel1 = trainingLabelb,g=150,out_dir_base = sub_dir,single = 1)

trainingLabelb<-list(control=list(bad=1:12),bad=13:18)
sub_dir<-paste(basedir,"bad_200_gene_list",sep='/')
dir.create( sub_dir)
assign_easy_multi(trainingData = cbind(c_gfp,c_bad),test=c_test,trainingLabel1 = trainingLabelb,g=200,out_dir_base = sub_dir,single = 1)


#3. HER2
trainingLabelh<-list(control=list(her2=1:12),her2=13:17)
sub_dir<-paste(basedir,"her2_15_gene_list",sep='/')
dir.create( sub_dir)
assign_easy_multi(trainingData = cbind(c_gfp,c_her2),test=c_test,trainingLabel1 = trainingLabelh,g=15,out_dir_base = sub_dir,single = 1)
trainingLabelh<-list(control=list(her2=1:12),her2=13:17)
sub_dir<-paste(basedir,"her2_25_gene_list",sep='/')
dir.create( sub_dir)
assign_easy_multi(trainingData = cbind(c_gfp,c_her2),test=c_test,trainingLabel1 = trainingLabelh,g=25,out_dir_base = sub_dir,single = 1)
trainingLabelh<-list(control=list(her2=1:12),her2=13:17)
sub_dir<-paste(basedir,"her2_50_gene_list",sep='/')
dir.create( sub_dir)
assign_easy_multi(trainingData = cbind(c_gfp,c_her2),test=c_test,trainingLabel1 = trainingLabelh,g=50,out_dir_base = sub_dir,single = 1)
sub_dir<-paste(basedir,"her2_75_gene_list",sep='/')
dir.create( sub_dir)
assign_easy_multi(trainingData = cbind(c_gfp,c_her2),test=c_test,trainingLabel1 = trainingLabelh,g=75,out_dir_base = sub_dir,single = 1)

#4. IGF1R
trainingLabeli<-list(control=list(igf1r=1:12),igf1r=13:18)
sub_dir<-paste(basedir,"igf1r_100_gene_list",sep='/')
dir.create( sub_dir)
assign_easy_multi(trainingData = cbind(c_gfp,c_igf1r),test=c_test,trainingLabel1 = trainingLabeli,g=100,out_dir_base = sub_dir,single = 1)

trainingLabeli<-list(control=list(igf1r=1:12),igf1r=13:18)
sub_dir<-paste(basedir,"igf1r_10_gene_list",sep='/')
dir.create( sub_dir)
assign_easy_multi(trainingData = cbind(c_gfp,c_igf1r),test=c_test,trainingLabel1 = trainingLabeli,g=10,out_dir_base = sub_dir,single = 1)

trainingLabeli<-list(control=list(igf1r=1:12),igf1r=13:18)
sub_dir<-paste(basedir,"igf1r_15_gene_list",sep='/')
dir.create( sub_dir)
assign_easy_multi(trainingData = cbind(c_gfp,c_igf1r),test=c_test,trainingLabel1 = trainingLabeli,g=15,out_dir_base = sub_dir,single = 1)

trainingLabeli<-list(control=list(igf1r=1:12),igf1r=13:18)
sub_dir<-paste(basedir,"igf1r_45_gene_list",sep='/')
dir.create( sub_dir)
assign_easy_multi(trainingData = cbind(c_gfp,c_igf1r),test=c_test,trainingLabel1 = trainingLabeli,g=45,out_dir_base = sub_dir,single = 1)

trainingLabeli<-list(control=list(igf1r=1:12),igf1r=13:18)
sub_dir<-paste(basedir,"igf1r_75_gene_list",sep='/')
dir.create( sub_dir)
assign_easy_multi(trainingData = cbind(c_gfp,c_igf1r),test=c_test,trainingLabel1 = trainingLabeli,g=75,out_dir_base = sub_dir,single = 1)

trainingLabeli<-list(control=list(igf1r=1:12),igf1r=13:18)
sub_dir<-paste(basedir,"igf1r_150_gene_list",sep='/')
dir.create( sub_dir)
assign_easy_multi(trainingData = cbind(c_gfp,c_igf1r),test=c_test,trainingLabel1 = trainingLabeli,g=150,out_dir_base = sub_dir,single = 1)

trainingLabeli<-list(control=list(igf1r=1:12),igf1r=13:18)
sub_dir<-paste(basedir,"igf1r_200_gene_list",sep='/')
dir.create( sub_dir)
assign_easy_multi(trainingData = cbind(c_gfp,c_igf1r),test=c_test,trainingLabel1 = trainingLabeli,g=200,out_dir_base = sub_dir,single = 1)

trainingLabeli<-list(control=list(igf1r=1:12),igf1r=13:18)
sub_dir<-paste(basedir,"igf1r_250_gene_list",sep='/')
dir.create( sub_dir)
assign_easy_multi(trainingData = cbind(c_gfp,c_igf1r),test=c_test,trainingLabel1 = trainingLabeli,g=250,out_dir_base = sub_dir,single = 1)

 #5. RAF
trainingLabelr<-list(control=list(raf=1:12),raf=13:18)
sub_dir<-paste(basedir,"raf_200_gene_list",sep='/')
dir.create( sub_dir)
assign_easy_multi(trainingData = cbind(c_gfp,c_raf),test=c_test,trainingLabel1 = trainingLabelr,g=200,out_dir_base = sub_dir,single = 1)
trainingLabelr<-list(control=list(raf=1:12),raf=13:18)
sub_dir<-paste(basedir,"raf_150_gene_list",sep='/')
dir.create( sub_dir)
assign_easy_multi(trainingData = cbind(c_gfp,c_raf),test=c_test,trainingLabel1 = trainingLabelr,g=150,out_dir_base = sub_dir,single = 1)
 #6. ERK
trainingLabele<-list(control=list(erk=1:12),erk=13:18)
sub_dir<-paste(basedir,"erk_100_gene_list",sep='/')
dir.create( sub_dir)
assign_easy_multi(trainingData = cbind(c_gfp,c_erk),test=c_test,trainingLabel1 = trainingLabele,g=100,out_dir_base = sub_dir,single = 1)


trainingLabele<-list(control=list(erk=1:12),erk=13:18)
sub_dir<-paste(basedir,"erk_200_gene_list",sep='/')
dir.create( sub_dir)
assign_easy_multi(trainingData = cbind(c_gfp,c_erk),test=c_test,trainingLabel1 = trainingLabele,g=200,out_dir_base = sub_dir,single = 1)

trainingLabele<-list(control=list(erk=1:12),erk=13:18)
sub_dir<-paste(basedir,"erk_150_gene_list",sep='/')
dir.create( sub_dir)
assign_easy_multi(trainingData = cbind(c_gfp,c_erk),test=c_test,trainingLabel1 = trainingLabele,g=150,out_dir_base = sub_dir,single = 1)

trainingLabele<-list(control=list(erk=1:12),erk=13:18)
sub_dir<-paste(basedir,"erk_65_gene_list",sep='/')
dir.create( sub_dir)
assign_easy_multi(trainingData = cbind(c_gfp,c_erk),test=c_test,trainingLabel1 = trainingLabele,g=65,out_dir_base = sub_dir,single = 1)

trainingLabele<-list(control=list(erk=1:12),erk=13:18)
sub_dir<-paste(basedir,"erk_250_gene_list",sep='/')
dir.create( sub_dir)
assign_easy_multi(trainingData = cbind(c_gfp,c_erk),test=c_test,trainingLabel1 = trainingLabele,g=250,out_dir_base = sub_dir,single = 1)

trainingLabele<-list(control=list(erk=1:12),erk=13:18)
sub_dir<-paste(basedir,"erk_300_gene_list",sep='/')
dir.create( sub_dir)
assign_easy_multi(trainingData = cbind(c_gfp,c_erk),test=c_test,trainingLabel1 = trainingLabele,g=300,out_dir_base = sub_dir,single = 1)

trainingLabele<-list(control=list(erk=1:12),erk=13:18)
sub_dir<-paste(basedir,"erk_400_gene_list",sep='/')
dir.create( sub_dir)
assign_easy_multi(trainingData = cbind(c_gfp,c_erk),test=c_test,trainingLabel1 = trainingLabele,g=400,out_dir_base = sub_dir,single = 1)

#############trying two pathways at a time in multipathway#############
#1. HER2 & AKT
trainha<-cbind(c_gfp,c_akt,c_her2)
trainingLabelha<-list(control=list(akt=1:12,her2=1:12),akt=13:18,her2=19:23)
sub_dir=paste(basedir,"her2_akt",sep='/')
dir.create( sub_dir)
#assign_easy_multi(trainingData = trainha,test=c_test,trainingLabel1 = trainingLabelha,g=c(150,15),out_dir_base = sub_dir)
assign_easy_multi(trainingData = trainha,test=c_test,trainingLabel1 = trainingLabelha,g=c(75,15),out_dir_base = sub_dir)
#2. HER2 & BAD
trainhb<-cbind(c_gfp,c_bad,c_her2)
trainingLabelhb<-list(control=list(bad=1:12,her2=1:12),bad=13:18,her2=19:23)
sub_dir=paste(basedir,"her2_bad",sep='/')
dir.create(sub_dir)
#assign_easy_multi(trainingData = trainhb,test=c_test,trainingLabel1 = trainingLabelhb,g=c(150,15),out_dir_base = sub_dir)
assign_easy_multi(trainingData = trainhb,test=c_test,trainingLabel1 = trainingLabelhb,g=c(200,15),out_dir_base = sub_dir)

#3. HER2 & IGF1R
trainhi<-cbind(c_gfp,c_igf1r,c_her2)
trainingLabelhi<-list(control=list(igf1r=1:12,her2=1:12),igf1r=13:18,her2=19:23)
sub_dir=paste(basedir,"her2_igf1r",sep='/')
dir.create(sub_dir)
#assign_easy_multi(trainingData = trainhi,test=c_test,trainingLabel1 = trainingLabelhi,g=c(100,15),out_dir_base = sub_dir)
assign_easy_multi(trainingData = trainhi,test=c_test,trainingLabel1 = trainingLabelhi,g=c(75,15),out_dir_base = sub_dir)



#4. AKT & BAD
trainab<-cbind(c_gfp,c_akt,c_bad)
trainingLabelab<-list(control=list(akt=1:12,bad=1:12),akt=13:18,bad=19:24)
sub_dir=paste(basedir,"akt_bad",sep='/')
dir.create(sub_dir)
#assign_easy_multi(trainingData = trainab,test=c_test,trainingLabel1 = trainingLabelab,g=c(150,150),out_dir_base = sub_dir)
assign_easy_multi(trainingData = trainab,test=c_test,trainingLabel1 = trainingLabelab,g=c(75,200),out_dir_base = sub_dir)

#5. AKT & IGF1R
trainai<-cbind(c_gfp,c_akt,c_igf1r)

trainingLabelai<-list(control=list(akt=1:12,igf1r=1:12),akt=13:18,igf1r=19:24)
sub_dir=paste(basedir,"akt_igf1r",sep='/')
dir.create( sub_dir)
#assign_easy_multi(trainingData = trainai,test=c_test,trainingLabel1 = trainingLabelai,g=c(150,100),out_dir_base = sub_dir)
assign_easy_multi(trainingData = trainai,test=c_test,trainingLabel1 = trainingLabelai,g=c(75,75),out_dir_base = sub_dir)


#6. BAD & IGF1R
trainbi<-cbind(c_gfp,c_bad,c_igf1r)
trainingLabelbi<-list(control=list(bad=1:12,igf1r=1:12),bad=13:18,igf1r=19:24)
sub_dir=paste(basedir,"bad_igf1r",sep='/')
dir.create( sub_dir)
#assign_easy_multi(trainingData = trainbi,test=c_test,trainingLabel1 = trainingLabelbi,g=c(150,100),out_dir_base = sub_dir)

assign_easy_multi(trainingData = trainbi,test=c_test,trainingLabel1 = trainingLabelbi,g=c(200,75),out_dir_base = sub_dir)

#7. ERK & IGF1R
trainei<-cbind(c_gfp,c_erk,c_igf1r)
trainingLabelei<-list(control=list(erk=1:12,igf1r=1:12),erk=13:18,igf1r=19:24)
sub_dir=paste(basedir,"erk_igf1r",sep='/')
dir.create( sub_dir)
#assign_easy_multi(trainingData = trainei,test=c_test,trainingLabel1 = trainingLabelei,g=c(100,100),out_dir_base = sub_dir)
assign_easy_multi(trainingData = trainei,test=c_test,trainingLabel1 = trainingLabelei,g=c(250,75),out_dir_base = sub_dir)


#8. ERK & AKT
trainea<-cbind(c_gfp,c_erk,c_akt)
trainingLabelea<-list(control=list(erk=1:12,akt=1:12),erk=13:18,akt=19:24)
sub_dir=paste(basedir,"erk_akt",sep='/')
dir.create( sub_dir)
#assign_easy_multi(trainingData = trainea,test=c_test,trainingLabel1 = trainingLabelea,g=c(100,150),out_dir_base = sub_dir)
assign_easy_multi(trainingData = trainea,test=c_test,trainingLabel1 = trainingLabelea,g=c(250,75),out_dir_base = sub_dir)


#9. ERK & BAD
traineb<-cbind(c_gfp,c_erk,c_bad)
trainingLabeleb<-list(control=list(erk=1:12,bad=1:12),erk=13:18,bad=19:24)
sub_dir=paste(basedir,"erk_bad",sep='/')
dir.create( sub_dir)
#assign_easy_multi(trainingData = traineb,test=c_test,trainingLabel1 = trainingLabeleb,g=c(100,150),out_dir_base = sub_dir)
assign_easy_multi(trainingData = traineb,test=c_test,trainingLabel1 = trainingLabeleb,g=c(250,200),out_dir_base = sub_dir)


#10. ERK & HER2
traineh<-cbind(c_gfp,c_erk,c_her2)
trainingLabeleh<-list(control=list(erk=1:12,her2=1:12),erk=13:18,her2=19:23)
sub_dir=paste(basedir,"erk_her2",sep='/')
dir.create( sub_dir)
#assign_easy_multi(trainingData = traineh,test=c_test,trainingLabel1 = trainingLabeleh,g=c(100,15),out_dir_base = sub_dir)
assign_easy_multi(trainingData = traineh,test=c_test,trainingLabel1 = trainingLabeleh,g=c(250,15),out_dir_base = sub_dir)


#11. AKT & RAF
trainar<-cbind(c_gfp,c_akt,c_raf)
trainingLabelar<-list(control=list(akt=1:12,raf=1:12),akt=13:18,raf=19:24)
sub_dir=paste(basedir,"akt_raf",sep='/')
dir.create( sub_dir)
#assign_easy_multi(trainingData = trainar,test=c_test,trainingLabel1 = trainingLabelah,g=c(150,200),out_dir_base = sub_dir)
assign_easy_multi(trainingData = trainar,test=c_test,trainingLabel1 = trainingLabelar,g=c(75,100),out_dir_base = sub_dir)

#12. BAD & RAF
trainbr<-cbind(c_gfp,c_bad,c_raf)
trainingLabelbr<-list(control=list(bad=1:12,raf=1:12),bad=13:18,raf=19:24)
sub_dir=paste(basedir,"bad_raf",sep='/')
dir.create( sub_dir)
#assign_easy_multi(trainingData = traineh,test=c_test,trainingLabel1 = trainingLabeleh,g=c(150,200),out_dir_base = sub_dir)
assign_easy_multi(trainingData = trainbr,test=c_test,trainingLabel1 = trainingLabelbr,g=c(200,100),out_dir_base = sub_dir)

#13. HER2 & RAF
trainhr<-cbind(c_gfp,c_her2,c_raf)
trainingLabelhr<-list(control=list(her2=1:12,raf=1:12),her2=13:17,raf=18:23)
sub_dir=paste(basedir,"her2_raf",sep='/')
dir.create( sub_dir)
assign_easy_multi(trainingData = trainhr,test=c_test,trainingLabel1 = trainingLabelhr,g=c(15,100),out_dir_base = sub_dir)

#14.ERK & RAF
trainer<-cbind(c_gfp,c_erk,c_raf)
trainingLabeler<-list(control=list(erk=1:12,raf=1:12),erk=13:18,raf=19:24)
sub_dir=paste(basedir,"erk_raf",sep='/')
dir.create( sub_dir)
#assign_easy_multi(trainingData = traineh,test=c_test,trainingLabel1 = trainingLabeleh,g=c(150,200),out_dir_base = sub_dir)
assign_easy_multi(trainingData = trainer,test=c_test,trainingLabel1 = trainingLabeler,g=c(250,100),out_dir_base = sub_dir)

#15. IGF1R & RAF
trainir<-cbind(c_gfp,c_igf1r,c_raf)
trainingLabelir<-list(control=list(igf1r=1:12,raf=1:12),igf1r=13:18,raf=19:24)
sub_dir=paste(basedir,"igf1r_raf",sep='/')
dir.create( sub_dir)
#assign_easy_multi(trainingData = traineh,test=c_test,trainingLabel1 = trainingLabeleh,g=c(150,200),out_dir_base = sub_dir)
assign_easy_multi(trainingData = trainir,test=c_test,trainingLabel1 = trainingLabelir,g=c(75,100),out_dir_base = sub_dir)

#############trying three pathways at a time in multipathway#############
#1. HER2, AKT & BAD
trainhab<-cbind(c_gfp,c_akt,c_bad,c_her2)
trainingLabelhab<-list(control=list(akt=1:12,bad=1:12,her2=1:12),akt=13:18,bad=19:24,her2=25:29)
sub_dir=paste(basedir,"her2_akt_bad",sep='/')
dir.create(sub_dir)
#assign_easy_multi(trainingData = trainhab,test=c_test,trainingLabel1 = trainingLabelhab,g=c(150,150,15),out_dir_base = sub_dir)
assign_easy_multi(trainingData = trainhab,test=c_test,trainingLabel1 = trainingLabelhab,g=c(75,200,15),out_dir_base = sub_dir)


#2. HER2, BAD & IGF1R
trainhbi<-cbind(c_gfp,c_igf1r,c_bad,c_her2)
trainingLabelhbi<-list(control=list(igf1r=1:12,bad=1:12,her2=1:12),igf1r=13:18,bad=19:24,her2=25:29)
sub_dir=paste(basedir,"her2_bad_igf1r",sep='/')
dir.create(sub_dir)
#assign_easy_multi(trainingData = trainhbi,test=c_test,trainingLabel1 = trainingLabelhbi,g=c(100,150,15),out_dir_base = sub_dir)
assign_easy_multi(trainingData = trainhbi,test=c_test,trainingLabel1 = trainingLabelhbi,g=c(75,200,15),out_dir_base = sub_dir)


#3. AKT, BAD & IGF1R
trainabi<-cbind(c_gfp,c_akt,c_bad,c_igf1r)
trainingLabelabi<-list(control=list(akt=1:12,bad=1:12,igf1r=1:12),akt=13:18,bad=19:24,igf1r=25:30)
sub_dir=paste(basedir,"akt_bad_igf1r",sep='/')
dir.create(sub_dir)
#assign_easy_multi(trainingData = trainabi,test=c_test,trainingLabel1 = trainingLabelabi,g=c(150,150,100),out_dir_base = sub_dir)
assign_easy_multi(trainingData = trainabi,test=c_test,trainingLabel1 = trainingLabelabi,g=c(75,200,75),out_dir_base = sub_dir)


#4. AKT, BAD & ERK
trainabe<-cbind(c_gfp,c_akt,c_bad,c_erk)
trainingLabelabe<-list(control=list(akt=1:12,bad=1:12,erk=1:12),akt=13:18,bad=19:24,erk=25:30)
sub_dir=paste(basedir,"akt_bad_erk",sep='/')
dir.create(sub_dir)
#assign_easy_multi(trainingData = trainabe,test=c_test,trainingLabel1 = trainingLabelabe,g=c(150,150,100),out_dir_base = sub_dir)
assign_easy_multi(trainingData = trainabe,test=c_test,trainingLabel1 = trainingLabelabe,g=c(75,200,250),out_dir_base = sub_dir)


#5. AKT, HER2 & IGF1R
trainahi<-cbind(c_gfp,c_akt,c_her2,c_igf1r)
trainingLabelahi<-list(control=list(akt=1:12,her2=1:12,igf1r=1:12),akt=13:18,her2=19:23,igf1r=24:29)
sub_dir=paste(basedir,"akt_her2_igf1r",sep='/')
dir.create(sub_dir)
#assign_easy_multi(trainingData = trainahi,test=c_test,trainingLabel1 = trainingLabelahi,g=c(150,15,100),out_dir_base = sub_dir)
assign_easy_multi(trainingData = trainahi,test=c_test,trainingLabel1 = trainingLabelahi,g=c(75,15,75),out_dir_base = sub_dir)


#6. AKT, HER2 & ERK
trainahe<-cbind(c_gfp,c_akt,c_her2,c_erk)
trainingLabelahe<-list(control=list(akt=1:12,her2=1:12,igf1r=1:12),akt=13:18,her2=19:23,erk=24:29)
sub_dir=paste(basedir,"akt_her2_erk",sep='/')
dir.create(sub_dir)
#assign_easy_multi(trainingData = trainahe,test=c_test,trainingLabel1 = trainingLabelahe,g=c(150,15,100),out_dir_base = sub_dir)
assign_easy_multi(trainingData = trainahe,test=c_test,trainingLabel1 = trainingLabelahe,g=c(75,15,250),out_dir_base = sub_dir)

#7. AKT, IGF1R & ERK
trainaie<-cbind(c_gfp,c_akt,c_igf1r,c_erk)
trainingLabelaie<-list(control=list(akt=1:12,igf1r=1:12,erk=1:12),akt=13:18,igf1r=19:24,erk=25:30)
sub_dir=paste(basedir,"akt_igf1r_erk",sep='/')
dir.create(sub_dir)
#assign_easy_multi(trainingData = trainaie,test=c_test,trainingLabel1 = trainingLabelaie,g=c(150,100,100),out_dir_base = sub_dir)
assign_easy_multi(trainingData = trainaie,test=c_test,trainingLabel1 = trainingLabelaie,g=c(75,75,250),out_dir_base = sub_dir)


#8. BAD, IGF1R & ERK
trainbie<-cbind(c_gfp,c_bad,c_igf1r,c_erk)
trainingLabelbie<-list(control=list(bad=1:12,igf1r=1:12,erk=1:12),bad=13:18,igf1r=19:24,erk=25:30)
sub_dir=paste(basedir,"bad_igf1r_erk",sep='/')
dir.create(sub_dir)
#assign_easy_multi(trainingData = trainbie,test=c_test,trainingLabel1 = trainingLabelbie,g=c(150,100,100),out_dir_base = sub_dir)
assign_easy_multi(trainingData = trainbie,test=c_test,trainingLabel1 = trainingLabelbie,g=c(200,75,250),out_dir_base = sub_dir)


#9. BAD, HER2 & ERK
trainbhe<-cbind(c_gfp,c_bad,c_her2,c_erk)
trainingLabelbhe<-list(control=list(bad=1:12,her2=1:12,erk=1:12),bad=13:18,her2=19:23,erk=24:29)
sub_dir=paste(basedir,"bad_her2_erk",sep='/')
dir.create(sub_dir)
#assign_easy_multi(trainingData = trainbhe,test=c_test,trainingLabel1 = trainingLabelbhe,g=c(150,15,100),out_dir_base = sub_dir)
assign_easy_multi(trainingData = trainbhe,test=c_test,trainingLabel1 = trainingLabelbhe,g=c(200,15,250),out_dir_base = sub_dir)


#10. IGF1R, HER2 & ERK
trainihe<-cbind(c_gfp,c_igf1r,c_her2,c_erk)
trainingLabelihe<-list(control=list(igf1r=1:12,her2=1:12,erk=1:12),igf1r=13:18,her2=19:23,erk=24:29)
sub_dir=paste(basedir,"igf1r_her2_erk",sep='/')
dir.create(sub_dir)
#assign_easy_multi(trainingData = trainihe,test=c_test,trainingLabel1 = trainingLabelihe,g=c(100,15,100),out_dir_base = sub_dir)
assign_easy_multi(trainingData = trainihe,test=c_test,trainingLabel1 = trainingLabelihe,g=c(75,15,250),out_dir_base = sub_dir)

#11. AKT, HER2 & RAF1
trainahr<-cbind(c_gfp,c_akt,c_her2,c_raf)
trainingLabelahr<-list(control=list(akt=1:12,her2=1:12,raf=1:12),akt=13:18,her2=19:23,raf=24:29)
sub_dir=paste(basedir,"akt_her2_raf",sep='/')
dir.create(sub_dir)
#assign_easy_multi(trainingData = trainihe,test=c_test,trainingLabel1 = trainingLabelihe,g=c(100,15,100),out_dir_base = sub_dir)
assign_easy_multi(trainingData = trainahr,test=c_test,trainingLabel1 = trainingLabelahr,g=c(75,15,100),out_dir_base = sub_dir)

#12. AKT, IGF1R & RAF
trainair<-cbind(c_gfp,c_akt,c_igf1r,c_raf)
trainingLabelair<-list(control=list(akt=1:12,igf1r=1:12,raf=1:12),akt=13:18,igf1r=19:24,raf=25:30)
sub_dir=paste(basedir,"akt_igf1r_raf",sep='/')
dir.create(sub_dir)
#assign_easy_multi(trainingData = trainbie,test=c_test,trainingLabel1 = trainingLabelbie,g=c(150,100,100),out_dir_base = sub_dir)
assign_easy_multi(trainingData = trainair,test=c_test,trainingLabel1 = trainingLabelair,g=c(75,75,100),out_dir_base = sub_dir)

#13. AKT, ERK & RAF
trainaer<-cbind(c_gfp,c_akt,c_erk,c_raf)
trainingLabelaer<-list(control=list(akt=1:12,erk=1:12,raf=1:12),akt=13:18,erk=19:24,raf=25:30)
sub_dir=paste(basedir,"akt_erk_raf",sep='/')
dir.create(sub_dir)
#assign_easy_multi(trainingData = trainbie,test=c_test,trainingLabel1 = trainingLabelbie,g=c(150,100,100),out_dir_base = sub_dir)
assign_easy_multi(trainingData = trainaer,test=c_test,trainingLabel1 = trainingLabelaer,g=c(75,250,100),out_dir_base = sub_dir)

##14. BAD, RAF & ERK
trainbre<-cbind(c_gfp,c_bad,c_raf,c_erk)
trainingLabelbre<-list(control=list(bad=1:12,raf=1:12,erk=1:12),bad=13:18,raf=19:24,erk=25:30)
sub_dir=paste(basedir,"bad_raf_erk",sep='/')
dir.create(sub_dir)
#assign_easy_multi(trainingData = trainbie,test=c_test,trainingLabel1 = trainingLabelbie,g=c(150,100,100),out_dir_base = sub_dir)
assign_easy_multi(trainingData = trainbre,test=c_test,trainingLabel1 = trainingLabelbre,g=c(200,100,250),out_dir_base = sub_dir)

#15. HER2, IGF1R & RAF
trainhir<-cbind(c_gfp,c_raf,c_igf1r,c_her2)
trainingLabelhir<-list(control=list(raf=1:12,igf1r=1:12,her2=1:12),raf=13:18,igf1r=19:24,her2=25:29)
sub_dir=paste(basedir,"her2_igf1r_raf",sep='/')
dir.create(sub_dir)
#assign_easy_multi(trainingData = trainhab,test=c_test,trainingLabel1 = trainingLabelhab,g=c(150,150,15),out_dir_base = sub_dir)
assign_easy_multi(trainingData = trainhir,test=c_test,trainingLabel1 = trainingLabelhir,g=c(100,75,15),out_dir_base = sub_dir)


#16. HER2, RAF & ERK
trainher<-cbind(c_gfp,c_raf,c_erk,c_her2)
trainingLabelher<-list(control=list(raf=1:12,erk=1:12,her2=1:12),raf=13:18,erk=19:24,her2=25:29)
sub_dir=paste(basedir,"her2_raf_erk",sep='/')
dir.create(sub_dir)
#assign_easy_multi(trainingData = trainhbi,test=c_test,trainingLabel1 = trainingLabelhbi,g=c(100,150,15),out_dir_base = sub_dir)
assign_easy_multi(trainingData = trainhbi,test=c_test,trainingLabel1 = trainingLabelhbi,g=c(100,250,15),out_dir_base = sub_dir)

#17. HER2, BAD & RAF
trainhbr<-cbind(c_gfp,c_raf,c_bad,c_her2)
trainingLabelhbr<-list(control=list(raf=1:12,bad=1:12,her2=1:12),raf=13:18,bad=19:24,her2=25:29)
sub_dir=paste(basedir,"her2_bad_raf",sep='/')
dir.create(sub_dir)
#assign_easy_multi(trainingData = trainhab,test=c_test,trainingLabel1 = trainingLabelhab,g=c(150,150,15),out_dir_base = sub_dir)
assign_easy_multi(trainingData = trainhbr,test=c_test,trainingLabel1 = trainingLabelhbr,g=c(100,200,15),out_dir_base = sub_dir)


#18. AKT, BAD & RAF
trainabr<-cbind(c_gfp,c_akt,c_bad,c_raf)
trainingLabelabr<-list(control=list(akt=1:12,bad=1:12,raf=1:12),akt=13:18,bad=19:24,raf=25:30)
sub_dir=paste(basedir,"akt_bad_raf",sep='/')
dir.create(sub_dir)
#assign_easy_multi(trainingData = trainbie,test=c_test,trainingLabel1 = trainingLabelbie,g=c(150,100,100),out_dir_base = sub_dir)
assign_easy_multi(trainingData = trainabr,test=c_test,trainingLabel1 = trainingLabelabr,g=c(75,200,100),out_dir_base = sub_dir)

##19. BAD, RAF & IGF1R
trainbri<-cbind(c_gfp,c_bad,c_raf,c_igf1r)
trainingLabelbri<-list(control=list(bad=1:12,raf=1:12,igf1r=1:12),bad=13:18,raf=19:24,igf1r=25:30)
sub_dir=paste(basedir,"bad_raf_igf1r",sep='/')
dir.create(sub_dir)
#assign_easy_multi(trainingData = trainbie,test=c_test,trainingLabel1 = trainingLabelbie,g=c(150,100,100),out_dir_base = sub_dir)
assign_easy_multi(trainingData = trainbri,test=c_test,trainingLabel1 = trainingLabelbri,g=c(200,100,75),out_dir_base = sub_dir)

##20. IGF1R, RAF & ERK
trainire<-cbind(c_gfp,c_igf1r,c_raf,c_erk)
trainingLabelire<-list(control=list(igf1r=1:12,raf=1:12,erk=1:12),igf1r=13:18,raf=19:24,erk=25:30)
sub_dir=paste(basedir,"igf1r_raf_erk",sep='/')
dir.create(sub_dir)
#assign_easy_multi(trainingData = trainbie,test=c_test,trainingLabel1 = trainingLabelbie,g=c(150,100,100),out_dir_base = sub_dir)
assign_easy_multi(trainingData = trainire,test=c_test,trainingLabel1 = trainingLabelire,g=c(75,100,250),out_dir_base = sub_dir)


########################trying four at a time#####################
#1. AKT, BAD, HER2 & IGF1R
trainabhi<-cbind(c_gfp,c_akt,c_bad,c_her2,c_igf1r)
trainingLabelabhi<-list(control=list(akt=1:12,bad=1:12,her2=1:12,igf1r=1:12),akt=13:18, bad=19:24,her2=25:29,igf1r=30:35)
sub_dir=paste(basedir,"akt_bad_her2_igf1r",sep='/')
dir.create(sub_dir)
assign_easy_multi(trainingData = trainabhi,test=c_test,trainingLabel1 = trainingLabelabhi,g=c(150,150,15,100),out_dir_base = sub_dir)

#2. AKT, BAD, HER2 & ERK
trainabhe<-cbind(c_gfp,c_akt,c_bad,c_her2,c_erk)
trainingLabelabhe<-list(control=list(akt=1:12,bad=1:12,her2=1:12,erk=1:12),akt=13:18, bad=19:24,her2=25:29,erk=30:35)
sub_dir=paste(basedir,"akt_bad_her2_erk",sep='/')
dir.create(sub_dir)
assign_easy_multi(trainingData = trainabhe,test=c_test,trainingLabel1 = trainingLabelabhe,g=c(150,150,15,100),out_dir_base = sub_dir)

#3. AKT, BAD, IGF1R & ERK
trainabie<-cbind(c_gfp,c_akt,c_bad,c_igf1r,c_erk)
trainingLabelabie<-list(control=list(akt=1:12,bad=1:12,igf1r=1:12,erk=1:12),akt=13:18, bad=19:24,igf1r=25:30,erk=31:36)
sub_dir=paste(basedir,"akt_bad_igf1r_erk",sep='/')
dir.create(sub_dir)
assign_easy_multi(trainingData = trainabie,test=c_test,trainingLabel1 = trainingLabelabie,g=c(150,150,100,100),out_dir_base = sub_dir)

#4. AKT, IGF1R, HER2 & ERK
trainaihe<-cbind(c_gfp,c_akt,c_igf1r,c_her2,c_erk)
#trainingLabelabie<-list(control=list(akt=1:12,bad=1:12,igf1r=1:12,erk=1:12),akt=13:18, bad=19:24,igf1r=25:30,erk=31:36)

trainingLabelaihe<-list(control=list(akt=1:12,igf1r=1:12,her2=1:12,erk=1:12),akt=13:18, igf1r=19:24,her2=25:29,erk=30:35)
sub_dir=paste(basedir,"akt_igf1r_her2_erk",sep='/')
dir.create(sub_dir)
assign_easy_multi(trainingData = trainaihe,test=c_test,trainingLabel1 = trainingLabelaihe,g=c(150,100,15,100),out_dir_base = sub_dir)

#5. BAD, IGF1R, HER2 & ERK
trainbihe<-cbind(c_gfp,c_bad,c_igf1r,c_her2,c_erk)
trainingLabelbihe<-list(control=list(bad=1:12,igf1r=1:12,her2=1:12,erk=1:12),bad=13:18, igf1r=19:24,her2=25:29,erk=30:35)
sub_dir=paste(basedir,"bad_igf1r_her2_erk",sep='/')
dir.create(sub_dir)
assign_easy_multi(trainingData = trainbihe,test=c_test,trainingLabel1 = trainingLabelbihe,g=c(150,100,15,100),out_dir_base = sub_dir)

#6. "AKT"  "BAD"  "HER2" "RAF1"
trainabhr<-cbind(c_gfp,c_akt,c_bad,c_her2,c_raf)
trainingLabelabhr<-list(control=list(akt=1:12,bad=1:12,her2=1:12,raf=1:12),akt=13:18, bad=19:24,her2=25:29,raf=30:35)
sub_dir=paste(basedir,"akt_bad_her2_raf",sep='/')
dir.create(sub_dir)
assign_easy_multi(trainingData = trainabhr,test=c_test,trainingLabel1 = trainingLabelabhr,g=c(75,200,15,100),out_dir_base = sub_dir)

#7. "AKT"   "BAD"   "IGF1R" "RAF1" 
trainabir<-cbind(c_gfp,c_akt,c_bad,c_igf1r,c_raf)
trainingLabelabir<-list(control=list(akt=1:12,bad=1:12,igf1r=1:12,raf=1:12),akt=13:18, bad=19:24,igf1r=25:30,raf=31:36)
sub_dir=paste(basedir,"akt_bad_igf1r_raf",sep='/')
dir.create(sub_dir)
assign_easy_multi(trainingData = trainabir,test=c_test,trainingLabel1 = trainingLabelabir,g=c(75,200,75,100),out_dir_base = sub_dir)

#8. "AKT"  "BAD"  "RAF1" "ERK" 
trainabre<-cbind(c_gfp,c_akt,c_bad,c_raf,c_erk)
trainingLabelabre<-list(control=list(akt=1:12,bad=1:12,raf=1:12,erk=1:12),akt=13:18, bad=19:24,raf=25:30,erk=31:36)
sub_dir=paste(basedir,"akt_bad_raf_erk",sep='/')
dir.create(sub_dir)
assign_easy_multi(trainingData = trainabre,test=c_test,trainingLabel1 = trainingLabelabre,g=c(75,200,100,250),out_dir_base = sub_dir)

#9. "AKT" "RAF1" "HER2" "ERK"
trainarhe<-cbind(c_gfp,c_akt,c_raf,c_her2,c_erk)
trainingLabelarhe<-list(control=list(akt=1:12,raf=1:12,her2=1:12,erk=1:12),akt=13:18, raf=19:24,her2=25:29,erk=30:35)
sub_dir=paste(basedir,"akt_raf_her2_erk",sep='/')
dir.create(sub_dir)
assign_easy_multi(trainingData = trainarhe,test=c_test,trainingLabel1 = trainingLabelarhe,g=c(75,100,15,250),out_dir_base = sub_dir)

#10. "AKT" "IGF1R" "HER2" "RAF1"
trainaihr<-cbind(c_gfp,c_akt,c_igf1r,c_her2,c_raf)
trainingLabelaihr<-list(control=list(akt=1:12,igf1r=1:12,her2=1:12,raf=1:12),akt=13:18, igf1r=19:24,her2=25:29,raf=30:35)
sub_dir=paste(basedir,"akt_igf1r_her2_raf",sep='/')
dir.create(sub_dir)
assign_easy_multi(trainingData = trainaihr,test=c_test,trainingLabel1 = trainingLabelaihr,g=c(75,75,15,100),out_dir_base = sub_dir)

#11. "AKT"   "IGF1R" "RAF1"  "ERK"  
trainaire<-cbind(c_gfp,c_akt,c_igf1r,c_raf,c_erk)
trainingLabelaire<-list(control=list(akt=1:12,igf1r=1:12,raf=1:12,erk=1:12),akt=13:18, igf1r=19:24,raf=25:30,erk=31:36)
sub_dir=paste(basedir,"akt_igf1r_raf_erk",sep='/')
dir.create(sub_dir)
assign_easy_multi(trainingData = trainaire,test=c_test,trainingLabel1 = trainingLabelaire,g=c(75,75,100,250),out_dir_base = sub_dir)


#12. "BAD"  "IGF1R" "HER2" "RAF1" 
trainbihr<-cbind(c_gfp,c_bad,c_igf1r,c_her2,c_raf)
trainingLabelbihr<-list(control=list(bad=1:12,igf1r=1:12,her2=1:12,raf=1:12),bad=13:18, igf1r=19:24,her2=25:29,raf=30:35)
sub_dir=paste(basedir,"bad_igf1r_her2_raf",sep='/')
dir.create(sub_dir)
assign_easy_multi(trainingData = trainbihr,test=c_test,trainingLabel1 = trainingLabelbihr,g=c(200,75,15,100),out_dir_base = sub_dir)

#13. "BAD"  "RAF1" "HER2""ERK" 
trainbrhe<-cbind(c_gfp,c_bad,c_raf,c_her2,c_erk)
trainingLabelbrhe<-list(control=list(bad=1:12,raf=1:12,her2=1:12,erk=1:12),bad=13:18, raf=19:24,her2=25:29,erk=30:35)
sub_dir=paste(basedir,"bad_raf_her2_erk",sep='/')
dir.create(sub_dir)
assign_easy_multi(trainingData = trainbrhe,test=c_test,trainingLabel1 = trainingLabelbrhe,g=c(200,100,15,250),out_dir_base = sub_dir)

#14. "BAD" "IGF1R" "RAF1"  "ERK"  
trainbire<-cbind(c_gfp,c_bad,c_igf1r,c_raf,c_erk)
trainingLabelbire<-list(control=list(bad=1:12,igf1r=1:12,raf=1:12,erk=1:12),bad=13:18, igf1r=19:24,raf=25:30,erk=31:36)
sub_dir=paste(basedir,"bad_igf1r_raf_erk",sep='/')
dir.create(sub_dir)
assign_easy_multi(trainingData = trainbire,test=c_test,trainingLabel1 = trainingLabelbire,g=c(200,75,100,250),out_dir_base = sub_dir)

#15. "IGF1R" "RAF1" "HER2" "ERK"  
trainirhe<-cbind(c_gfp,c_igf1r,c_raf,c_her2,c_erk)
trainingLabelirhe<-list(control=list(igf1r=1:12,raf=1:12,her2=1:12,erk=1:12),igf1r=13:18, raf=19:24,her2=25:29,erk=30:35)
sub_dir=paste(basedir,"igf1r_raf_her2_erk",sep='/')
dir.create(sub_dir)
assign_easy_multi(trainingData = trainirhe,test=c_test,trainingLabel1 = trainingLabelirhe,g=c(75,100,15,250),out_dir_base = sub_dir)
#########including 5 pathways at a time######
#1. "AKT"   "BAD"   "HER2"  "IGF1R" "ERK"  

trainhall5<-cbind(c_gfp,c_akt,c_bad,c_her2,c_igf1r, c_erk)
trainingLabelall5<-list(control=list(akt=1:12,bad=1:12,her2=1:12,igf1r=1:12, erk=1:12),akt=13:18, bad=19:24,her2=25:29,igf1r=30:35, erk=36:41)
sub_dir=paste(basedir,"akt_bad_her2_igf1r_erk",sep='/')
dir.create(sub_dir)
assign_easy_multi(trainingData = trainhall5,test=c_test,trainingLabel1 = trainingLabelall5,g=c(75,200,15,100,250),out_dir_base = sub_dir)

#2. "AKT"   "BAD"   "HER2"  "IGF1R" "RAF1" 
trainhall5<-cbind(c_gfp,c_akt,c_bad,c_her2,c_igf1r, c_raf)
trainingLabelall5<-list(control=list(akt=1:12,bad=1:12,her2=1:12,igf1r=1:12, raf=1:12),akt=13:18, bad=19:24,her2=25:29,igf1r=30:35, raf=36:41)
sub_dir=paste(basedir,"akt_bad_her2_igf1r_raf",sep='/')
dir.create(sub_dir)
assign_easy_multi(trainingData = trainhall5,test=c_test,trainingLabel1 = trainingLabelall5,g=c(75,200,15,75,100),out_dir_base = sub_dir)

#3. "AKT"  "BAD"  "HER2" "RAF1" "ERK" 
trainhall5<-cbind(c_gfp,c_akt,c_bad,c_her2,c_raf,c_erk)
trainingLabelall5<-list(control=list(akt=1:12,bad=1:12,her2=1:12,raf=1:12,erk=1:12),akt=13:18, bad=19:24,her2=25:29,raf=30:35, erk=36:41)
sub_dir=paste(basedir,"akt_bad_her2_raf_erk",sep='/')
dir.create(sub_dir)
assign_easy_multi(trainingData = trainhall5,test=c_test,trainingLabel1 = trainingLabelall5,g=c(75,200,15,100,250),out_dir_base = sub_dir)

#4. "AKT"   "BAD"   "IGF1R" "RAF1"  "ERK"  
trainhall5<-cbind(c_gfp,c_akt,c_bad,c_igf1r,c_raf,c_erk)
trainingLabelall5<-list(control=list(akt=1:12,bad=1:12,igf1r=1:12,raf=1:12,erk=1:12),akt=13:18, bad=19:24,iigf1r=25:30,raf=31:36, erk=37:42)
sub_dir=paste(basedir,"akt_bad_igf1r_raf_erk",sep='/')
dir.create(sub_dir)
assign_easy_multi(trainingData = trainhall5,test=c_test,trainingLabel1 = trainingLabelall5,g=c(75,200,75,100,250),out_dir_base = sub_dir)

#5. "AKT" "IGF1R" "HER2" "RAF1"  "ERK"  
trainhall5<-cbind(c_gfp,c_akt,c_igf1r,c_her2,c_raf,c_erk)
trainingLabelall5<-list(control=list(akt=1:12,igf1r=1:12,her2=1:12,raf=1:12,erk=1:12),akt=13:18, igf1r=19:24,her2=25:29,raf=30:35, erk=36:41)
sub_dir=paste(basedir,"akt_igf1r_her2_raf_erk",sep='/')
dir.create(sub_dir)
assign_easy_multi(trainingData = trainhall5,test=c_test,trainingLabel1 = trainingLabelall5,g=c(75,75,15,100,250),out_dir_base = sub_dir)

#6. "BAD"   "IGF1R" "HER2" "RAF1"  "ERK" 
trainhall5<-cbind(c_gfp,c_bad,c_igf1r,c_her2,c_raf,c_erk)
trainingLabelall5<-list(control=list(bad=1:12,igf1r=1:12,her2=1:12,raf=1:12,erk=1:12),bad=13:18, igf1r=19:24,her2=25:29,raf=30:35, erk=36:41)
sub_dir=paste(basedir,"bad_igf1r_her2_raf_erk",sep='/')
dir.create(sub_dir)
assign_easy_multi(trainingData = trainhall5,test=c_test,trainingLabel1 = trainingLabelall5,g=c(200,75,15,100,250),out_dir_base = sub_dir)

#########including 6 pathways at a time######

trainhall6<-cbind(c_gfp,c_akt,c_bad,c_igf1r,c_her2,c_raf,c_erk)
trainingLabelall6<-list(control=list(akt=1:12,bad=1:12,igf1r=1:12,her2=1:12,raf=1:12,erk=1:12),akt=13:18, bad=19:24,igf1r=25:30,her2=31:35, raf=36:41,erk=42:47)
sub_dir=paste(basedir,"akt_bad_igf1r_her2_raf_erk",sep='/')
dir.create(sub_dir)
assign_easy_multi(trainingData = trainhall6,test=c_test,trainingLabel1 = trainingLabelall6,g=c(75,200,75,15,100,250),out_dir_base = sub_dir)

# ##########
# #########including all 7 (36 hour GFP+ EGFR(Laurie's signature)) pathways######
setwd("~/Dropbox/egfr_opt/")
gfp <- read.table("36hr_gfp_TPMlog.txt",header = 1, row.names=1)
dim(gfp)
egfr<- read.table("36hr_EGFR_train_TPMlog.txt",header = 1, row.names=1)
dim(egfr)
gfp_egfr_36<-cbind(gfp,egfr)

gfp_egfr_36,

icbp<-read.table("icbp_Rsubread_tpmlog.txt", sep='\t', header=1, row.names=1)
dim(icbp)
# expr_all<-merge_drop(expr,cbind(gfp,egfr))
# expr_all_f <-expr_all[apply(expr_all[,1:65]==0,1,mean) < 0.85,]
# dim(expr_all_f)
# expr_all_icbp_f<-merge_drop(expr_all_f,icbp,by=0)
# sub<-c(12,6,6,5,6,6,6,9,9,55)
# pcaplot(expr_all_icbp_f,sub)
# bat1<-as.matrix(cbind(c(colnames(expr_all_f),colnames(icbp)),c(rep(1,47),rep(2,18),rep(3,55))))
# combat_expr1<-ComBat(dat=expr_all_icbp_f, batch=bat1[,2], mod=NULL, numCovs=NULL)
# pcaplot(combat_expr1,sub)
# colnames(combat_expr1)
# c_gfp36<-subset(combat_expr1, select=48:56)
# c_egfr<-subset(combat_expr1, select=EGFR.1:EGFR.9)
# c_test<-combat_expr1[,66:120]
# c_gfp<-subset(combat_expr1, select=GFP.1:GFP.12)
# c_akt<-subset(combat_expr1, select=AKT.1:AKT.6)
# c_bad<-subset(combat_expr1, select=BAD.1:BAD.6)
# c_her2<-subset(combat_expr1, select=HER2.1:HER2.6)
# c_igf1r<-subset(combat_expr1, select=IGF1R.1:IGF1R.6)
# c_raf<-subset(combat_expr1, select=RAF.1:RAF.6)
# c_erk<-subset(combat_expr1, select=ERK.1:ERK.6)
# 
# 
# 
# 
# trainingLabelall5<-list(control=list(akt=1:12,bad=1:12,her2=1:12,erk=1:12,igf1r=1:12, raf=1:12, egfr=48:65),akt=13:18, bad=19:24,her2=25:29,erk=30:35, igf1r=36:41,raf=42:47,egfr=57:65)
# sub_dir=paste(basedir,"akt_bad_her2_erk_igf1r_raf_egfr",sep='/')
# dir.create(sub_dir)
# assign_easy_multi(trainingData = trainhall5,test=c_test,trainingLabel1 = trainingLabelall5,g=c(150,150,15,100,100,150,25),out_dir_base = sub_dir)

```


```{r}
# expr_all<-merge_drop(expr,cbind(control_l,egfr_l))
# expr_all_f <-expr_all[apply(expr_all[,1:ncol(expr_all)]==0,1,mean) < 0.85,]
# dim(expr_all_f)
# expr_all_icbp_f<-merge_drop(expr_all_f,icbp,by=0)
# sub<-c(12,6,6,5,6,6,6,6,6,55)
# pcaplot(expr_all_icbp_f,sub)
# bat1<-as.matrix(cbind(c(colnames(expr_all_f),colnames(icbp)),c(rep(1,47),rep(2,12),rep(3,55))))
# combat_expr1<-ComBat(dat=expr_all_icbp_f, batch=bat1[,2], mod=NULL, numCovs=NULL)
# pcaplot(combat_expr1,sub)
# colnames(combat_expr1)
# c_gfp_l<-subset(combat_expr1, select=48:53)
# c_egfr_l<-subset(combat_expr1, select=54:59)
# c_test<-combat_expr1[,48:ncol(combat_expr1)]
# c_gfp<-subset(combat_expr1, select=GFP.1:GFP.12)
# c_akt<-subset(combat_expr1, select=AKT.1:AKT.6)
# c_bad<-subset(combat_expr1, select=BAD.1:BAD.6)
# c_her2<-subset(combat_expr1, select=HER2.1:HER2.6)
# c_igf1r<-subset(combat_expr1, select=IGF1R.1:IGF1R.6)
# c_raf<-subset(combat_expr1, select=RAF.1:RAF.6)
# c_erk<-subset(combat_expr1, select=ERK.1:ERK.6)
# 
# trainingLabelall5<-list(control=list(akt=1:12,bad=1:12,her2=1:12,erk=1:12,igf1r=1:12, raf=1:12, egfr=48:53),akt=13:18, bad=19:24,her2=25:29,erk=30:35, igf1r=36:41,raf=42:47,egfr=54:59)
# sub_dir=paste(basedir,"akt_bad_her2_erk_igf1r_raf_egfr_l",sep='/')
# dir.create(sub_dir)
# assign_easy_multi(trainingData = trainhall5,test=c_test,trainingLabel1 = trainingLabelall5,g=c(150,150,15,100,100,150,25),out_dir_base = sub_dir)
# pred_7_l<-read.csv("~/Dropbox/bild_signatures/icbp_15_april_assign_adap_/akt_bad_her2_erk_igf1r_raf_egfr_l/adap_adap_multi/pathway_activity_testset.csv",header=1,row.names=1)

# filenames_icbp_multi<-system("ls *gene_list/*/pathway_activity_testset*", intern=TRUE)
# filenames_icbp_multi
# 
# for(i in 1:length(filenames_icbp_multi))
#   {
#    f<-read.csv(filenames_icbp_multi[i], header=1,row.names=1) ###reading in the filess one at a time
#    colnames(f)<-paste(filenames_icbp_multi[i],colnames(f),sep='/')
#    if(i==1){
#      data_icbp<-f
#      }
#    else{
#      data_icbp<-cbind(data_icbp,f)
#     }
#   }
# 
# head(data_icbp)
# dim(data_icbp)
# colnames(data_icbp)<-gsub(pattern = "/pathway_activity_testset.csv",replacement = "",x = colnames(data_icbp))
# head(data_icbp)
# rownames(data_icbp)[1:7]<-c("184A1","184B5","21MT1","21MT2","21NT","21PT","600MPE")
# 
# drugs<-read.delim("~/Dropbox/bild_signatures/Datasets/ICBP_drugs.txt", header=1,row.names=1)
# head(drugs);dim(drugs)
# pred_drug<-merge_drop(data_icbp,drugs,by=0)
# dim(pred_drug)
# rownames(pred_7_l)[1:7]<-c("184A1","184B5","21MT1","21MT2","21NT","21PT","600MPE")
# pred_drug_l<-merge_drop(pred_7_l,drugs)
# colnames(pred_drug_l)
# cor_mat=p_mat=matrix(0,length(filenames_icbp_multi),90)
# rownames(cor_mat)=rownames(p_mat)=colnames(pred_drug)[1:length(filenames_icbp_multi)]
# colnames(cor_mat)=colnames(p_mat)=colnames(pred_drug)[(length(filenames_icbp_multi)+11):ncol(pred_drug)]
# 
# for(i in 1:38){
#   for(j in 1:90){
#   temp=cor.test(pred_drug[,i],pred_drug[,j+48],use="pairwise",method="spearman")
#   print(j)
#   print(temp)
#   cor_mat[i,j]=temp$estimate
#   p_mat[i,j]=temp$p.value
#   }
# }
# write.table(cor_mat,"single_cor_p_mat.txt",col.names = NA,quote=F,sep='\t')
# colnames(p_mat)=paste(colnames(p_mat),"p_value",sep="_")
# cor_p_mat<-cbind(cor_mat,p_mat)
# order(colnames(cor_p_mat))
# cor_p_mat<-cor_p_mat[,order(colnames(cor_p_mat))]
# write.table(cor_p_mat,"multi_l_cor_p_mat.txt",col.names = NA,quote=F,sep='\t')
```


Read in all the predictions are make files with all results 
```{r, echo=TRUE}
# multi nonadpative 
#setwd("~/Documents/Thesiswork/ICBP/multi_icbp_expr_pc/")
source('~/Dropbox/bild_signatures/bild_signatures/Rmarkdowns_scripts//Key_ASSIGN_functions.Rmd', echo=TRUE)
setwd("~/Dropbox/bild_signatures/icbp_15_april_assign_adap_/")
setwd("~/Dropbox/bild_signatures/icbp_15_april_assign_adap_/single/")
filenames<-system("ls */*/pathway_activity_testset*", intern=TRUE)
filenames<-system("ls *_gene_list/*/pathway_activity_testset*", intern=TRUE)

filenames
data_icbp=NULL
for(i in 1:length(filenames))
  {
   f<-read.csv(filenames[i], header=1,row.names=1) ###reading in the filess one at a time
   colnames(f)<-paste(filenames[i],colnames(f),sep='/')
   if(i==1){
     data_icbp<-f
     }
   else{
     data_icbp<-cbind(data_icbp,f)
     print(i)
    }
  }

head(data_icbp)
dim(data_icbp)
colnames(data_icbp)<-gsub(pattern = "/pathway_activity_testset.csv",replacement = "",x = colnames(data_icbp))
head(data_icbp)
rownames(data_icbp)[1:7]<-c("184A1","184B5","21MT1","21MT2","21NT","21PT","600MPE")

drugs<-read.delim("~/Dropbox/bild_signatures/Datasets/ICBP_drugs.txt", header=1,row.names=1)
head(drugs);dim(drugs)
pred_drug<-merge_drop(data_icbp,drugs,by=0)
write.table(pred_drug[,c(1:130,141:230)],"~/Dropbox/bild_signatures/bild_signatures/Datasets/pred_130_drug_90.txt",sep='\t',col.names=NA,quote=F)
write.table(pred_drug[,c(1:380,391:480)],"~/Dropbox/bild_signatures/bild_signatures/Datasets/pred_380_drug_90.txt",sep='\t',col.names=NA,quote=F)


dim(pred_drug)
#best_pathway_predictions=apply(subset(pred_drug,select=c(133,147,154,160,150)),2,scale)
#rownames(best_pathway_predictions)<-rownames(pred_drug)
single_pathway_best<-data_icbp[,c("akt_75_gene_list/adap_adap_single/akt","her2_25_gene_list/adap_adap_single/her2","igf1r_75_gene_list/adap_adap_single/igf1r","bad_200_gene_list/adap_adap_single/bad","erk_200_gene_list/adap_adap_single/erk","raf_100_gene_list/adap_adap_single/raf","egfr_25_gene_list/adap_adap_single/egfr")]
best_pathway_predictions<-pred_drug[,c("akt_75_gene_list/adap_adap_single/akt","her2_25_gene_list/adap_adap_single/her2","igf1r_75_gene_list/adap_adap_single/igf1r","bad_200_gene_list/adap_adap_single/bad","erk_200_gene_list/adap_adap_single/erk","raf_100_gene_list/adap_adap_single/raf","egfr_25_gene_list/adap_adap_single/egfr")]
#########this subtype analysis is the transcriptional subtype + HER2 status based.#########
colnames(single_pathway_best)<-gsub(".*_gene_list/adap_adap_single/","",colnames(single_pathway_best))
colnames(best_pathway_predictions)<-gsub(".*_gene_list/adap_adap_single/","",colnames(best_pathway_predictions))
best_pathway_predictions<-best_pathway_predictions[,order(colnames(best_pathway_predictions))]
single_w_o_erk<-single_pathway_best[,c(1:4,6:7)]
x  <- as.matrix(cor(single_pathway_best))
x2  <- as.matrix(cor(single_w_o_erk))
#rc <- rainbow(nrow(x), start = 0, end = .3)
#cc <- rainbow(ncol(x), start = 0, end = .3)
heatmap(x, col = , margins = c(5,5),xlab = "Pathway predictions", ylab =  "Pathway predictions",main = "Pearson's correlation \namong the pathway predictions")
my_palette <- colorRampPalette(c("darkblue","aliceblue","brown3"))(n = 299)


prediction_heatmap<-function(x,type=NULL)
{
  require(gplots)
  heatmap.2(as.matrix(x),col=my_palette,margins=c(9,9),Rowv = NULL, Colv = NULL, cexCol = 1,cexRow = 1,trace="none",main=paste(type,"",sep = "\n"),density.info = 'none',scale = 'row')#,cellnote = round(x,digits = 2),notecol = 'black')
  
}
prediction_heatmap(x,type = "Pathway correlations in\n ICBP breast cell lines")
prediction_heatmap(x2,type = "Pathway correlations in\n ICBP breast cell lines")




subtype_her2<-pred_drug$Transcriptional.subtype...ERBB2.status
subtype_her2=gsub("ERBB2.*","ERBB2",subtype_her2)
subtype_her2=gsub("Basal.*","BASAL",subtype_her2)
subtype_her2=gsub("Luminal.*","LUMINAL",subtype_her2)
subtype_her2=gsub(".*ormal.*","NORMAL",subtype_her2)

par(mfrow = c(2,1),mar=c(3,5,3, 0.5),lwd=4)
#pdf("~/Dropbox/bild_signatures/bild_signatures/Results/ICBP_predictions.pdf")
#min(best_pathway_predictions)
boxplot(scale(best_pathway_predictions$akt)~subtype_her2,main="AKT across breast cell lines",col=2:6,ylim=c(-2.5,2), ylab="Scaled pathway activity")
boxplot(scale(best_pathway_predictions$bad)~subtype_her2,main="BAD across breast cell lines",col=2:6,ylim=c(-2.5,2),ylab="Scaled pathway activity")
boxplot(pred_drug[,18]~subtype_her2,main="BAD across breast cell lines",col=2:5,ylim=c(-2.5,2),ylab="Scaled pathway activity")

boxplot(best_pathway_predictions[,3]~subtype_her2,main="IGF1R across breast cell lines",col=2:5,ylim=c(-2.5,2))
boxplot(best_pathway_predictions[,4]~subtype_her2,main="ERK across breast cell lines",col=2:5,ylim=c(-2.5,2))
boxplot(best_pathway_predictions[,5]~subtype_her2,main="HER2(2) across breast cell lines",col=2:5,ylim=c(-2.5,2))





cor_mat=p_mat=matrix(0,ncol(data_icbp),90)
rownames(cor_mat)=rownames(p_mat)=colnames(pred_drug)[1:ncol(data_icbp)]
colnames(cor_mat)=colnames(p_mat)=colnames(pred_drug)[(ncol(data_icbp)+11):ncol(pred_drug)]

for(i in 1:ncol(data_icbp)){
  for(j in 1:90){
  temp=cor.test(pred_drug[,i],pred_drug[,(j+ncol(data_icbp)+10)],use="pairwise",method="spearman")
  print(j)
  print(temp)
  cor_mat[i,j]=temp$estimate
  p_mat[i,j]=temp$p.value
  }
}
write.table(cor_mat,"Multi_single_cor_drug_mat_4_30.txt",col.names = NA,quote=F,sep='\t')
colnames(p_mat)=paste(colnames(p_mat),"p_value",sep="_")
write.table(p_mat,"Multi_single_p_drug_mat_4_30.txt",col.names = NA,quote=F,sep='\t')
cor_p_mat<-cbind(cor_mat,p_mat)
order(colnames(cor_p_mat))
cor_p_mat<-cor_p_mat[,order(colnames(cor_p_mat))]
write.table(cor_p_mat,"Multi_single_cor_p_mat_4_30.txt",col.names = NA,quote=F,sep='\t')
meki<-read.table("~/Dropbox/Datasets/mek_inhibitors_gray.txt",header=1,row.names=1,sep='\t')
pred_meki<-merge_drop(data_icbp,meki)


```


Now,combining predictions and proteomics data
```{r}
prot<-read.table("~/Dropbox/bild_signatures/bild_signatures/Datasets/proteomics.txt",sep='\t',header=1,row.names=1)
pred_prot<-merge_drop(data_icbp,prot)
write.table(pred_prot,"~/Dropbox/bild_signatures/bild_signatures/Datasets/pred_130_prot_70.txt",sep='\t',col.names=NA,quote=F)
write.table(pred_prot,"~/Dropbox/bild_signatures/bild_signatures/Datasets/pred_380_prot_70.txt",sep='\t',col.names=NA,quote=F)



cor_mat=p_mat=matrix(0,ncol(data_icbp),70)
rownames(cor_mat)=rownames(p_mat)=colnames(pred_prot)[1:ncol(data_icbp)]
colnames(cor_mat)=colnames(p_mat)=colnames(pred_prot)[(ncol(data_icbp)+1):ncol(pred_prot)]

for(i in 1:ncol(data_icbp)){
  for(j in 1:70){
  temp=cor.test(pred_prot[,i],pred_prot[,j+ncol(data_icbp)],use="pairwise",method="spearman")
  print(j)
  print(temp)
  cor_mat[i,j]=temp$estimate
  p_mat[i,j]=temp$p.value
  }
}
colnames(p_mat)=paste(colnames(p_mat),"p_value",sep="_")
cor_p_mat<-cbind(cor_mat,p_mat)
order(colnames(cor_p_mat))
cor_p_mat<-cor_p_mat[,order(colnames(cor_p_mat))]
write.table(cor_mat,"Multi_single_protein_cor_mat_4_30.txt",col.names = NA,quote=F,sep='\t')
write.table(p_mat,"Multi_single_protein_p_mat_4_30.txt",col.names = NA,quote=F,sep='\t')
write.table(cor_p_mat,"Multi_single_protein_cor_p_mat_4_30.txt",col.names = NA,quote=F,sep='\t')
```
Identifying the best single and multipathway predictions

```{r}
single_pathway_best<-c("akt_75_gene_list/adap_adap_single/akt","bad_200_gene_list/adap_adap_single/bad","her2_25_gene_list/adap_adap_single/her2","igf1r_75_gene_list/adap_adap_single/igf1r","erk_200_gene_list/adap_adap_single/erk","raf_100_gene_list/adap_adap_single/raf","egfr_25_gene_list/adap_adap_single/egfr")
multi_pathway_best<-c("akt_bad_her2_raf/adap_adap_multi/akt","akt_bad_her2_erk/adap_adap_multi/bad","her2_igf1r/adap_adap_multi/her2","igf1r_raf_her2_erk/adap_adap_multi/igf1r","erk_bad/adap_adap_multi/erk","akt_bad_igf1r_raf/adapB_multi/raf")
```



Creating heatmaps
```{r }

if (!require("gplots")) {
   install.packages("gplots", dependencies = TRUE)
   library(gplots)
   }
if (!require("RColorBrewer")) {
   install.packages("RColorBrewer", dependencies = TRUE)
   library(RColorBrewer)
   }
multi<-data#read.table("~/Desktop/multipathway_preds.txt", sep='\t',row.names=1,header=1)
single<-read.csv("~/Dropbox/bild_signatures/multi_icbp_expr_pc/single_pathway_results.csv", row.names=1,header=1)
my_palette <- colorRampPalette(c("darkblue","aliceblue","brown4"))(n = 299)
col_breaks = c(seq(0,0.2,length=100), seq(0.2,0.4,length=100), seq(0.4,1,length=100)) 
# creates a 5 x 5 inch image
png("heatmaps_in_r.png",    # create PNG for the heat map        
  width = 5*300,        # 5 x 300 pixels
  height = 5*300,
  res = 300,            # 300 pixels per inch
  pointsize = 8)  
comb<-cbind(multi,single)
dim(comb)
colnames(comb)<-gsub(pattern = "adap_multi.pathway_activity_testset.csv",replacement = "A",x = colnames(comb))
#colnames(comb)<-gsub(pattern = "non",replacement = "NA",x = colnames(comb))
pdf(file='~/Dropbox/bild_signatures//bild_signatures/activity_subtype.pdf')

heatmap.2(as.matrix(comb),col=my_palette,margins=c(12,9),Rowv=F,Colv=F,dendrogram="none", trace="none",main="All possibilities",breaks = col_breaks)
heatmap.2(as.matrix(comb[,47:50]),col=my_palette,trace="none",main="Multipathway activity",margins=c(12,9),Rowv =F,Colv=F,dendrogram="none",ylab="ICBP Cell lines",breaks = col_breaks)
heatmap.2(as.matrix(comb[,51:54]),margins=c(12,9),col=my_palette, Rowv=F,Colv=F,dendrogram="none",trace="none",main="Single pathway activity",ylab="ICBP Cell lines",scale = "row")

comb_drug<-merge_drop(comb,drugs,by=0)
#plot(hclust(dist(comb_drug[,1:48]), method = "complete", members = NULL))


basal<-subset(comb_drug,comb_drug$Transcriptional.subtype...ERBB2.status=="Basal")
heatmap.2(as.matrix(basal[,22:25]),col=my_palette,margins=c(12,9),dendrogram="none", trace="none",main="Basal Multi")
heatmap.2(as.matrix(basal[,26:29]),col=my_palette,margins=c(12,9),dendrogram="none",lmat=rbind( c(0, 3, 4), c(2,1,0 ) ), lwid=c(1.5, 4, 2 ), trace="none",main="Basal single")
cor(basal[,22],basal$Sigma.AKT1.2.inhibitor,use="pairwise")

her<-subset(comb_drug[,1:44],comb_drug$Transcriptional.subtype...ERBB2.status=="ERBB2-amp"|comb_drug$Transcriptional.subtype...ERBB2.status=="ERBB2Amp")
heatmap.2(as.matrix(her[,22:25]),col=my_palette,dendrogram="none",lmat=rbind( c(0, 3, 4), c(2,1,0 ) ), lwid=c(1.5, 4, 2 ), trace="none",margins=c(12,9),main="HER2 Multi")
heatmap.2(as.matrix(her[,26:29]),col=my_palette,dendrogram="none",lmat=rbind( c(0, 3, 4), c(2,1,0 ) ), lwid=c(1.5, 4, 2 ), trace="none",margins=c(12,9),main="HER2 Single",scale="column")
cor(her[,22],her$Sigma.AKT1.2.inhibitor,use="pairwise")

claudin<-subset(comb_drug,comb_drug$Transcriptional.subtype...ERBB2.status=="Claudin-low")
heatmap.2(as.matrix(claudin[,22:25]),col=my_palette,dendrogram="none",lmat=rbind( c(0, 3, 4), c(2,1,0 ) ), lwid=c(1.5, 4, 2 ), trace="none",margins=c(12,9),main="Claudin Multi")
heatmap.2(as.matrix(claudin[,26:29]),col=my_palette,dendrogram="none",lmat=rbind( c(0, 3, 4), c(2,1,0 ) ), lwid=c(1.5, 4, 2 ), trace="none",margins=c(12,9),main="Claudin Single",scale="column")
cor(claudin[,22],claudin$Sigma.AKT1.2.inhibitor,use="na.or.complete")

luminal<-subset(comb_drug,comb_drug$Transcriptional.subtype...ERBB2.status=="Luminal")
heatmap.2(as.matrix(luminal[,22:25]),col=my_palette,dendrogram="none",lmat=rbind( c(0, 3, 4), c(2,1,0 ) ), lwid=c(1.5, 4, 2 ), trace="none",margins=c(12,9),main="Luminal Multi")
heatmap.2(as.matrix(luminal[,26:29]),col=my_palette,dendrogram="none",lmat=rbind( c(0, 3, 4), c(2,1,0 ) ), lwid=c(1.5, 4, 2 ), trace="none",margins=c(12,9),main="Luminal Single",scale="row")
=======
# write(file="~/Dropbox/bild_signatures/bild_signatures/pathway prediction drug response results.xls","Correlations for pathway predictions with Lapatinib and Sigma.AKT.inhibitor in BASAL subtype",append = T)
# write('',file="~/Dropbox/bild_signatures/bild_signatures/pathway prediction drug response results.xls", append=T)
basal<-subset(comb_drug,comb_drug$Transcriptional.subtype...ERBB2.status=="Basal")
# write("For Lapatinib",file="~/Dropbox/bild_signatures/bild_signatures/pathway prediction drug response results.xls", append =T)
# write(paste(colnames(basal)[1:54],cor(basal[,1:54],basal$Lapatinib,use="pairwise.complete.obs"),sep='\t'), file="~/Dropbox/bild_signatures/bild_signatures/pathway prediction drug response results.xls", append = T)
# write("For Sigma AKT inhibitor",file="~/Dropbox/bild_signatures/bild_signatures/pathway prediction drug response results.xls", append =T)
# write(paste(colnames(basal)[1:54],cor(basal[,1:54],basal$Sigma.AKT1.2.inhibitor,use="pairwise.complete.obs"),sep='\t'),file="~/Dropbox/bild_signatures/bild_signatures/pathway prediction drug response results.xls",append = T)

par(mfrow = c(2,1))
heatmap.2(as.matrix(basal[,47:50]),col=my_palette,margins=c(12,9),dendrogram="none", trace="none",main="Basal Multi",Rowv = NULL, Colv = NULL)
heatmap.2(as.matrix(basal[,51:54]),col=my_palette,margins=c(12,9),dendrogram="none",Rowv = NULL, Colv = NULL, trace="none",main="Basal single")


her<-subset(comb_drug,comb_drug$Transcriptional.subtype...ERBB2.status=="ERBB2-amp"|comb_drug$Transcriptional.subtype...ERBB2.status=="ERBB2Amp")
# wrtie(paste(colnames(her)[1:54],cor(her[,1:54],her$Lapatinib,use="pairwise.complete.obs"),sep='\t'),file="~/Dropbox/bild_signatures/bild_signatures/pathway prediction drug response results.xls",append = T)
# write("For Sigma AKT inhibitor",file="~/Dropbox/bild_signatures/bild_signatures/pathway prediction drug response results.xls", append =T)
# write(paste(colnames(her),cor(her[,1:54],her$Sigma.AKT1.2.inhibitor,use="pairwise.complete.obs"),sep='\t'),file="~/Dropbox/bild_signatures/bild_signatures/pathway prediction drug response results.xls",append = T)
# 

heatmap.2(as.matrix(her[,43:54]),col=my_palette,dendrogram="none",lmat=rbind( c(0, 3, 4), c(2,1,0 ) ), lwid=c(1.5, 4, 2 ), trace="none",margins=c(14,9),main="HER2 Multi",Rowv=F, Colv=F)
heatmap.2(as.matrix(her[,51:54]),col=my_palette,dendrogram="none",lmat=rbind( c(0, 3, 4), c(2,1,0 ) ), lwid=c(1.5, 4, 2 ), trace="none",margins=c(12,9),main="HER2 Single",Rowv=F, Colv=F,scale = "row")


claudin<-subset(comb_drug,comb_drug$Transcriptional.subtype...ERBB2.status=="Claudin-low")
cor(claudin[,1:54],claudin$Lapatinib,use="pairwise.complete.obs")# variance zero in this group
cor(claudin[,1:54],claudin$Sigma.AKT1.2.inhibitor,use="pairwise.complete.obs")

heatmap.2(as.matrix(claudin[,47:50]),col=my_palette,dendrogram="none",trace="none",margins=c(12,9),main="Claudin Multi",,Rowv=F, Colv=F)
heatmap.2(as.matrix(claudin[,51:54]),col=my_palette,dendrogram="none", trace="none",margins=c(12,9),main="Claudin Single",scale="row",,Rowv=F, Colv=F)
cor(claudin[,22],claudin$Sigma.AKT1.2.inhibitor,use="na.or.complete")

luminal<-subset(comb_drug,comb_drug$Transcriptional.subtype...ERBB2.status=="Luminal")
cor(luminal[,47:50],luminal$Lapatinib,use="pairwise.complete.obs")
cor(luminal[,51:54],luminal$Sigma.AKT1.2.inhibitor,use="pairwise.complete.obs")
heatmap.2(as.matrix(luminal[,47:50]),col=my_palette,dendrogram="none", trace="none",margins=c(12,9),main="Luminal Multi",Rowv=F, Colv=F)
heatmap.2(as.matrix(luminal[,47:50]),col=my_palette,dendrogram="none",trace="none",margins=c(12,9),main="Luminal Single",scale="row",Rowv=F, Colv=F)
>>>>>>> 2fac797b6fb95768996bf82bab2763ae0f043efa
cor(luminal[,22],luminal$Sigma.AKT1.2.inhibitor,use="na.or.complete")
multi_4<-rbind(basal[,43:46],her[,43:46],claudin[,43:46],luminal[,43:46])
png("heatmaps_multi_adap.png",width = 5*300,height = 5*300,res = 800, pointsize = 8)  
heatmap.2(as.matrix(multi_4), RowSideColors = c(rep("gray", length(rownames(basal))),rep("blue", length(rownames(her))),rep("black", length(rownames(claudin))),rep("green",length(rownames(luminal)))),col=my_palette,dendrogram="none", trace="none",margins=c(15,10),main="Multi Preds within Subtypes",scale="row",Rowv=F)
par(lend = 10)           # square line ends for the color legend
legend("topright",legend = c("Basal", "HER2", "Claudin","Luminal"), col = c("gray", "blue", "black","green"),  lty= 1,lwd = 10)
dev.off()
single_4<-rbind(basal[,51:54],her[,51:54],claudin[,51:54],luminal[,51:54])
heatmap.2(as.matrix(single_4), RowSideColors = c(rep("gray", length(rownames(basal))),rep("blue", length(rownames(her))),rep("black", length(rownames(claudin))),rep("green",length(rownames(luminal)))),col=my_palette,dendrogram="none", trace="none",margins=c(12,9),main="Single Preds within Subtypes",scale="row",Rowv=F)
par(lend = 10)           # square line ends for the color legend
legend("topright",legend = c("Basal", "HER2", "Claudin","Luminal"), col = c("gray", "blue", "black","green"),  lty= 1,lwd = 10)

dev.off()
```

```{r echo=FALSE}
time<-format(Sys.time(),"%a %b %d %X %Y")
```
This analysis was run on `r time` 
