---
title: "Pathway Predictions/Drug Response Correlations"
author: "Shelley"
date: "February 9, 2015"
output: html_document
---

Read in the single and multi-pathway ASSIGN predictions
```{r}
setwd("~/Documents/ThesisWork/GitRepos/bild_signatures")

drug_response_data<-read.delim("ICBP_drugs.txt", header=1, sep='\t',row.names=1)

multipathway_data<-read.delim("Results/ICBP/predictions/multipathway_preds.txt", header=1, sep='\t',row.names=1) 

singlepathway_data=read.csv("Results/ICBP/predictions/single_pathway_results.csv") 

row.names(singlepathway_data)=singlepathway_data[,1]
singlepathway_data=singlepathway_data[,-1]
```

Merge the pathway predictions and the ICBP drugs
```{r}

merge_drop<-function(x,y,by=0)
{
  new_m<-merge(x,y,by=by)
  rownames(new_m)<-new_m$Row.names
  return(new_m[,2:length(colnames(new_m))])
}

pred_drug_multi<-merge_drop(multipathway_data,drug_response_data,by=0)
pred_drug_single<-merge_drop(singlepathway_data,drug_response_data,by=0)

```

Perform correlations and bootstrap, save to file
```{r}
drug_prediction_correlations_multi_spear= cor(pred_drug_multi[1:25],pred_drug_multi[36:125],use="na.or.complete", method="spearman")

#### Bootstrap:
pathways = 25 # number of pathway signatures
samplesize = nrow(pred_drug_multi) # number of cell lines
n.boot = 10000 # number of bootstrap samples -- set at 10,000 or more for your final run

boot_cors = array(0,dim=c(25,90,n.boot)) # make a three dimensional array to store the bootstrap results

for (i in 1:n.boot){
  boot.sample = sample(1:samplesize,replace=T)
  boot_cors[,,i]=cor(pred_drug_multi[boot.sample,1:25],pred_drug_multi[boot.sample,36:125],use="na.or.complete")
  }

# means
cor_mean = apply(boot_cors, c(1,2), mean, na.rm=T)  ## average bootstrap cors. Should be similar to the non-boot values
dimnames(cor_mean)=dimnames(drug_prediction_correlations_multi_spear)
View(cor_mean)
write.table(cor_mean,"~/Documents/ThesisWork/GitRepos/bild_signatures/cor_mean.txt",sep='\t', col.names = NA,quote=F)
cor_means_ICBP=read.delim("~/Documents/ThesisWork/GitRepos/bild_signatures/cor_mean.txt", header=1, sep='\t',row.names=1)
#lower
lower = apply(boot_cors, c(1,2), quantile,na.rm=T,probs=.025) ## lower 95% CI
dimnames(lower)=dimnames(drug_prediction_correlations_multi_spear)
write.table(lower,"~/Documents/ThesisWork/GitRepos/bild_signatures/lower.txt",sep='\t', col.names = NA,quote=F)
cor_lower_ICBP=read.delim("~/Documents/ThesisWork/GitRepos/bild_signatures/lower.txt", header=1, sep='\t',row.names=1)
#upper
upper = apply(boot_cors, c(1,2), quantile,na.rm=T,probs=.975) ## upper 95% CI
dimnames(upper)=dimnames(drug_prediction_correlations_multi_spear)
write.table(upper,"~/Documents/ThesisWork/GitRepos/bild_signatures/upper.txt",sep='\t', col.names = NA,quote=F)
cor_upper_ICBP=read.delim("~/Documents/ThesisWork/GitRepos/bild_signatures/upper.txt", header=1, sep='\t',row.names=1)

```

Box plot the results using a for loop 
```{r}

#just a test
test =c(lower[1,1],cor_mean[1,1], upper[1,1])  ## print the upper, mean, lower for first pathway and first drug

# loop through

# Subset each signature from means, lower, and upper. 
AKT_means=cor_mean[c(1,3,6,9, 13, 22), ]
dim(AKT_means)
AKT_lower=lower[c(1,3,6,9, 13, 22), ]
AKT_upper=upper[c(1,3,6,9, 13, 22), ]

Her2_means=cor_mean[c(5,14,16,18, 21, 24), ]
dim(Her2_means)
Her2_lower=lower[c(5,14,16,18, 21, 24), ]
Her2_upper=upper[c(5,14,16,18, 21, 24), ]

IGFR_means=cor_mean[c(8,10,12,17, 19, 25), ]
dim(IGFR_means) #6
IGFR_lower=lower[c(8,10,12,17, 19, 25), ]
IGFR_upper=upper[c(8,10,12,17, 19, 25), ]

BAD_means=cor_mean[c(2,4,7,11, 15, 20, 23), ]
dim(BAD_means) # 7
BAD_lower=lower[c(2,4,7,11, 15, 20, 23), ]
BAD_upper=upper[c(2,4,7,11, 15, 20, 23), ]

#create a function that loops through the rows and columns of each matrix and boxplots each pathway/sdrug combination
makeMatrix=function(lowerMatrix, meanMatrix, upperMatrix){
final=tmp=name=NULL
Drug=NULL
for (i in 1:nrow(meanMatrix) ){
 for( j in 1:ncol(meanMatrix)){
  Drug =c(lowerMatrix[i,j],meanMatrix[i,j], upperMatrix[i,j])
  name=c(name,(paste(rownames(meanMatrix)[i],colnames(meanMatrix)[j],sep=')')))
  name=gsub(".adap_multi.pathway_activity_testset.csv.", "(", name)
  tmp=cbind(tmp,Drug)
  colnames(tmp)<-name
  }
 
final[i]<-tmp
par(mar=c(1,10,2,2))
boxplot(BAD_BADandAKTandHER, main = "BAD Pathway Drug Correlation Bootstrap", col = 3, las=2, horizontal = TRUE, cex.axis=0.7, boxwex=1, xlab= "Spearnman Correlation")
abline(v=0, col = "red", lwd = 2)
tmp=name=NULL
 
}
return (final)
 }
 
#BAD
pdf("~/BAD_boxplots.pdf")
ba=makeMatrix(BAD_means, BAD_lower, BAD_upper)
dev.off()



#Trying differenet box plot functions

#Bad_AKTnBADnIGF1R=final
#par(mar=c(19,5,2,1))
#boxplot(ba[1], main = "BAD Pathway Drug Correlation Bootstrap using AKT/BAD/IGF1R", col= ifelse(Bad_AKTnBADnIGF1R <= 0, "red", ifelse(Bad_AKTnBADnIGF1R >=0,"blue", "black")), las=2, cex.axis=0.7, boxwex=.7, ylab= "Spearnman Correlation")

#BAD_AKTandBAD=final
#par(mar=c(19,5,2,1))
#boxplot(BAD_AKTandBAD,main = "BAD Pathway Drug Correlation Bootstrap using AKT and BAD", col = 3, las=2, cex.axis=0.7, boxwex=.5, ylab= "Spearnman Correlation")
#abline(h=0, col = "red", lwd = 2)

#BAD_BADandAKTandHER=final
#par(mar=c(1,5,2,2))
#boxplot(BAD_BADandAKTandHER, main = "BAD Pathway Drug Correlation Bootstrap using AKT and and BAD and HER2 and BAD", col = 3, las=2, horizontal = TRUE, cex.axis=0.7, boxwex=1, ylab= "Spearnman Correlation")
#abline(h=0, col = "red", lwd = 2)
```

Do the same thing for single pathway
```{r}
drug_prediction_correlations_single= cor(pred_drug_single[1:4],pred_drug_single[15:104],use="na.or.complete")

single_and_multi= rbind(drug_prediction_correlations_multi,drug_prediction_correlations_single)

write.table(single_and_multi,"Correlations_ICBP_Single_Multi2.txt",sep='\t', col.names = NA,quote=F)
```

