---
title: "multipathway_ASSIGN"
author: "Mumtahena Rahman"
date: "December 23, 2014"
output: pdf_document
---

```{r,echo=FALSE,cache=TRUE,include=FALSE}
library(sva)
library(ASSIGN)
library(utils)
source("~/Documents/ThesisWork/GitRepos/bild_signatures/code/ASSIGN_Functions.R")
```

Reading in the signature datasets...
```{r include=FALSE,echo=FALSE}
setwd("~/Documents/ThesisWork/GitRepos/bild_signature_validation_old_repo/Datasets")

expr<-as.matrix(read.table("GFP18_AKT_BAD_HER2_IGF1R_RAF_ERK.tpmlog",sep='\t',row.names=1,header=1))
control<-subset(expr, select=GFP.1:GFP.12)
her2<-subset(expr, select=HER2.1:HER2.6)
akt<-subset(expr,select=AKT.1:AKT.6)
bad<-subset(expr,select=BAD.1:BAD.6)
igf1r<-subset(expr,select=IGF1R.1:IGF1R.6)
erk<-subset(expr,select=ERK.1:ERK.6)
expr_all<-cbind(control,akt,bad,her2,igf1r,erk)

#read in ICBP data
icbp<-as.matrix(read.table("~/Documents/ThesisWork/GitRepos/bild_signature_validation_old_repo/Datasets/ICBP/icbp_Rsubread_tpmlog.txt", sep='\t', stringsAsFactors=FALSE, header=1, row.names=1))

#filter 
expr_all_f <-expr_all[apply(expr_all[,1:41]==0,1,mean) < 0.85,]
dim(expr_all_f)
expr_all_icbp_f<-merge_drop(expr_all_f,icbp,by=0)


```

Batch adjust
```{r}
# PCA Plot
sub<-c(12,6,6,5,6,6,55)
pdf("pca_plots.pdf")
pcaplot(expr_all_icbp_f,sub)
bat1<-as.matrix(cbind(c(colnames(expr_all_f),colnames(icbp)),c(rep(1,length(colnames(expr_all_f))),rep(2,length(colnames(icbp))))))

#Run ComBat
combat_expr1<-ComBat(dat=expr_all_icbp_f, batch=bat1[,2], mod=NULL, numCovs=NULL)
pcaplot(combat_expr1,sub)
dev.off()

# Subset comBat data
c_gfp<-subset(combat_expr1, select=GFP.1:GFP.12)
c_akt<-subset(combat_expr1, select=AKT.1:AKT.6)
c_bad<-subset(combat_expr1, select=BAD.1:BAD.6)
c_her2<-subset(combat_expr1, select=HER2.1:HER2.6)
c_igf1r<-subset(combat_expr1, select=IGF1R.1:IGF1R.6)
c_erk<-subset(combat_expr1, select=ERK.1:ERK.6)
```

Run ASSIGN Single pathway
```{r}
basedir="~/Documents/ThesisWork/GitRepos/bild_signatures/Her2_Results_Rerun"
dir.create( basedir)

#############trying one pathways at a time in multipathway#############

# HER2
trainingLabelh<-list(control=list(her2=1:12),her2=13:17)
sub_dir<-paste(basedir,"her2_rerun",sep='/')
dir.create( sub_dir)
assign_easy_multi(trainingData = cbind(c_gfp,c_her2),test=c_test,trainingLabel1 = trainingLabelh,g=15,out_dir_base = sub_dir,single = 1)

#########including all 5 pathways######
trainhall5<-cbind(c_gfp,c_akt,c_bad,c_her2,c_igf1r, c_erk)
trainingLabelall5<-list(control=list(akt=1:12,bad=1:12,her2=1:12,igf1r=1:12, erk=1:12),akt=13:18, bad=19:24,her2=25:29,igf1r=30:35, erk=36:41)
sub_dir=paste(basedir,"akt_bad_her2_igf1r_erk",sep='/')
dir.create(sub_dir)
assign_easy_multi(trainingData = trainhall5,test=c_test,trainingLabel1 = trainingLabelall5,g=c(150,150,15,100,100),out_dir_base = sub_dir)

```

Get the gene list
```{r}
setwd("~/Documents/Thesiswork/GitRepos/bild_signatures")
filenames_single_her2_noseed<-system("ls *rda*", intern=TRUE)
filenames_single_her2_noseed

getGeneList(filenames_single_her2_noseed)

```





