---
title: "Multi_pathway Correlations with ICBP"
author: "Shelley"
date: "March 18, 2015"
output: html_document
---


```{r}
library(psych)

setwd("~//Documents/Thesiswork/GitRepos/bild_signatures/")

system("ls")

ICBP_preds_drugs<-(read.table("ICBP_pathwaypredictions_drug_all_combos.txt", sep='\t', stringsAsFactors=FALSE, header=1, row.names=1))
View(ICBP_preds_drugs)
colnames(ICBP_preds_drugs)
dimnames(ICBP_preds_drugs)

```


```{r}
colnames(ICBP_preds_drugs)
rhos=p_val=NULL
temp=cors_pvals=NULL
for(i in 1:160){
  for(j in 1:90) {
    #i=1
    #j=1
  pathway_drug=subset(ICBP_preds_drugs, select=c(i,160+j))
  temp_cors= cor.ci(pathway_drug, method="spearman", plot=FALSE, n.iter=1000)
  temp<-c(temp_cors$rho[2,1],temp_cors$ci[5])  
  temp<- cbind(temp[1],temp[2])
  cors_pvals<-rbind(cors_pvals,temp)
  rownames(cors_pvals)[j+(i-1)*90]=paste(colnames(pathway_drug)[1],colnames(pathway_drug)[2],sep='__')
  print(i)
  print(j)
  

}
colnames(cors_pvals)<-c("Corr","p_val")
dim(cors_pvals)


writeFile(cors_pvals, "ICBP_allpathwaycombos_all_drugs_1000.txt")

```

