---
title: "multipathway_ASSIGN"
author: "Mumtahena Rahman"
date: "March 23, 2015"
output: pdf_document
------------------------

Read in all the predictions are make files with all results 
```{r, echo=FALSE} 
#setwd("~/Documents/Thesiswork/ICBP/multi_icbp_expr_pc/")
source('~/Dropbox/bild_signatures/bild_signatures/Rmarkdowns_scripts//Key_ASSIGN_functions.Rmd', echo=F)
setwd("~/Dropbox/bild_signatures/icbp_15_mar_all/")
filenames_icbp_multi<-system("ls */*/pathway_activity_testset*", intern=TRUE)
#filenames_icbp_multi

for(i in 1:length(filenames_icbp_multi))
  {
   f<-read.csv(filenames_icbp_multi[i], header=1,row.names=1) ###reading in the filess one at a time
   colnames(f)<-paste(filenames_icbp_multi[i],colnames(f),sep='/')
   if(i==1){
     data_icbp<-f
     }
   else{
     data_icbp<-cbind(data_icbp,f)
    }
  }
#head(data_icbp)
#dim(data_icbp)

colnames(data_icbp)<-gsub(pattern = "/pathway_activity_testset.csv",replacement = "",x = colnames(data_icbp))
#head(data_icbp)
rownames(data_icbp)[1:7]<-c("184A1","184B5","21MT1","21MT2","21NT","21PT","600MPE")
setwd("~/Dropbox/bild_signatures//Datasets")
drugs<-read.delim("ICBP_drugs.txt", header=1, sep='\t',row.names=1)
#head(drugs);dim(drugs)
pred_drug<-merge_drop(data_icbp,drugs,by=0)
#dim(pred_drug)
```
The function to compare pathway-drug response correlation
```{r, echo=FALSE}

check_sign_flip<-function(preds){
problematic=NULL
adapB<-subset(preds,select=grep("/adapB_", colnames(preds) , ignore.case=FALSE, fixed=T))
adap_adap<-subset(preds,select=grep("/adap_adap", colnames(preds) , ignore.case=FALSE, fixed=T))
for(i in 1:16){
  print(cor(adap_adap[i],adapB[i]))
  if(cor(adap_adap[i],adapB[i])<0)
    {
    print(paste("direction flipped in adaptive-adaptive feature",colnames(adap_adap)[i],sep=':'))
    problematic=c(problematic,colnames(adap_adap)[i])
  }
}
return(problematic)
}
#### Bootstrap:
create_boot_cors<-function(pathway_predictions=NULL,pred_drug,druglist){
pathways = ncol(pathway_predictions) # number of pathway signatures
samplesize = length(druglist)#nrow(pred_drug_multi) # number of cell lines
n.boot = 10000 # number of bootstrap samples -- set at 10,000 or more for your final run
boot_cors = array(0,dim=c(pathways,samplesize,n.boot)) # make a three dimensional array to store the bootstrap results
drug_index=NULL
for(j in 1:length(druglist)){
    drug_index=c(drug_index,which(colnames(pred_drug)==druglist[j]))
    }
for(j in 1:length(drug_index)){
  for (i in 1:n.boot){
  boot.sample = sample(1:nrow(pred_drug),replace=T)
  boot_cors[,j,i]=cor(pathway_predictions[boot.sample,1:pathways],pred_drug[boot.sample,drug_index[j]],use="pairwise",method="spearman")
    }
  }

dimnames(boot_cors)[[1]]=colnames(pathway_predictions)#pathway
dimnames(boot_cors)[[2]]=druglist

return (boot_cors)
}
# ## p-values: to test that a correlation is bigger than some value:
cor_cutoff = 0 ## i.e. to test is the correlation is > or < 0. Note this can be anything, i.e. .1, .5, etc
p_calc = function(x,direction="greater",cor_cut=0){
  if (!(direction %in% c("greater","less"))){stop("Invalid value for direction")}
  if (direction=="greater"){return(mean(x>cor_cut,na.rm=T))}
  if (direction=="less"){return(mean(x<cor_cut,na.rm=T))}
  }

# ps_above_0_3 = apply(boot_cors, c(1,2), p_calc,cor_cut=0.3)#ask Shelley
# ps_below_0_3 = apply(boot_cors, c(1,2), p_calc,direction="less",cor_cut=0.3)
cor_tables<-read.table("~/Dropbox/bild_signatures/bild_signatures/Results//ICBP/correlations//ICBP_corci_160pathwaycombos_90drugs_10000i.txt", header=1,row.names=1)
#  to test 
p_calc_compare=function(path1,path2,drug,cor_cut=0,cors){
    pathlist=dimnames(cors)[[1]]
    druglist=dimnames(cors)[[2]]
    ind_p1 = which(pathlist==path1)
    ind_p2 = which(pathlist==path2)
    ind_drug = which(druglist==drug)
    mean((cors[ind_p1,ind_drug,]-cors[ind_p2,ind_drug,])>cor_cut,na.rm=T)     
}
cor_tables=read.table("~/Dropbox/bild_signatures//bild_signatures/Results/ICBP/correlations/ICBP_corci_160pathwaycombos_90drugs_10000i.txt", header=1,row.name=1)
bootstrap_compare<-function(pathway_predictions,pred_drug,boot_cors){
##This function identifies the pathway that best correlates with given drug
  pathway=dimnames(boot_cors)[[1]]
  druglist=dimnames(boot_cors)[[2]]
  best_pathway=NULL
  for(d in 1:length(druglist)){
    print(druglist[d])
    comp_val=0
    current_best=-1   
    for(i in 1:(length(pathway)-1)){
        if(cor_tables[paste(gsub("/",".",pathway[i]),druglist[d],sep="__"),2]<0.15){
          current_best=pathway[i]
          for(j in (i+1):length(pathway)){
            if(cor_tables[paste(gsub("/",".",pathway[j]),druglist[d],sep="__"),2]<0.15){
              temp_diff=p_calc_compare(path1 = current_best,path2 = pathway[j],drug = druglist[d],cors = boot_cors)
              if(temp_diff<0.5){
                current_best=pathway[j]
                break
              }
            }
          }             
        }
      } 
    #best_pathway=c(best_pathway,paste(druglist[d],current_best,cor_tables[paste(gsub("/",".",current_best),druglist[d],sep="__"),1],sep='\t'))#}
    if(current_best!=-1){best_pathway=rbind(best_pathway,cbind(cor_tables[paste(gsub("/",".",current_best),druglist[d],sep="__"),1:2],druglist[d],current_best))
         }
    }
  return (best_pathway)
  }

```
calculating the best predicting pathway for each drug..
```{r,echo=FALSE}

# chemolist<-c("X5.FU","X5.FdUR","CGC.11047","CGC.11144","CPT.11","Carboplatin","Cisplatin","Docetaxel","Doxorubicin","Epirubicin","Etoposide","Gemcitabine","Oxaliplatin","Methotrexate","ICRF.193","Ixabepilone","Paclitaxel","Pemetrexed","Topotecan","Vinorelbine")
# 
# targeted_list<-c("AG1478","Sigma.AKT1.2.inhibitor",  "Triciribine",	"AS.252424",	"BEZ235",	"BIBW2992",		"ERKi.II..FR180304.",		"Erlotinib",	"Everolimus",	"GSK1120212",	"GSK1059868",	"GSK1838705",	"GSK2119563",	"GSK2126458",	"GSK2141795",	"GSK1059615",	"Lapatinib",	"Imatinib",	"Gefitinib",	"Rapamycin",	"Temsirolimus")
# 
# akt_preds<-subset(pred_drug,select=grep("/akt", colnames(pred_drug) , ignore.case=FALSE, fixed=T))
# dim(akt_preds)
# bad_preds<-subset(pred_drug,select=grep("/bad", colnames(pred_drug) , ignore.case=FALSE, fixed=T))
# dim(bad_preds)
# erk_preds<-subset(pred_drug,select=grep("/erk", colnames(pred_drug) , ignore.case=FALSE, fixed=T))
# dim(erk_preds)
# her2_preds<-subset(pred_drug,select=grep("/her2", colnames(pred_drug) , ignore.case=FALSE, fixed=T))
# dim(her2_preds)
# igf1r_preds<-subset(pred_drug,select=grep("/igf1r", colnames(pred_drug) , ignore.case=FALSE, fixed=T))
# dim(igf1r_preds)
# 
# check_sign_flip(akt_preds)#"no sign flipping observed in AKT pathway predictions""
# check_sign_flip(bad_preds)#"no sign flipping observed in BAD pathway predictions"
# check_sign_flip(her2_preds)#"no sign flipping observed in HER2 pathway predictions"
# erk_prblematic=check_sign_flip(erk_preds)#"no sign flipping observed in BAD pathway predictions"
# check_sign_flip(igf1r_preds)#"no sign flipping observed in BAD pathway predictions"
# 
# erk_up=erk_preds
# for(i in 1:length(erk_prblematic)){
#   erk_up[,which(colnames(erk_up)==erk_prblematic[i])]=1-erk_up[,which(colnames(erk_up)==erk_prblematic[i])]
#   }
# 
# #drugs<-c("Lapatinib","Sigma.akt.1.2.inhibitor")
# colnames(pred_drug)
# all_preds=create_boot_cors(pathway_predictions = pred_drug[,1:160],druglist = colnames(pred_drug)[171:260],pred_drug = pred_drug)
# all_best_pathway=bootstrap_compare(pathway_predictions=all_preds,pred_drug=pred_drug,boot_cors = all_preds,druglist=colnames(pred_drug)[171:260])
# write.table(all_best_pathway,"~/Dropbox/bild_signatures/bild_signatures/Results/ICBP/all_best_chemo_tageted pathway_03_26.txt",sep='\t')
# 
# akt_chemo_boot_cors=create_boot_cors(pathway_predictions = akt_preds,pred_drug = pred_drug,druglist = chemolist)
# akt_target_boot_cors=create_boot_cors(pathway_predictions = akt_preds,pred_drug = pred_drug,druglist = targeted_list)
# akt_best_pathway_target=bootstrap_compare(pathway_predictions=akt_preds,pred_drug=pred_drug,boot_cors = akt_target_boot_cors)
# akt_best_pathway_chemo=bootstrap_compare(pathway_predictions=akt_preds,pred_drug=pred_drug,boot_cors = akt_chemo_boot_cors)
# 
# 
# bad_chemo_boot_cors=create_boot_cors(pathway_predictions = bad_preds,pred_drug = pred_drug,druglist = chemolist)
# bad_target_boot_cors=create_boot_cors(pathway_predictions = bad_preds,pred_drug = pred_drug,druglist = targeted_list)
# bad_best_pathway_chemo=bootstrap_compare(pathway_predictions=bad_preds,pred_drug=pred_drug,boot_cors = bad_chemo_boot_cors)
# bad_best_pathway_target=bootstrap_compare(pathway_predictions=bad_preds,pred_drug=pred_drug,boot_cors = bad_target_boot_cors)
# 
# 
# erk_chemo_boot_cors=create_boot_cors(pathway_predictions = erk_preds,pred_drug = pred_drug,druglist = chemolist)
# erk_target_boot_cors=create_boot_cors(pathway_predictions = erk_preds,pred_drug = pred_drug,druglist = targeted_list)
# erk_best_pathway_chemo=bootstrap_compare(pathway_predictions=erk_preds,pred_drug=pred_drug,boot_cors = erk_chemo_boot_cors)
# erk_best_pathway_target=bootstrap_compare(pathway_predictions=erk_preds,pred_drug=pred_drug,boot_cors = erk_target_boot_cors)
# 
# erk_chemo_boot_cors_up=create_boot_cors(pathway_predictions = erk_up,pred_drug = pred_drug,druglist = chemolist)
# erk_target_boot_cors_up=create_boot_cors(pathway_predictions = erk_up,pred_drug = pred_drug,druglist = targeted_list)
# erk_best_pathway_chemo_up=bootstrap_compare(pathway_predictions=erk_up,pred_drug=pred_drug,boot_cors = erk_chemo_boot_cors)
# erk_best_pathway_target_up=bootstrap_compare(pathway_predictions=erk_up,pred_drug=pred_drug,boot_cors = erk_target_boot_cors)
# 
# her2_chemo_boot_cors=create_boot_cors(pathway_predictions = her2_preds,pred_drug = pred_drug,druglist = chemolist)
# her2_target_boot_cors=create_boot_cors(pathway_predictions = her2_preds,pred_drug = pred_drug,druglist = targeted_list)
# her2_best_pathway_chemo=bootstrap_compare(pathway_predictions=her2_preds,pred_drug=pred_drug,boot_cors = her2_chemo_boot_cors)
# her2_best_pathway_target=bootstrap_compare(pathway_predictions=her2_preds_preds,pred_drug=pred_drug,boot_cors = her2_target_boot_cors) 
# 
# 
# igf1r_chemo_boot_cors=create_boot_cors(pathway_predictions = igf1r_preds,pred_drug = pred_drug,druglist = chemolist)
# igf1r_target_boot_cors=create_boot_cors(pathway_predictions = igf1r_preds,pred_drug = pred_drug,druglist = targeted_list)
# igf1r_best_pathway_chemo=bootstrap_compare(pathway_predictions=igf1r_preds,pred_drug=pred_drug,boot_cors = igf1r_chemo_boot_cors)
# igf1r_best_pathway_target=bootstrap_compare(pathway_predictions=igf1r_preds_preds,pred_drug=pred_drug,boot_cors = igf1r_target_boot_cors) 
# ## pval_comp = 0.91 in this case means that AKT+BAD > AKT+BAD+HER2 in 91% of the bootstrap correlations. Thus the p-value for testing Ha: AKT+BAD > AKT+BAD+HER2 is 0.09
# 
# 
# write.table(rbind(bad_best_pathway_chemo,bad_best_pathway_target,erk_best_pathway_chemo,erk_best_pathway_target,akt_best_pathway_chemo,akt_best_pathway_target,her2_best_pathway_chemo,her2_best_pathway_target,igf1r_best_pathway_chemo,igf1r_best_pathway_target,erk_best_pathway_chemo_up,erk_best_pathway_target_up),"~/Dropbox/bild_signatures/bild_signatures/Results/ICBP/best_chemo_tageted pathway_03_26.txt",sep='\t',col.names=NA, quote=F)
```

```{r echo=FALSE}
best_pathway_predictions=apply(subset(pred_drug,select=c(34,35,37,108,145,150)),2,scale)
rownames(best_pathway_predictions)<-rownames(pred_drug)
#########this subtype analysis is the transcriptional subtype + HER2 status based.#########
subtype_her2<-pred_drug[,162]
subtype_her2=gsub("ERBB2.*","ERBB2",subtype_her2)
subtype_her2=gsub("Basal.*","BASAL",subtype_her2)
subtype_her2=gsub("Luminal.*","LUMINAL",subtype_her2)
subtype_her2=gsub(".*ormal.*","NORMAL",subtype_her2)

par(mar=c(3,3,3, 0.5),lwd=4)
#pdf("~/Dropbox/bild_signatures/bild_signatures/Results/ICBP_predictions.pdf")
#min(best_pathway_predictions)
boxplot(best_pathway_predictions[,1]~subtype_her2,main="AKT across breast cell lines",col=2:5,ylim=c(-2.5,2))
boxplot(best_pathway_predictions[,2]~subtype_her2,main="BAD across breast cell lines",col=2:5,ylim=c(-2.5,2))
boxplot(best_pathway_predictions[,3]~subtype_her2,main="IGF1R across breast cell lines",col=2:5,ylim=c(-2.5,2))
boxplot(best_pathway_predictions[,4]~subtype_her2,main="ERK across breast cell lines",col=2:5,ylim=c(-2.5,2))
boxplot(best_pathway_predictions[,5]~subtype_her2,main="HER2(3) across breast cell lines",col=2:5,ylim=c(-2.5,2))
boxplot(best_pathway_predictions[,6]~subtype_her2,main="HER2(2) across breast cell lines",col=2:5,ylim=c(-2.5,2))
#best_pathway_predictions[,"subtype_her2"]<-subtype_her2
cell_basal<-best_pathway_predictions[subtype_her2=="BASAL",]
boxplot(cell_basal[,1],cell_basal[,2],cell_basal[,3],cell_basal[,4],cell_basal[,5],cell_basal[,6],names=c("AKT","BAD","IGF1R","ERK","HER2(3)","HER2(2)"),main="Pathway activity in BASAL cell lines",col=2:7,ylim=c(-2.5,2))
cell_her2<-best_pathway_predictions[subtype_her2=="ERBB2",]
boxplot(cell_her2[,1],cell_her2[,2],cell_her2[,3],cell_her2[,4],cell_her2[,5],cell_her2[,6],names=c("AKT","BAD","IGF1R","ERK","HER2(3)","HER2(2)"),main="Pathway activity in ERBB2 cell lines",col=2:7)
cell_lum<-best_pathway_predictions[subtype_her2=="LUMINAL",]
boxplot(cell_lum[,1],cell_lum[,2],cell_lum[,3],cell_lum[,4],cell_lum[,5],cell_lum[,6],names=c("AKT","BAD","IGF1R","ERK","HER2(3)","HER2(2)"),main="Pathway activity in LUMINAL cell lines",col=2:7)
cell_clad<-best_pathway_predictions[subtype_her2=="Claudin-low",]
boxplot(cell_clad[,1],cell_clad[,2],cell_clad[,3],cell_clad[,4],cell_clad[,5],cell_clad[,6],names=c("AKT","BAD","IGF1R","ERK","HER2(3)","HER2(2)"),main="Pathway activity in Claudin-low cell lines",col=2:7)
print("comparing BAD activity between triple negative(basal+claudin-low) and luminal")
t.test(c(cell_basal[,2],cell_clad[,2]),c(cell_her2[,2],cell_lum[,2]))
# print("comparing ERK activity between triple negative(basal+claudin-low) and luminal")
# boxplot(cell_basal[,4],cell_clad[,4],cell_lum[,4])
#t.test(c(cell_basal[,4],cell_clad[,4]),cell_lum[,4])
print("comparing ERK activity between triple negative(basal+claudin-low) and luminal")
t.test(c(cell_basal[,4],cell_clad[,4]),c(cell_her2[,4],cell_lum[,4]))
print("comparing IGF1R activity between basal and luminal")
t.test(cell_basal[,3],cell_lum[,3])
# boxplot(basal[,3],luminal[,3], names=c("BASAL", "LUMINAL"),main="IGF1R activity")
# print("comparing IGF1R activity between basal and normal")
# t.test(cell_basal[,3],ce[,3])
subtype=pred_drug[,161]

subtype=gsub("Basal.*","BASAL",subtype)
subtype=gsub("Luminal.*","LUMINAL",subtype)
subtype=gsub(".*ormal.*","NORMAL",subtype)
subtype_best_pred<-cbind(best_pathway_predictions,subtype,subtype_her2)
basal=subset(subtype_best_pred,subtype=="BASAL")
luminal=subset(subtype_best_pred,subtype=="LUMINAL")  
claudin=subset(subtype_best_pred,subtype=="Claudin-low")
normal=subset(subtype_best_pred,subtype=="NORMAL")


#########this subtype analysis is the transcriptional subtype based.#########

#subtype
# boxplot(best_pathway_predictions[,1]~subtype,main="AKT across breast cell lines(PAM50)",col=2:5)
# boxplot(best_pathway_predictions[,2]~subtype,main="BAD across breast cell lines(PAM50)",col=2:5)
# boxplot(best_pathway_predictions[,3]~subtype,main="IGF1R across breast cell lines(PAM50)",col=2:5)
# boxplot(best_pathway_predictions[,4]~subtype,main="ERK across breast cell lines(PAM50)",col=2:5)
# boxplot(best_pathway_predictions[,5]~subtype,main="HER2(3) across breast cell lines(PAM50)",col=2:5)
# boxplot(best_pathway_predictions[,6]~subtype,main="HER2(2) across breast cell lines(PAM50)",col=2:5)
```
Things that I am working on now with ERK..
```{r}
proteomics_cell<-read.table("~/Dropbox/bild_signatures/bild_signatures//Datasets/proteomics.txt", header=1, row.names=1)

erk_pred<-read.csv("~/Dropbox/bild_signatures/icbp_15_mar_all/bad_igf1r_her2_erk/adap_adap_multi/pathway_activity_testset.csv",header=1,row.names=1)
erk_pred_adapB<-read.csv("~/Dropbox/bild_signatures/icbp_15_mar_all/bad_igf1r_her2_erk/adapB_multi/pathway_activity_testset.csv",header=1,row.names=1)

multi_5_pred_prot<-merge_drop(erk_pred,proteomics_cell,by = 0)
print(paste("bad_igf1r_her2_erk + adaptive_adaptive_multi ERK prediction with MAPKp protein",cor(multi_5_pred_prot$erk,multi_5_pred_prot$MAPKp,method="spearman"),sep=" "))

print(paste("bad_igf1r_her2_erk + adaptive_adaptive_multi ERK prediction with ERK2 protein",cor(multi_5_pred_prot$erk,multi_5_pred_prot$ERK2,method="spearman"),sep=" "))

multi_5_pred_prot_b<-merge_drop(erk_pred_adapB,proteomics_cell,by = 0)
print(paste("bad_igf1r_her2_erk + adaptive_B_multi ERK prediction with MAPKp protein",cor(multi_5_pred_prot_b$erk,multi_5_pred_prot$MAPKp,method="spearman"),sep=" "))
print(paste("bad_igf1r_her2_erk + adaptive_B_multi ERK prediction with ERK protein",cor(multi_5_pred_prot_b$erk,multi_5_pred_prot$ERK2,method="spearman"),sep=" "))
##############
erk_pred<-read.csv("~/Dropbox/bild_signatures/icbp_15_mar_all/igf1r_her2_erk/adap_adap_multi/pathway_activity_testset.csv",header=1,row.names=1)
erk_pred_adapB<-read.csv("~/Dropbox/bild_signatures/icbp_15_mar_all/igf1r_her2_erk/adapB_multi/pathway_activity_testset.csv",header=1,row.names=1)

multi_5_pred_prot<-merge_drop(erk_pred,proteomics_cell,by = 0)
print(paste("Correlation: igf1r_her2_erk + adaptive_adaptive_multi ERK prediction with MAPKp protein",cor(multi_5_pred_prot$erk,multi_5_pred_prot$MAPKp,method="spearman"),sep=" "))
print(paste("Correlation: igf1r_her2_erk + adaptive_adaptive_multi ERK prediction with ERK protein",cor(multi_5_pred_prot$erk,multi_5_pred_prot$ERK2,method="spearman"),sep=" "))

multi_5_pred_prot_b<-merge_drop(erk_pred_adapB,proteomics_cell,by = 0)
print(paste("Correlation: igf1r_her2_erk + adaptive_B_multi ERK prediction with MAPKp protein",cor(multi_5_pred_prot_b$erk,multi_5_pred_prot$MAPKp,method="spearman"),sep=" "))
print(paste("Correlation: igf1r_her2_erk + adaptive_B_multi ERK prediction with ERK protein",cor(multi_5_pred_prot_b$erk,multi_5_pred_prot$ERK2,method="spearman"),sep=" "))

#dev.off()
```

```{r echo=FALSE}
time<-format(Sys.time(),"%a %b %d %X %Y")
```
This analysis was run on `r time` 
