---
title: "multipathway_ASSIGN"
author: "Mumtahena Rahman"
date: "December 23, 2014"
output: pdf_document
------------------------

Read in all the predictions are make files with all results 
```{r, echo=TRUE}
# multi nonadpative 
#setwd("~/Documents/Thesiswork/ICBP/multi_icbp_expr_pc/")
source('~/Dropbox/bild_signatures/bild_signatures/Rmarkdowns_scripts//Key_ASSIGN_functions.Rmd', echo=TRUE)
setwd("~/Dropbox/bild_signatures/icbp_15_mar_all/")
filenames_icbp_multi<-system("ls */*/pathway_activity_testset*", intern=TRUE)
filenames_icbp_multi

for(i in 1:length(filenames_icbp_multi))
  {
   f<-read.csv(filenames_icbp_multi[i], header=1,row.names=1) ###reading in the filess one at a time
   colnames(f)<-paste(filenames_icbp_multi[i],colnames(f),sep='/')
   if(i==1){
     data_icbp<-f
     }
   else{
     data_icbp<-cbind(data_icbp,f)
    }
  }

head(data_icbp)
dim(data_icbp)

#cor(data_icbp[,90], data_icbp[,82])

colnames(data_icbp)<-gsub(pattern = "/pathway_activity_testset.csv",replacement = "",x = colnames(data_icbp))
head(data_icbp)
rownames(data_icbp)[1:7]<-c("184A1","184B5","21MT1","21MT2","21NT","21PT","600MPE")
setwd("~/Dropbox/bild_signatures//Datasets")
drugs<-read.delim("ICBP_drugs.txt", header=1, sep='\t',row.names=1)
head(drugs);dim(drugs)
pred_drug<-merge_drop(data_icbp,drugs,by=0)
dim(pred_drug)
```
The function to compare pathway-drug response correlation
```{r}

check_sign_flip<-function(preds){
problematic=NULL
adapB<-subset(preds,select=grep("/adapB_", colnames(preds) , ignore.case=FALSE, fixed=T))
adap_adap<-subset(preds,select=grep("/adap_adap", colnames(preds) , ignore.case=FALSE, fixed=T))
for(i in 1:16){
  print(cor(adap_adap[i],adapB[i]))
  if(cor(adap_adap[i],adapB[i])<0)
    {
    print(paste("direction flipped in adaptive-adaptive feature",colnames(adap_adap)[i],sep=':'))
    problematic=c(problematic,colnames(adap_adap)[i])
  }
}
return(problematic)
}
#### Bootstrap:
create_boot_cors<-function(pathway_predictions=NULL,pred_drug,druglist){
pathways = ncol(pathway_predictions) # number of pathway signatures
samplesize = length(druglist)#nrow(pred_drug_multi) # number of cell lines
n.boot = 10000 # number of bootstrap samples -- set at 10,000 or more for your final run
boot_cors = array(0,dim=c(pathways,samplesize,n.boot)) # make a three dimensional array to store the bootstrap results
drug_index=NULL
for(j in 5){#1:length(druglist)){
    drug_index=c(drug_index,which(colnames(pred_drug)==druglist[j]))
    }
for(j in 1:length(drug_index)){
  for (i in 1:n.boot){
  boot.sample = sample(1:nrow(pred_drug),replace=T)
  #print(length(boot.sample))
  boot_cors[,j,i]=cor(pathway_predictions[boot.sample,1:pathways],pred_drug[boot.sample,drug_index[j]],use="pairwise",method="spearman")
    }
  }

dimnames(boot_cors)[[1]]=colnames(pathway_predictions)#pathway
dimnames(boot_cors)[[2]]=druglist

#cor_mean = apply(boot_cors, c(1,2), mean, na.rm=T)  ## average bootstrap cors. Should be similar to the non-boot values
return (boot_cors)
}
# ## p-values: to test that a correlation is bigger than some value:
cor_cutoff = 0 ## i.e. to test is the correlation is > or < 0. Note this can be anything, i.e. .1, .5, etc
p_calc = function(x,direction="greater",cor_cut=0){
  if (!(direction %in% c("greater","less"))){stop("Invalid value for direction")}
  if (direction=="greater"){return(mean(x>cor_cut,na.rm=T))}
  if (direction=="less"){return(mean(x<cor_cut,na.rm=T))}
  }

# ps_above_0_3 = apply(boot_cors, c(1,2), p_calc,cor_cut=0.3)#ask Shelley
# ps_below_0_3 = apply(boot_cors, c(1,2), p_calc,direction="less",cor_cut=0.3)
cor_tables<-read.table("~/Dropbox/bild_signatures/bild_signatures/Results//ICBP/correlations//ICBP_corci_160pathwaycombos_90drugs_10000i.txt", header=1,row.names=1)
#  to test 
p_calc_compare=function(path1,path2,drug,cor_cut=0,cors){
    pathlist=dimnames(cors)[[1]]
    druglist=dimnames(cors)[[2]]
    ind_p1 = which(pathlist==path1)
    ind_p2 = which(pathlist==path2)
    ind_drug = which(druglist==drug)
    mean((cors[ind_p1,ind_drug,]-cors[ind_p2,ind_drug,])>cor_cut,na.rm=T)     
}
cor_tables=read.table("~/Dropbox/bild_signatures//bild_signatures/Results/ICBP/correlations/ICBP_corci_160pathwaycombos_90drugs_10000i.txt", header=1,row.name=1)
bootstrap_compare<-function(pathway_predictions,pred_drug,boot_cors,druglist){

pathway=dimnames(boot_cors)[[1]]
druglist=dimnames(boot_cors)[[2]]
best_pathway=NULL
for(d in 1:length(druglist)){
  print(druglist[d])
  current_best=NULL
  comp_val=0
  for(i in 1:length(pathway)){
    if(i==1){
      p1=pathway[i]
      p_list=pathway[-i]}
    if(cor_tables[paste(gsub("/",".",p1),druglist[d],sep="__"),2]<0.15){
        for(j in 1:length(p_list)){
            if(cor_tables[paste(gsub("/",".",p_list[j]),druglist[d],sep="__"),2]<0.15){
              temp_diff=p_calc_compare(path1 = p1,path2 = p_list[j],drug = druglist[d],cors = boot_cors)
              if(comp_val==0&temp_diff>0.5){
                comp_val<-temp_diff
                current_best=p1}
              else if(comp_val==0 &temp_diff<0.5){
                comp_val<-1-temp_diff
                current_best=p_list[j]
                p1=p_list[j]
                if(length(p_list)>1){
                  p_list=p_list[-j]
                  j=1
                  break}
              }
              else if(temp_diff<0.5){
                comp_val<-1-temp_diff
                current_best=p_list[j]
                p1=p_list[j]
                if(length(p_list)>1){
                  p_list=p_list[-j]
                  j=1
                  break}
                }
               else {
                comp_val<-temp_diff
                current_best=p1}
             }
            else{
              current_best=p1
            }
        }             
      }
    } 
  #if(length(best_pathway)>0){
    best_pathway=c(best_pathway,paste(druglist[d],current_best,cor_tables[paste(gsub("/",".",current_best),druglist[d],sep="__"),1],sep='\t'))#}
  }
return (best_pathway)
}

```
calculating the best predicting pathway for each drug..
```{r}

chemolist<-c("X5.FU","X5.FdUR","CGC.11047","CGC.11144","CPT.11","Carboplatin","Cisplatin","Docetaxel","Doxorubicin","Epirubicin","Etoposide","Gemcitabine","Oxaliplatin","Methotrexate","ICRF.193","Ixabepilone","Paclitaxel","Pemetrexed","Topotecan","Vinorelbine")

targeted_list<-c("AG1478","Sigma.AKT1.2.inhibitor",  "Triciribine",	"AS.252424",	"BEZ235",	"BIBW2992",		"ERKi.II..FR180304.",		"Erlotinib",	"Everolimus",	"GSK1120212",	"GSK1059868",	"GSK1838705",	"GSK2119563",	"GSK2126458",	"GSK2141795",	"GSK1059615",	"Lapatinib",	"Imatinib",	"Gefitinib",	"Rapamycin",	"Temsirolimus")

akt_preds<-subset(pred_drug,select=grep("/akt", colnames(pred_drug) , ignore.case=FALSE, fixed=T))
dim(akt_preds)
bad_preds<-subset(pred_drug,select=grep("/bad", colnames(pred_drug) , ignore.case=FALSE, fixed=T))
dim(bad_preds)
erk_preds<-subset(pred_drug,select=grep("/erk", colnames(pred_drug) , ignore.case=FALSE, fixed=T))
dim(erk_preds)
her2_preds<-subset(pred_drug,select=grep("/her2", colnames(pred_drug) , ignore.case=FALSE, fixed=T))
dim(her2_preds)
igf1r_preds<-subset(pred_drug,select=grep("/igf1r", colnames(pred_drug) , ignore.case=FALSE, fixed=T))
dim(igf1r_preds)

check_sign_flip(akt_preds)#"no sign flipping observed in AKT pathway predictions""
check_sign_flip(bad_preds)#"no sign flipping observed in BAD pathway predictions"
check_sign_flip(her2_preds)#"no sign flipping observed in HER2 pathway predictions"
erk_prblematic=check_sign_flip(erk_preds)#"no sign flipping observed in BAD pathway predictions"
check_sign_flip(igf1r_preds)#"no sign flipping observed in BAD pathway predictions"

erk_up=erk_preds
for(i in 1:length(erk_prblematic)){
  erk_up[,which(colnames(erk_up)==erk_prblematic[i])]=1-erk_up[,which(colnames(erk_up)==erk_prblematic[i])]
  }

#drugs<-c("Lapatinib","Sigma.akt.1.2.inhibitor")
colnames(pred_drug)
all_preds=create_boot_cors(pathway_predictions = pred_drug[,1:160],druglist = colnames(pred_drug)[171:260],pred_drug = pred_drug)
all_best_pathway=bootstrap_compare(pathway_predictions=all_preds,pred_drug=pred_drug,boot_cors = all_preds,druglist=colnames(pred_drug)[171:260])


akt_chemo_boot_cors=create_boot_cors(pathway_predictions = akt_preds,pred_drug = pred_drug,druglist = chemolist)
akt_target_boot_cors=create_boot_cors(pathway_predictions = akt_preds,pred_drug = pred_drug,druglist = targeted_list)
akt_best_pathway_target=bootstrap_compare(pathway_predictions=akt_preds,pred_drug=pred_drug,boot_cors = akt_target_boot_cors,druglist=targeted_list)
akt_best_pathway_chemo=bootstrap_compare(pathway_predictions=akt_preds,pred_drug=pred_drug,boot_cors = akt_chemo_boot_cors,druglist=chemolist)


bad_chemo_boot_cors=create_boot_cors(pathway_predictions = bad_preds,pred_drug = pred_drug,druglist = chemolist)
bad_target_boot_cors=create_boot_cors(pathway_predictions = bad_preds,pred_drug = pred_drug,druglist = targeted_list)
bad_best_pathway_chemo=bootstrap_compare(pathway_predictions=bad_preds,pred_drug=pred_drug,druglist=chemolist,boot_cors = bad_chemo_boot_cors)
bad_best_pathway_target=bootstrap_compare(pathway_predictions=bad_preds,pred_drug=pred_drug,boot_cors = bad_target_boot_cors,druglist=targeted_list)


erk_chemo_boot_cors=create_boot_cors(pathway_predictions = erk_preds,pred_drug = pred_drug,druglist = chemolist)
erk_target_boot_cors=create_boot_cors(pathway_predictions = erk_preds,pred_drug = pred_drug,druglist = targeted_list)
erk_best_pathway_chemo=bootstrap_compare(pathway_predictions=erk_preds,pred_drug=pred_drug,boot_cors = erk_chemo_boot_cors, druglist=chemolist)
erk_best_pathway_target=bootstrap_compare(pathway_predictions=erk_preds,pred_drug=pred_drug,boot_cors = erk_target_boot_cors,druglist=targeted_list)

erk_chemo_boot_cors_up=create_boot_cors(pathway_predictions = erk_up,pred_drug = pred_drug,druglist = chemolist)
erk_target_boot_cors_up=create_boot_cors(pathway_predictions = erk_up,pred_drug = pred_drug,druglist = targeted_list)
erk_best_pathway_chemo_up=bootstrap_compare(pathway_predictions=erk_up,pred_drug=pred_drug,boot_cors = erk_chemo_boot_cors, druglist=chemolist)
erk_best_pathway_target_up=bootstrap_compare(pathway_predictions=erk_up,pred_drug=pred_drug,boot_cors = erk_target_boot_cors,druglist=targeted_list)

her2_chemo_boot_cors=create_boot_cors(pathway_predictions = her2_preds,pred_drug = pred_drug,druglist = chemolist)
her2_target_boot_cors=create_boot_cors(pathway_predictions = her2_preds,pred_drug = pred_drug,druglist = targeted_list)
her2_best_pathway_chemo=bootstrap_compare(pathway_predictions=her2_preds,pred_drug=pred_drug,boot_cors = her2_chemo_boot_cors,druglist=chemolist)
her2_best_pathway_target=bootstrap_compare(pathway_predictions=her2_preds_preds,pred_drug=pred_drug,boot_cors = her2_target_boot_cors,druglist=targeted_list) 


igf1r_chemo_boot_cors=create_boot_cors(pathway_predictions = igf1r_preds,pred_drug = pred_drug,druglist = chemolist)
igf1r_target_boot_cors=create_boot_cors(pathway_predictions = igf1r_preds,pred_drug = pred_drug,druglist = targeted_list)
igf1r_best_pathway_chemo=bootstrap_compare(pathway_predictions=igf1r_preds,pred_drug=pred_drug,boot_cors = igf1r_chemo_boot_cors,druglist=chemolist)
igf1r_best_pathway_target=bootstrap_compare(pathway_predictions=igf1r_preds_preds,pred_drug=pred_drug,boot_cors = igf1r_target_boot_cors,druglist=targeted_list) 
## pval_comp = 0.91 in this case means that AKT+BAD > AKT+BAD+HER2 in 91% of the bootstrap correlations. Thus the p-value for testing Ha: AKT+BAD > AKT+BAD+HER2 is 0.09


write.table(c(bad_best_pathway_chemo,bad_best_pathway_target,erk_best_pathway_chemo,erk_best_pathway_target,akt_best_pathway_chemo,akt_best_pathway_target,her2_best_pathway_chemo,her2_best_pathway_target,igf1r_best_pathway_chemo,igf1r_best_pathway_target,erk_best_pathway_chemo_up,erk_best_pathway_target_up),"~/Dropbox/bild_signatures/bild_signatures/Results/ICBP/best_chemo_tageted pathway_03_26.txt",sep='\t')


akt_adapB<-subset(akt_preds,select=grep("/adapB_", colnames(akt_preds) , ignore.case=FALSE, fixed=T))
dim(akt_adapB)
akt_adap_adap<-subset(akt_preds,select=grep("/adap_adap_", colnames(akt_preds) , ignore.case=FALSE, fixed=T))
dim(akt_adap_adap)

min(corr.test(cbind(akt_preds,pred_drug$Sigma.AKT1.2.inhibitor),method="spearman", use="pairwise")$p[,33])


bad_preds<-subset(pred_drug,select=grep("/bad", colnames(pred_drug) , ignore.case=FALSE, fixed=T))
her2_preds<-subset(pred_drug,select=grep("/her2", colnames(pred_drug) , ignore.case=FALSE, fixed=T))
igf1r_preds<-subset(pred_drug,select=grep("/igf1r", colnames(pred_drug) , ignore.case=FALSE, fixed=T))
erk_preds<-subset(pred_drug,select=grep("/erk", colnames(pred_drug) , ignore.case=FALSE, fixed=T))
length(bad_preds)

adapB<-subset(pred_drug,select=grep("adapB",colnames(pred_drug)))
adapS<-subset(pred_drug,select=grep("adap_adap",colnames(pred_drug)))

##############

#### Bootstrap:
pathways = 80 # number of pathway signatures
samplesize = nrow(adapB) # number of cell lines
n.boot = 100 # number of bootstrap samples -- set at 10,000 or more for your final run

adapB_boot_cors = array(0,dim=c(80,1,n.boot)) # make a three dimensional array to store the bootstrap results
akt_adapB_boot_cors = akt_adap_adap_boot_cors =array(0,dim=c(16,1,n.boot))

boot.sample
test<-cor(adapB[boot.sample,1:80],pred_drug[boot.sample,171:260],use="pairwise", method="spearman")
dim(test)

# added spearman here, it did not have it 
for (i in 1:100){
  boot.sample = sample(1:samplesize,replace=T)
  akt_adapB_boot_cors[,,i]=cor(akt_adapB[boot.sample,1:16],pred_drug[boot.sample,175],use="pairwise", method="spearman")
  akt_adap_adap_boot_cors[,,i]=cor(akt_adap_adap[boot.sample,1:16],pred_drug[boot.sample,175],use="pairwise", method="spearman")
  }
adapB[1]
View(adapB_boot_cors[1,1,1])

dim(adapB_boot_cors)
dim(akt_boot_cors) #24 x 90 x 10000

#  to test 
p_calc_compare=function(path1,path2,drug,cor_cut=0,cors=boot_cors,pathlist=pathway,druglist=drugs){
  ind_p1 = which(pathlist==path1)
  ind_p2 = which(pathlist==path2)
  ind_drug = which(druglist==drug)
  mean((cors[ind_p1,ind_drug,]-cors[ind_p2,ind_drug,])>cor_cut,na.rm=T)
}


pval_comp_akt_adapB_vs_adap_adap = p_calc_compare(combn(colnames(akt_adap_adap),1),combn(colnames(akt_adapB),1),cors=akt_boot_cors, drug="Sigma.AKT1.2.inhibitor",pathlist = colnames(akt_preds),druglist = pred_drug[171:260] )
head(pval_comp)

# # means
# cor_mean = apply(boot_cors, c(1,2), mean, na.rm=T)  ## average bootstrap cors. Should be similar to the non-boot values
# dimnames(cor_mean)=dimnames(drug_prediction_correlations_multi_spear)
# View(cor_mean)
# write.table(cor_mean,"~/Documents/ThesisWork/GitRepos/bild_signatures/cor_mean.txt",sep='\t', col.names = NA,quote=F)
# cor_means_ICBP=read.delim("~/Documents/ThesisWork/GitRepos/bild_signatures/cor_mean.txt", header=1, sep='\t',row.names=1)
# 
# #lower
# lower = apply(boot_cors, c(1,2), quantile,na.rm=T,probs=.025) ## lower 95% CI
# dimnames(lower)=dimnames(drug_prediction_correlations_multi_spear)
# write.table(lower,"~/Documents/ThesisWork/GitRepos/bild_signatures/lower.txt",sep='\t', col.names = NA,quote=F)
# cor_lower_ICBP=read.delim("~/Documents/ThesisWork/GitRepos/bild_signatures/lower.txt", header=1, sep='\t',row.names=1)
# #upper
# 
# upper = apply(boot_cors, c(1,2), quantile,na.rm=T,probs=.975) ## upper 95% CI
# dimnames(upper)=dimnames(drug_prediction_correlations_multi_spear)
# write.table(upper,"~/Documents/ThesisWork/GitRepos/bild_signatures/upper.txt",sep='\t', col.names = NA,quote=F)
# cor_upper_ICBP=read.delim("~/Documents/ThesisWork/GitRepos/bild_signatures/upper.txt", header=1, sep='\t',row.names=1)


## p-values: to test that a correlation is bigger than some value:

# is this the p-value that is it bigger than some value??
 
cor_cutoff = 0 ## i.e. to test is the correlation is > or < 0. Note this can be anything, i.e. .1, .5, etc
p_calc = function(x,direction="greater",cor_cut=0){
  if (!(direction %in% c("greater","less"))){stop("Invalid value for direction")}
  if (direction=="greater"){return(mean(x>cor_cut,na.rm=T))}
  if (direction=="less"){return(mean(x<cor_cut,na.rm=T))}
  }

head(boot_cors)
# These are not p-values, or are they, they just seem like correlations above or below a certain value
# Obtaining the cor means for all 10000 interations that are either above or below a certain value for all rows and columns. 
# I think above and below equal to 1...

View(boot_cors)
# This just contains the means from the 10000 bootstrap cor values above 0
# I dont get how you can get different p-values for the same correlation?
ps_above_0 = apply(boot_cors, c(1,2), p_calc)
dimnames(ps_above_0)=dimnames(drug_prediction_correlations_multi_spear)
View(ps_above_0)
dim(ps_above_0)

ps_below_0 = apply(boot_cors, c(1,2), p_calc,direction="less")
dimnames(ps_below_0 )=dimnames(drug_prediction_correlations_multi_spear)
View(ps_below_0)
dim(ps_below_0)

## p-values: to test two correlations against each other:
pathway = colnames(pred_drug_multi)[1:25]  ## print to see the pathway names
print(pathway)
drugs = colnames(pred_drug_multi)[36:125]  ## print to see the drug names
print(drugs)

#  to test 
p_calc_compare=function(path1,path2,drug,cor_cut=0,cors=boot_cors,pathlist=pathway,druglist=drugs){
  ind_p1 = which(pathlist==path1)
  ind_p2 = which(pathlist==path2)
  ind_drug = which(druglist==drug)
  mean((cors[ind_p1,ind_drug,]-cors[ind_p2,ind_drug,])>cor_cut,na.rm=T)
}


pval_comp = p_calc_compare("AKT_BAD.adap_multi.pathway_activity_testset.csv.akt","AKT_BAD_HER2.adap_multi.pathway_activity_testset.csv.akt","Sigma.AKT1.2.inhibitor")
head(pval_comp)

 ## pval_comp = 0.91 in this case means that AKT+BAD > AKT+BAD+HER2 in 91% of the bootstrap correlations. Thus the p-value for testing Ha: AKT+BAD > AKT+BAD+HER2 is 0.09










#######################
library(psych)
for (i in 1:length(colnames(data_icbp))){
  for (j in 1:1){ #length(colnames(drug_srt))){
    cors[i,j]=corr.test(pred_drug[,i],pred_drug$Sigma.AKT1.2.inhibitor,use="pairwise",method="spearman")
  }
}

View(drug_pre_diction_correlations_multi)
View(drug_prediction_correlations_single)

single_and_multi= rbind(drug_prediction_correlations_multi,drug_prediction_correlations_single)
plot(single_and_multi[2])
View(single_and_multi)

row.names(single_and_multi)

# for sinlge
single_and_multi[26,]
cor(single_and_multi[26,], single_and_multi[27,] ) # 0.5269367
cor(single_and_multi[26,], single_and_multi[28,] ) #0.7882588
cor(single_and_multi[26,], single_and_multi[29,] ) # 0.6173746
cor(single_and_multi[27,], single_and_multi[28,] ) # 0.2896494
cor(single_and_multi[27,], single_and_multi[29,] ) # -0.02523773
cor(single_and_multi[28,], single_and_multi[29,] ) # 0.7182353

#mutli
cor(single_and_multi[22,], single_and_multi[23,] )  #-0.6161527
cor(single_and_multi[22,], single_and_multi[24,] ) # -0.2015345
cor(single_and_multi[22,], single_and_multi[25,] ) # 0.4247083
cor(single_and_multi[23,], single_and_multi[24,] ) # -0.04692151
cor(single_and_multi[23,], single_and_multi[25,] ) # -0.4218923
cor(single_and_multi[24,], single_and_multi[25,] ) # -0.7734885

write.table(single_and_multi,"~/Documents/ThesisWork/GitRepos/bild_signatures/Correlations_ICBP_Single_Multi.txt",sep='\t', col.names = NA,quote=F)

```


Creating heatmaps
```{r }

if (!require("gplots")) {
   install.packages("gplots", dependencies = TRUE)
   library(gplots)
   }
if (!require("RColorBrewer")) {
   install.packages("RColorBrewer", dependencies = TRUE)
   library(RColorBrewer)
   }
multi<-data#read.table("~/Desktop/multipathway_preds.txt", sep='\t',row.names=1,header=1)
single<-read.csv("~/Dropbox/bild_signatures/multi_icbp_expr_pc/single_pathway_results.csv", row.names=1,header=1)
my_palette <- colorRampPalette(c("darkblue","aliceblue","brown4"))(n = 299)
col_breaks = c(seq(0,0.2,length=100), seq(0.2,0.4,length=100), seq(0.4,1,length=100)) 
# creates a 5 x 5 inch image
png("heatmaps_in_r.png",    # create PNG for the heat map        
  width = 5*300,        # 5 x 300 pixels
  height = 5*300,
  res = 300,            # 300 pixels per inch
  pointsize = 8)  
comb<-cbind(multi,single)
dim(comb)
colnames(comb)<-gsub(pattern = "adap_multi.pathway_activity_testset.csv",replacement = "A",x = colnames(comb))
#colnames(comb)<-gsub(pattern = "non",replacement = "NA",x = colnames(comb))
pdf(file='~/Dropbox/bild_signatures//bild_signatures/activity_subtype.pdf')

heatmap.2(as.matrix(comb),col=my_palette,margins=c(12,9),Rowv=F,Colv=F,dendrogram="none", trace="none",main="All possibilities",breaks = col_breaks)
heatmap.2(as.matrix(comb[,47:50]),col=my_palette,trace="none",main="Multipathway activity",margins=c(12,9),Rowv =F,Colv=F,dendrogram="none",ylab="ICBP Cell lines",breaks = col_breaks)
heatmap.2(as.matrix(comb[,51:54]),margins=c(12,9),col=my_palette, Rowv=F,Colv=F,dendrogram="none",trace="none",main="Single pathway activity",ylab="ICBP Cell lines",scale = "row")

comb_drug<-merge_drop(comb,drugs,by=0)
#plot(hclust(dist(comb_drug[,1:48]), method = "complete", members = NULL))
<<<<<<< HEAD

basal<-subset(comb_drug,comb_drug$Transcriptional.subtype...ERBB2.status=="Basal")
heatmap.2(as.matrix(basal[,22:25]),col=my_palette,margins=c(12,9),dendrogram="none", trace="none",main="Basal Multi")
heatmap.2(as.matrix(basal[,26:29]),col=my_palette,margins=c(12,9),dendrogram="none",lmat=rbind( c(0, 3, 4), c(2,1,0 ) ), lwid=c(1.5, 4, 2 ), trace="none",main="Basal single")
cor(basal[,22],basal$Sigma.AKT1.2.inhibitor,use="pairwise")

her<-subset(comb_drug[,1:44],comb_drug$Transcriptional.subtype...ERBB2.status=="ERBB2-amp"|comb_drug$Transcriptional.subtype...ERBB2.status=="ERBB2Amp")
heatmap.2(as.matrix(her[,22:25]),col=my_palette,dendrogram="none",lmat=rbind( c(0, 3, 4), c(2,1,0 ) ), lwid=c(1.5, 4, 2 ), trace="none",margins=c(12,9),main="HER2 Multi")
heatmap.2(as.matrix(her[,26:29]),col=my_palette,dendrogram="none",lmat=rbind( c(0, 3, 4), c(2,1,0 ) ), lwid=c(1.5, 4, 2 ), trace="none",margins=c(12,9),main="HER2 Single",scale="column")
cor(her[,22],her$Sigma.AKT1.2.inhibitor,use="pairwise")

claudin<-subset(comb_drug,comb_drug$Transcriptional.subtype...ERBB2.status=="Claudin-low")
heatmap.2(as.matrix(claudin[,22:25]),col=my_palette,dendrogram="none",lmat=rbind( c(0, 3, 4), c(2,1,0 ) ), lwid=c(1.5, 4, 2 ), trace="none",margins=c(12,9),main="Claudin Multi")
heatmap.2(as.matrix(claudin[,26:29]),col=my_palette,dendrogram="none",lmat=rbind( c(0, 3, 4), c(2,1,0 ) ), lwid=c(1.5, 4, 2 ), trace="none",margins=c(12,9),main="Claudin Single",scale="column")
cor(claudin[,22],claudin$Sigma.AKT1.2.inhibitor,use="na.or.complete")

luminal<-subset(comb_drug,comb_drug$Transcriptional.subtype...ERBB2.status=="Luminal")
heatmap.2(as.matrix(luminal[,22:25]),col=my_palette,dendrogram="none",lmat=rbind( c(0, 3, 4), c(2,1,0 ) ), lwid=c(1.5, 4, 2 ), trace="none",margins=c(12,9),main="Luminal Multi")
heatmap.2(as.matrix(luminal[,26:29]),col=my_palette,dendrogram="none",lmat=rbind( c(0, 3, 4), c(2,1,0 ) ), lwid=c(1.5, 4, 2 ), trace="none",margins=c(12,9),main="Luminal Single",scale="row")
=======
# write(file="~/Dropbox/bild_signatures/bild_signatures/pathway prediction drug response results.xls","Correlations for pathway predictions with Lapatinib and Sigma.AKT.inhibitor in BASAL subtype",append = T)
# write('',file="~/Dropbox/bild_signatures/bild_signatures/pathway prediction drug response results.xls", append=T)
basal<-subset(comb_drug,comb_drug$Transcriptional.subtype...ERBB2.status=="Basal")
# write("For Lapatinib",file="~/Dropbox/bild_signatures/bild_signatures/pathway prediction drug response results.xls", append =T)
# write(paste(colnames(basal)[1:54],cor(basal[,1:54],basal$Lapatinib,use="pairwise.complete.obs"),sep='\t'), file="~/Dropbox/bild_signatures/bild_signatures/pathway prediction drug response results.xls", append = T)
# write("For Sigma AKT inhibitor",file="~/Dropbox/bild_signatures/bild_signatures/pathway prediction drug response results.xls", append =T)
# write(paste(colnames(basal)[1:54],cor(basal[,1:54],basal$Sigma.AKT1.2.inhibitor,use="pairwise.complete.obs"),sep='\t'),file="~/Dropbox/bild_signatures/bild_signatures/pathway prediction drug response results.xls",append = T)

par(mfrow = c(2,1))
heatmap.2(as.matrix(basal[,47:50]),col=my_palette,margins=c(12,9),dendrogram="none", trace="none",main="Basal Multi",Rowv = NULL, Colv = NULL)
heatmap.2(as.matrix(basal[,51:54]),col=my_palette,margins=c(12,9),dendrogram="none",Rowv = NULL, Colv = NULL, trace="none",main="Basal single")


her<-subset(comb_drug,comb_drug$Transcriptional.subtype...ERBB2.status=="ERBB2-amp"|comb_drug$Transcriptional.subtype...ERBB2.status=="ERBB2Amp")
# wrtie(paste(colnames(her)[1:54],cor(her[,1:54],her$Lapatinib,use="pairwise.complete.obs"),sep='\t'),file="~/Dropbox/bild_signatures/bild_signatures/pathway prediction drug response results.xls",append = T)
# write("For Sigma AKT inhibitor",file="~/Dropbox/bild_signatures/bild_signatures/pathway prediction drug response results.xls", append =T)
# write(paste(colnames(her),cor(her[,1:54],her$Sigma.AKT1.2.inhibitor,use="pairwise.complete.obs"),sep='\t'),file="~/Dropbox/bild_signatures/bild_signatures/pathway prediction drug response results.xls",append = T)
# 

heatmap.2(as.matrix(her[,43:54]),col=my_palette,dendrogram="none",lmat=rbind( c(0, 3, 4), c(2,1,0 ) ), lwid=c(1.5, 4, 2 ), trace="none",margins=c(14,9),main="HER2 Multi",Rowv=F, Colv=F)
heatmap.2(as.matrix(her[,51:54]),col=my_palette,dendrogram="none",lmat=rbind( c(0, 3, 4), c(2,1,0 ) ), lwid=c(1.5, 4, 2 ), trace="none",margins=c(12,9),main="HER2 Single",Rowv=F, Colv=F,scale = "row")


claudin<-subset(comb_drug,comb_drug$Transcriptional.subtype...ERBB2.status=="Claudin-low")
cor(claudin[,1:54],claudin$Lapatinib,use="pairwise.complete.obs")# variance zero in this group
cor(claudin[,1:54],claudin$Sigma.AKT1.2.inhibitor,use="pairwise.complete.obs")

heatmap.2(as.matrix(claudin[,47:50]),col=my_palette,dendrogram="none",trace="none",margins=c(12,9),main="Claudin Multi",,Rowv=F, Colv=F)
heatmap.2(as.matrix(claudin[,51:54]),col=my_palette,dendrogram="none", trace="none",margins=c(12,9),main="Claudin Single",scale="row",,Rowv=F, Colv=F)
cor(claudin[,22],claudin$Sigma.AKT1.2.inhibitor,use="na.or.complete")

luminal<-subset(comb_drug,comb_drug$Transcriptional.subtype...ERBB2.status=="Luminal")
cor(luminal[,47:50],luminal$Lapatinib,use="pairwise.complete.obs")
cor(luminal[,51:54],luminal$Sigma.AKT1.2.inhibitor,use="pairwise.complete.obs")
heatmap.2(as.matrix(luminal[,47:50]),col=my_palette,dendrogram="none", trace="none",margins=c(12,9),main="Luminal Multi",Rowv=F, Colv=F)
heatmap.2(as.matrix(luminal[,47:50]),col=my_palette,dendrogram="none",trace="none",margins=c(12,9),main="Luminal Single",scale="row",Rowv=F, Colv=F)
>>>>>>> 2fac797b6fb95768996bf82bab2763ae0f043efa
cor(luminal[,22],luminal$Sigma.AKT1.2.inhibitor,use="na.or.complete")
multi_4<-rbind(basal[,43:46],her[,43:46],claudin[,43:46],luminal[,43:46])
png("heatmaps_multi_adap.png",width = 5*300,height = 5*300,res = 800, pointsize = 8)  
heatmap.2(as.matrix(multi_4), RowSideColors = c(rep("gray", length(rownames(basal))),rep("blue", length(rownames(her))),rep("black", length(rownames(claudin))),rep("green",length(rownames(luminal)))),col=my_palette,dendrogram="none", trace="none",margins=c(15,10),main="Multi Preds within Subtypes",scale="row",Rowv=F)
par(lend = 10)           # square line ends for the color legend
legend("topright",legend = c("Basal", "HER2", "Claudin","Luminal"), col = c("gray", "blue", "black","green"),  lty= 1,lwd = 10)
dev.off()
single_4<-rbind(basal[,51:54],her[,51:54],claudin[,51:54],luminal[,51:54])
heatmap.2(as.matrix(single_4), RowSideColors = c(rep("gray", length(rownames(basal))),rep("blue", length(rownames(her))),rep("black", length(rownames(claudin))),rep("green",length(rownames(luminal)))),col=my_palette,dendrogram="none", trace="none",margins=c(12,9),main="Single Preds within Subtypes",scale="row",Rowv=F)
par(lend = 10)           # square line ends for the color legend
legend("topright",legend = c("Basal", "HER2", "Claudin","Luminal"), col = c("gray", "blue", "black","green"),  lty= 1,lwd = 10)

dev.off()
```

```{r echo=FALSE}
time<-format(Sys.time(),"%a %b %d %X %Y")
```
This analysis was run on `r time` 
