library(sva)
library(ASSIGN)
library(data.table)
library(devtools)
install_github("wevanjohnson/ASSIGN",ref="adapt_gene_only")
library(ASSIGN)
source('~/Dropbox/bild_signatures/bild_signatures/Rmarkdowns_scripts//Key_ASSIGN_functions.Rmd', echo=TRUE)
ovca<-data.frame(fread("~/Dropbox/Datasets/OVCA_in_SYMBOLs.txt"),row.names=1,check.names = F)
skcm<-data.frame(fread("~/Dropbox/Datasets/SKCM_TPMlog_RNA-seq.txt"),row.names=1,check.names = F)
dim(skcm)
#setwd("~/Dropbox/bild_signature/Datasets/")
expr<-as.matrix(read.table("~/Dropbox/Datasets/GFP18_AKT_BAD_HER2_IGF1R_RAF_ERK.tpmlog",sep='\t',row.names=1,header=1))
control<-subset(expr, select=GFP.1:GFP.12)
her2<-subset(expr, select=HER2.1:HER2.6)
akt<-subset(expr,select=AKT.1:AKT.6)
bad<-subset(expr,select=BAD.1:BAD.6)
igf1r<-subset(expr,select=IGF1R.1:IGF1R.6)
erk<-subset(expr,select=ERK.1:ERK.6)
expr_all<-cbind(control,akt,bad,her2,igf1r,erk)
dim(expr_all)
expr_all_f <-expr_all[apply(expr_all[,1:41]==0,1,mean) < 0.85,]
dim(expr_all_f)
expr_all_skcm_f<-merge_drop(expr_all_f,skcm,by=0)
dim(expr_all_skcm_f)
sub<-c(12,6,6,5,6,6,373)
pdf("pca_plots_skcm.pdf")
pcaplot(expr_all_skcm_f,sub,scale = T)
bat1<-as.matrix(cbind(c(colnames(expr_all_f),colnames(skcm)),c(rep(1,length(colnames(expr_all_f))),rep(2,length(colnames(skcm))))))
combat_expr1<-ComBat(dat=expr_all_skcm_f, batch=bat1[,2], mod=NULL, numCovs=NULL)
pcaplot(combat_expr1,sub,scale = T)
c_gfp<-subset(combat_expr1, select=GFP.1:GFP.12)
c_akt<-subset(combat_expr1, select=AKT.1:AKT.6)
c_bad<-subset(combat_expr1, select=BAD.1:BAD.6)
c_her2<-subset(combat_expr1, select=HER2.1:HER2.6)
c_igf1r<-subset(combat_expr1, select=IGF1R.1:IGF1R.6)
c_erk<-subset(combat_expr1, select=ERK.1:ERK.6)
c_test<-combat_expr1[,42:ncol(combat_expr1)]
dim(c_test)
basedir="~/Dropbox/bild_signatures/skcm"
dir.create(basedir)
#basedir=getwd()
dir.create( basedir)
setwd(basedir)
# ERK single
trainingLabele<-list(control=list(erk=1:12),erk=13:18)
sub_dir<-paste(basedir,"erk_gene_list",sep='/')
dir.create( sub_dir)
assign_easy_multi(trainingData = cbind(c_gfp,c_erk),test=c_test,trainingLabel1 = trainingLabele,g=250,out_dir_base = sub_dir,single = 1)
# 4 pathways
trainbihe<-cbind(c_gfp,c_bad,c_igf1r,c_her2,c_erk)
trainingLabelbihe<-list(control=list(bad=1:12,igf1r=1:12,her2=1:12,erk=1:12),bad=13:18, igf1r=19:24,her2=25:29,erk=30:35)
sub_dir=paste(basedir,"bad_igf1r_her2_erk",sep='/')
dir.create(sub_dir)
assign_easy_multi(trainingData = trainbihe,test=c_test,trainingLabel1 = trainingLabelbihe,g=c(150,100,15,100),out_dir_base = sub_dir)

#Multi_5
trainhall5<-cbind(c_gfp,c_akt,c_bad,c_her2,c_igf1r, c_erk)
trainingLabelall5<-list(control=list(akt=1:12,bad=1:12,her2=1:12,igf1r=1:12, erk=1:12),akt=13:18, bad=19:24,her2=25:29,igf1r=30:35, erk=36:41)
sub_dir=paste(basedir,"akt_bad_her2_igf1r_erk",sep='/')
dir.create(sub_dir)
assign_easy_multi(trainingData = trainhall5,test=c_test,trainingLabel1 = trainingLabelall5,g=c(150,150,15,100,100),out_dir_base = sub_dir)

############ovca analysis.didn't work.Signatures were too messy!!Don't trust the predictions####
expr_all_ovca_f<-merge_drop(expr_all_f,ovca,by=0)
sub<-c(12,6,6,5,6,6,28)
pdf("pca_plots.pdf")
pcaplot(expr_all_ovca_f,sub,scale = F)
bat1<-as.matrix(cbind(c(colnames(expr_all_f),colnames(ovca)),c(rep(1,length(colnames(expr_all_f))),rep(2,length(colnames(ovca))))))
combat_expr1<-ComBat(dat=expr_all_ovca_f, batch=bat1[,2], mod=NULL, numCovs=NULL)
pcaplot(combat_expr1,sub,scale = F)
dev.off()
c_gfp<-subset(combat_expr1, select=GFP.1:GFP.12)
c_akt<-subset(combat_expr1, select=AKT.1:AKT.6)
c_bad<-subset(combat_expr1, select=BAD.1:BAD.6)
c_her2<-subset(combat_expr1, select=HER2.1:HER2.6)
c_igf1r<-subset(combat_expr1, select=IGF1R.1:IGF1R.6)
c_erk<-subset(combat_expr1, select=ERK.1:ERK.6)
c_test<-combat_expr1[,42:69]
basedir="~/Dropbox/bild_signatures/ovca"
basedir=getwd()
dir.create( basedir)
# ERK single
trainingLabele<-list(control=list(erk=1:12),erk=13:18)
sub_dir<-paste(basedir,"erk",sep='/')
dir.create( sub_dir)
assign_easy_multi(trainingData = cbind(c_gfp,c_erk),test=c_test,trainingLabel1 = trainingLabele,g=100,out_dir_base = sub_dir,single = 1)

#Multi_5
trainhall5<-cbind(c_gfp,c_akt,c_bad,c_her2,c_igf1r, c_erk)
trainingLabelall5<-list(control=list(akt=1:12,bad=1:12,her2=1:12,igf1r=1:12, erk=1:12),akt=13:18, bad=19:24,her2=25:29,igf1r=30:35, erk=36:41)
sub_dir=paste(basedir,"akt_bad_her2_igf1r_erk",sep='/')
dir.create(sub_dir)
assign_easy_multi(trainingData = trainhall5,test=c_test,trainingLabel1 = trainingLabelall5,g=c(150,150,15,100,100),out_dir_base = sub_dir)
