---
title: "Pathway predictions in TCGA BRCA samples based on subtypes"
output: html_document
---

```{r include=FALSE}

##Load the packages required for heatmap
if (!require("gplots")) {
   install.packages("gplots", dependencies = TRUE)
   library(gplots)
   }
if (!require("RColorBrewer")) {
   install.packages("RColorBrewer", dependencies = TRUE)
   library(RColorBrewer)
}
if (!require("data.table")) {
   install.packages("data.table", dependencies = TRUE)
   library(data.table)
}
if (!require("mclust")) {
   install.packages("mclust", dependencies = TRUE)
   library(mclust)
}

source('~/Documents/bild_signatures/Rmarkdowns_scripts//Key_ASSIGN_functions.Rmd', echo=TRUE)

icbp_pi3k_225 <- read.csv("~/Documents/bild_signatures/PI3KPredictions/icbp_pi3k_225_gene_pathway_activity_testset.csv")
tcga_pi3k_225 <- read.csv("~/Documents/bild_signatures/PI3KPredictions/tcga_pi3k_225_gene_pathway_activity_testset.csv", row.names=1)
View(tcga_pi3k_225)
plot(icbp_pi3k_225)
View(tcga_pi3k_225)
brca_subtypes<-read.table("~/Downloads//BRCA.547.PAM50.SigClust.Subtypes.txt",header=1,row.names=1, sep='\t')
subtypes_preds<-merge_drop(brca_subtypes,tcga_pi3k_225 )
boxplot2(subtypes_preds[,4]~subtypes_preds$PAM50,col=c(2,4,5,5,6),ylab="PI3K Activity",ylim=c(0,1),las=1)


# Pi3K muations seperation
brca_mut<-t(read.table("~/Downloads/TCGA_PANCAN_mut.txt",header=1,row.names=1, sep='\t', check.names = F))
longnames=rownames(subtypes_preds)
new_longnames=NULL
counter=0
for (j in 1:length(longnames)){
  new_longnames[j]<-paste(strsplit(longnames[j],"-")[[1]][1:3],collapse = "-")
}
subtypes_preds$Short_names=new_longnames
subtypes_preds_mut<-merge(subtypes_preds,brca_mut,by.x=5,by.y=0)
colnames(subtypes_preds_mut)
boxplot(subtypes_preds_mut[,5]~subtypes_preds_mut$PIK3CA,ylab="PI3K Activity",names=c("No PIK3CA\nmutation","PIK3CA\nmutation"))
t.test(subtypes_preds_mut[,5]~subtypes_preds_mut$PIK3CA)





prot_brca<-read.csv("~/Dropbox/bild_signatures/Datasets/TCGA-BRCA-RBN.csv",header=1,check.names = F)

dev.off()



```




Survival analysis with TCGA BRCA data...
```{r}
bad_status<-pred_sub[,147]
bad_cutoff<- median(pred_sub[,147])
for(i in 1:length(bad_status)){
  if(bad_status[i]< bad_cutoff){
    bad_status[i]="Low"}
  else{
    bad_status[i]="High"}
  }
pred_sub$bad_status<-bad_status
fit<-survfit(Surv(pred_sub$OS.Time,pred_sub$OS.event)~pred_sub$bad_status)
plot(fit,col=c(3:2), xlab="Time in days",ylab="Survival probability",main="Survival in TCGA BRCA\n patients based on BAD pathway status")
legend("topright",c("High","Low"),col=3:2,lwd=4,box.lwd = 1)
survdiff(Surv(pred_sub$OS.Time,pred_sub$OS.event)~pred_sub$bad_status,rho=0)


erk_status<-pred_sub[,160]
erk_cutoff<-median(pred_sub[,160])
for(i in 1:length(erk_status)){
  if(erk_status[i] < erk_cutoff){
    erk_status[i]="Low"}
  else{
    erk_status[i]="High"}
  }
pred_sub$erk_status<-erk_status
fit<-survfit(Surv(pred_sub$OS.Time,pred_sub$OS.event)~pred_sub$erk_status)
plot(fit,col=c(2:3), xlab="Time in days",ylab="Survival probability",main="Survival in TCGA BRCA\n patients based on ERK pathway status")
legend("topright",c("High","Low"),col=2:3,lwd=4,box.lwd = 1)

#mtext(side=1,line = 2,at=c(5,7),"p=",col = "red")

#summary(fit)
survdiff(Surv(pred_sub$OS.Time,pred_sub$OS.event)~pred_sub$erk_status,rho=0)

basal<-subset(pred_sub[,c(133,147,37,106,145,150,179,180,191,192)],pred_sub$PAM50.mRNA.x=="Basal-like")
her<-subset(pred_sub[,c(133,147,37,106,145,150,179,180,191,192)],pred_sub$PAM50.mRNA.x=="HER2-enriched")
luminal<-subset(pred_sub[,c(133,147,37,106,145,150,179,180,191,192)],pred_sub$PAM50.mRNA.x=="Luminal A"|pred_sub$PAM50.mRNA.x=="Luminal B")
normal<-subset(pred_sub[,c(133,147,37,106,145,150,179,180,191,192)],pred_sub$PAM50.mRNA.x=="Normal-like")

fit<-survfit(Surv(basal$OS.Time,basal$OS.event)~basal$bad_status)
plot(fit,col=c(2:3), xlab="Time in days",ylab="Survival probability",main="Basal TCGA BRCA\n patients based on BAD pathway status")
legend("topright",c("High","Low"),col=2:3,lwd=4,box.lwd = 1)
survdiff(Surv(basal$OS.Time,basal$OS.event)~basal$bad_status,rho=0)
mtext(side=1,line = 2,at=c(5,7),"p=0.0767",col = "red")

```

```{r}
proteomics_cell_tcga<-read.csv("~/Dropbox/bild_signatures/Datasets/TCGA-BRCA-RBN.csv", header=1)
proteomics_cell_tcga$TCGA_patient_barcode<-short_to_long_TCGA_id(longnames = rownames(pred_sub),shortnames = gsub(pattern = "-",replacement = ".",proteomics_cell_tcga$TCGA_patient_barcode))
rownames(proteomics_cell_tcga)<-proteomics_cell_tcga$TCGA_patient_barcode

tcga_pred_prot<-merge(best_predictors,proteomics_cell_tcga,by.x=0,by.y = 1)

#####AKT correlation with TCGA proteomica data
cor(as.numeric(tcga_pred_prot$Akt_pS473),as.numeric(tcga_pred_prot[,2]),method = "spearman")#
cor(tcga_pred_prot$Akt,tcga_pred_prot[,2], method="spearman")#
cor(tcga_pred_prot$Akt_pT308,tcga_pred_prot[,2], method="spearman")#

#######BAD correlation with TCGA proteomics data

cor(tcga_pred_prot$Bad_pS112,tcga_pred_prot[3],method="spearman")##pS112 inactivates bad
cor(tcga_pred_prot$Bcl.xL,tcga_pred_prot[3],method="spearman")
cor(tcga_pred_prot$Bcl.2,tcga_pred_prot[3],method="spearman")

#####ERK correlation with TCGA proteomics data
cor(tcga_pred_prot$MAPK_pT202_Y204,tcga_pred_prot[,6], method="spearman")#igf1r_her2_erk/adap_adap_multi/erk


######HER2 correlation with TCGA proteomics data

cor(tcga_pred_prot$HER2_pY1248,tcga_pred_prot[,5], method="spearman")#"her2_bad_igf1r/adapB_multi/her2"  
cor(tcga_pred_prot$HER2,tcga_pred_prot[,5], method="spearman")#"her2_igf1r/adapB_multi/her2"    

#######IGF1R correlation with TCGA proteomics data
cor(tcga_pred_prot$IRS1,tcga_pred_prot[,4], method="spearman")#"akt_bad_her2_igf1r_erk/adap_adap_multi/igf1r"

```


```{r echo=FALSE}
time<-format(Sys.time(),"%a %b %d %X %Y")
```
This analysis was run on `r time` 

