---
title: "RALA_Validation"
author: "Shelley"
date: "November 20, 2014"
output: html_document
---

Goal: Determine if the RALA and JNK1(MAPK8) signature is okay. 


What is the function of RalA? Role in cancer? What pathways does it activate?



What is the function of JNK1? Role in cancer? What pathways does it activate?




1) Find a validation dataset
  
*LINCS- Library of Integrated Network-based Ceullular Signatures*

-What is L1000? measuring the expression levels of approximately one thousand landmark genes, and using a computational model trained on more than one hundred thousand microarray experiments to infer the activity of the other genes,

- looks like LINCS has knock out data on RALA on but I cannot figure out how to downloand it and I think it might b microarray only (find out).

- Merge the 1000 genes from the L1000 with our RNA-seq data (where to find these?) and run their values for the RALA / JNK9 knock out microarray and our RNA- seq values in binReg to see if binReq can predict that signature as down for RALA

- Also try the Overexpression data and our RNA-seq values in binReg 

- Do I need covert to UPC? Guess not just try it!

- Or just input the genes from the model into LINCS. (are the up really up and the down really down?)

**ICBP** Are there any drugs we can look at that target RALA and JNK1?

**GEO data sets:**Use the GEO signature that was used to make the MSigDB. Merge with our genes. 
   
2) Run bigReg on the Adira server with the newly created runBinRegs script with the function


*RALA Results*

How does the heatmap look? Good, some variabiltiy in the controls. Looks like there are alot most genes down than up. 

Which binReg paramters looked the best?

All that have 2 meta genes have hugggge error bars

1Metagene_DWD: Looks the best, and error bars actaully got tigher with the more genes you add. 
1Metagene_DWD BILD: ALL ICBP samples group with the controls
1Metagene_Quantile: All ICBP samples group with the activated

Is the signature just as good when you add more genes? Yes




*JNK1 Results*

How did the heatmap look?  Looks really clean between replicates. More genes down that up in activated. 

Which binReg paramters looked the best? 

All that have 2 meta genes have hugggge error bars, but the DWD bild put them all in the middle. 

1Metagene_DWD: Looks the best,form a nice curve, looks the same when you add more genes you add. 
1Metagene_DWD BILD: ALL ICBP samples group with the controls
1Metagene_Quantile: All ICBP samples group with the activated

Is the signature just as good when you add more genes? yeah

What are the GO terms associated with the model?


3) Run binReg again to get the actually genes.



4) What are the Gene Ontology Terms associated with the two signatures?

**RALA**

**JNK1**

