---
title: "Heatmaps of pathway predictions in TCGA BRCA samples based on subtypes"
output: html_document
---

```{r include=FALSE}

source('~/Dropbox/bild_signatures/bild_signatures/Rmarkdowns_scripts//Key_ASSIGN_functions.Rmd', echo=TRUE)
setwd("~/Dropbox/bild_signatures/tcga_15_mar_all/")
filenames_tcga_multi<-system("ls */*/pathway_activity_testset*", intern=TRUE)
filenames_tcga_multi

for(i in 1:length(filenames_tcga_multi))
  {
   f<-read.csv(filenames_tcga_multi[i], header=1,row.names=1) ###reading in the filess one at a time
   colnames(f)<-paste(filenames_tcga_multi[i],colnames(f),sep='/')
   if(i==1){
     data_tcga<-f
     }
   else{
     data_tcga<-cbind(data_tcga,f)
    }
  }

head(data_tcga)
dim(data_tcga)
colnames(data_tcga)<-gsub(pattern = "/pathway_activity_testset.csv",replacement = "",x = colnames(data_tcga))
head(data_tcga)

```


```{r include=FALSE}

if (!require("gplots")) {
   install.packages("gplots", dependencies = TRUE)
   library(gplots)
   }
if (!require("RColorBrewer")) {
   install.packages("RColorBrewer", dependencies = TRUE)
   library(RColorBrewer)
   }
prediction_heatmap<-function(x,type=NULL)
{
  
  adapB_single=subset(x,select=grep("adapB_single",colnames(x)))
  adap_adap_single=subset(x,select=grep("adap_adap_single",colnames(x)))
  adapB_multi=subset(x,select=grep("akt_bad_her2_igf1r_erk/adapB",colnames(x)))
  adap_adap_multi=subset(x,select=grep("akt_bad_her2_igf1r_erk/adap_adap",colnames(x)))
  adapB_multi4=subset(x,select=grep("akt_bad_her2_igf1r/adapB",colnames(x)))
  adap_adap_multi4=subset(x,select=grep("akt_bad_her2_igf1r/adap_adap",colnames(x)))
  colnames(adapB_single)=colnames(adap_adap_single)=c("AKT","BAD","ERK","HER2","IGF1R")
  adapB_single= adapB_single[,c("AKT","BAD","HER2","IGF1R","ERK")]
  adap_adap_single=adap_adap_single[,c("AKT","BAD","HER2","IGF1R","ERK")]
  colnames(adapB_multi)=colnames(adap_adap_multi)=c("AKT","BAD","HER2","IGF1R","ERK")
  colnames(adapB_multi4)=colnames(adap_adap_multi4)=c("AKT","BAD","HER2","IGF1R")

  heatmap.2(as.matrix(adapB_single),col=my_palette,margins=c(15,9),dendrogram="none", trace="none",main=paste(type,"Single Adap BG",sep = "\n"),Rowv = NULL, Colv = NULL,density.info = "none",scale = 'row')#cellnote = round(x[,43:46],digits = 2),notecol = 'black'
 heatmap.2(as.matrix(adap_adap_single),col=my_palette,margins=c(15,9),dendrogram="none", trace="none",main=paste(type,"Single Adap BGSG",sep = "\n"),Rowv = NULL, Colv = NULL,density.info = "none",scale = 'row')#cellnote = round(x[,43:46],digits = 2),notecol = 'black
  heatmap.2(as.matrix(adapB_multi),col=my_palette,margins=c(15,9),dendrogram="none",Rowv = NULL, Colv = NULL, trace="none",main=paste(type,"Multi Adap BG",sep = "\n"),density.info = 'none',scale = 'row')#,cellnote = round(x[,51:54],digits = 2),notecol = 'black',
 heatmap.2(as.matrix(adap_adap_multi),col=my_palette,margins=c(15,9),dendrogram="none",Rowv = NULL, Colv = NULL, trace="none",main=paste(type,"Multi Adap BGSG",sep = "\n"),density.info = 'none',scale = 'row')#,cellnote = round(x[,51:54],digits = 2),notecol = 'black',
 heatmap.2(as.matrix(adapB_multi4),col=my_palette,margins=c(15,9),dendrogram="none",Rowv = NULL, Colv = NULL, trace="none",main=paste(type,"Multi 4 Adap BG",sep = "\n"),density.info = 'none',scale = 'row')#,cellnote = round(x[,51:54],digits = 2),notecol = 'black',
 heatmap.2(as.matrix(adap_adap_multi4),col=my_palette,margins=c(15,9),dendrogram="none",Rowv = NULL, Colv = NULL, trace="none",main=paste(type,"Multi 4 Adap BGSG",sep = "\n"),density.info = 'none',scale = 'row')#,cellnote = round(x[,51:54],digits = 2),notecol = 'black',
 
}
correlation_heatmap<-function(x,drugs_names=NULL,type=NULL)
{
  adapB_single=subset(x,select=grep("adapB_single",colnames(x)))
  adap_adap_single=subset(x,select=grep("adap_adap_single",colnames(x)))
  adapB_multi=subset(x,select=grep("akt_bad_her2_igf1r_erk/adapB",colnames(x)))
  adap_adap_multi=subset(x,select=grep("akt_bad_her2_igf1r_erk/adap_adap",colnames(x)))
  cors = pval=matrix(-2,20,7)
  #rownames(cors)=c(colnames(x)[43:46],colnames(x)[51:54])#selecting the adaptive multipathway and single pathway prediction columns
  pathways<-cbind(adapB_single,adap_adap_single,adapB_multi,adap_adap_multi)
  drugs<-subset(x,select=drugs_names)
  colnames(cors)=drugs_names
  rownames(cors)=colnames(pathways)
  rownames(cors)=gsub(pattern = "akt_bad_her2_igf1r_erk/",replacement = "",x = rownames(cors))
  #rownames(cors)=gsub(pattern = "*/*/adapB",replacement = "B",x = rownames(cors))
  
  for (i in 1:20){
    for (j in 1:length(colnames(drugs))){
      ci=cor.ci(cbind(pathways[,i],drugs[,j]),method="spearman",plot=F)
      cors[i,j]=ci$rho[2,1]
      print(cors[i,j]);print(ci$ci[[5]])
      pval[i,j]=ci$ci[[5]]
    }
  }
  par(mar=c(1, 0.5, 3, 10),lwd=4)

heatmap.2(as.matrix(cors),col=redgreen,margins =c(13,18),dendrogram="none",Rowv = NULL, Colv = NULL, trace="none",main=paste("Correlations of pathway"," drug response in",type,sep='\n '),cellnote = round(cors,digits = 2),notecol = 'black',density.info = 'none')
}
pam50<-read.table("~/Dropbox/Datasets/tcga_breast_pam50.txt",sep='\t', stringsAsFactors = T,header=T, row.names=1)
partial_sample_names<-rownames(pam50)
sample_names<-rownames(data_tcga)
counter=0
for (j in 1:length(partial_sample_names)){
    if(!is.na(pmatch(partial_sample_names[j],sample_names))){
      partial_sample_names[j]<-sample_names[pmatch(partial_sample_names[j],sample_names, duplicates.ok=F)]  
      counter=counter+1
    }
}
rownames(pam50)<-partial_sample_names
my_palette <- colorRampPalette(c("darkblue","aliceblue","brown4"))(n = 299)
col_breaks = c(seq(0,0.2,length=100), seq(0.2,0.4,length=100), seq(0.4,1,length=100)) 

pred_sub<-merge_drop(data_tcga,pam50,by=0)
colnames(pred_sub)<-gsub(pattern = "pathway_activity_testset.csv",replacement = "",x = colnames(pred_sub))
```

Creating  heatmaps for predictions within subtypes

```{r}
basal<-subset(pred_sub,pred_sub$PAM50.mRNA=="Basal-like")
prediction_heatmap(x=basal,type = "Basal")

her<-subset(pred_sub,pred_sub$PAM50.mRNA=="HER2-enriched")
prediction_heatmap(x=her,type = "ERBB2 Amplified")

luminal<-subset(pred_sub,pred_sub$PAM50.mRNA=="Luminal A"|pred_sub$PAM50.mRNA=="Luminal B")
prediction_heatmap(x=luminal,type = "Luminal")
normal<-subset(pred_sub,pred_sub$PAM50.mRNA=="Normal-like")
prediction_heatmap(x=normal,type = "Normal-like")
```


```{r echo=FALSE}
time<-format(Sys.time(),"%a %b %d %X %Y")
```
This analysis was run on `r time` 

