---
title: "TCGA_ASSIGN"
author: "Mumtahena Rahman"
date: "January 23, 2015"
output: html_document
---
---
title: "multipathway_ASSIGN"
author: "Mumtahena Rahman"
date: "December 23, 2014"
output: pdf_document
---


```{r,echo=FALSE,cache=TRUE,include=FALSE}
library(sva)
library(ASSIGN)
merge_drop<-function(x,y,by=0)
{
  new_m<-merge(x,y,by=by)
  rownames(new_m)<-new_m$Row.names
  return(new_m[,2:length(colnames(new_m))])
}

pcaplot<-function(mat,sub){
  if(sum(sub)!=length(mat))
    {
    print("verify the subscripts...exiting now")
    }
  else{
    pca_mat <- prcomp(t(mat), center=T,scale=T)
    plot(pca_mat)
    plot(pca_mat$x[,1],pca_mat$x[,2])
    for(i in 1:length(sub))
      {
      #print(rownames(pca_mat$x)[index:sub[i]+index-1],"has color", )
      print(i)
      if(i==1)
        {
        points(pca_mat$x[1:sub[i]],pca_mat$x[1:sub[i],2],col=i)
        }
      else if(i==length(sub))
         {
         points(pca_mat$x[sum(sub[1:i-1]):length(rownames(pca_mat$x))],pca_mat$x[sum(sub[1:i-1]):length(rownames(pca_mat$x)),2],col=i)
        }
       else
        {
          
        points(pca_mat$x[sum(sub[1:i-1]):sum(sub[1:i])],pca_mat$x[sum(sub[1:i-1]):sum(sub[1:i]),2],col=i)
        }
      }
  }
}
assign_easy_multi<-function(trainingData=train, testData=test, trainingLabel1=NULL,g=100,out_dir_base="~/Desktop/tmp",cov=0){
if(cov==0){
  adap_folder<-paste(out_dir_base,paste( "adap_multi",sep=''),sep='/')
  dir.create(file.path(out_dir_base,paste( "adap_multi",sep='')))
  nonadap_folder<-paste(out_dir_base,paste( "nonadap_multi",sep=''),sep='/')
  dir.create(file.path(out_dir_base,paste( "nonadap_multi",sep='')))
  }
else{
  adap_folder<-paste(out_dir_base,paste( "adap_cov",sep=''),sep='/')
  dir.create(file.path(out_dir_base,paste( "adap_cov",sep='')))
  nonadap_folder<-paste(out_dir_base,paste( "nonadap_cov",sep=''),sep='/')
  dir.create(file.path(out_dir_base,paste( "nonadap_cov",sep='')))
}

set.seed(1234)
assign.wrapper(trainingData=trainingData, testData=testData, trainingLabel=trainingLabel1, testLabel=NULL, geneList=NULL, n_sigGene=g, adaptive_B=T, adaptive_S=F, mixture_beta=F, outputDir=adap_folder, theta0=0.05, theta1=0.9, iter=10000, burn_in=1000)  

set.seed(1234)
assign.wrapper(trainingData=trainingData, testData=testData, trainingLabel=trainingLabel1, testLabel=NULL, geneList=NULL, n_sigGene=g, adaptive_B=F, adaptive_S=F, mixture_beta=F, outputDir=nonadap_folder, theta0=0.05, theta1=0.9, iter=10000, burn_in=1000)  

}

```
Reading in the signature datasets...
```{r include=FALSE,echo=FALSE}
setwd("~/Dropbox/bild_signatures/Datasets/")
expr<-as.matrix(read.table("GFP18_AKT_BAD_HER2_IGF1R_RAF_ERK.tpmlog",sep='\t',row.names=1,header=1))
control<-subset(expr, select=GFP.1:GFP.12)
her2<-subset(expr, select=HER2.1:HER2.6)
akt<-subset(expr,select=AKT.1:AKT.6)
bad<-subset(expr,select=BAD.1:BAD.6)
igf1r<-subset(expr,select=IGF1R.1:IGF1R.6)
expr_all<-cbind(control,akt,bad,her2,igf1r)
tcga<-as.matrix(read.table("~/Dropbox/Datasets/TCGA20_brca_1_23.txt", sep='\t', stringsAsFactors=T, header=1, row.names=1))
expr_all_f <-expr_all[apply(expr_all[,1:35]==0,1,mean) < 0.85,]
dim(expr_all_f)
expr_all_tcga_f<-merge_drop(expr_all_f,tcga,by=0)
sub<-c(12,6,6,5,6,length(colnames(tcga)))
pdf(file='~/Dropbox/bild_signatures/bild_signatures/tcga_hmec_pca_plot.pdf')
pcaplot(expr_all_tcga_f,sub)
bat1<-as.matrix(cbind(c(colnames(expr_all_f),colnames(tcga)),c(rep(1,length(colnames(expr_all_f))),rep(2,length(colnames(tcga))))))
#bat1
combat_expr1<-ComBat(dat=expr_all_tcga_f, batch=bat1[,2], mod=NULL, numCovs=NULL)
pcaplot(combat_expr1,sub)
dev.off()
c_gfp<-subset(combat_expr1, select=GFP.1:GFP.12)
c_akt<-subset(combat_expr1, select=AKT.1:AKT.6)
c_bad<-subset(combat_expr1, select=BAD.1:BAD.6)
c_her2<-subset(combat_expr1, select=HER2.1:HER2.6)
c_igf1r<-subset(combat_expr1, select=IGF1R.1:IGF1R.6)
```
Now running ASSIGN with multiple pathways..
```{r}
#############running single pathway assign predictions#################
#1.HER2
trainh<-cbind(c_gfp,c_her2)
testh<-combat_expr1[,36:ncol(combat_expr1)]
trainingLabelh<-list(control=list(her2=1:12),her2=13:17)
dir.create("~/Dropbox/bild_signatures/multi_tcga_expr_pc/single")
setwd("~/Dropbox/bild_signatures/multi_tcga_expr_pc/single")
dir.create( "Her2")
# 
assign_easy_multi(trainingData = trainh,test=testh,trainingLabel1 = trainingLabelh,g=c(15),out_dir_base = "Her2")

#2. AKT
traina<-cbind(c_gfp,c_akt)
testa<-combat_expr1[,36:ncol(combat_expr1)]
trainingLabela<-list(control=list(akt=1:12),akt=13:18)
dir.create( "AKT")
# 
assign_easy_multi(trainingData = traina,test=testa,trainingLabel1 = trainingLabela,g=c(150),out_dir_base = "AKT")

#3. BAD
trainb<-cbind(c_gfp,c_bad)
testb<-combat_expr1[,36:ncol(combat_expr1)]
trainingLabelb<-list(control=list(bad=1:12),bad=13:18)
dir.create( "BAD")
# 
assign_easy_multi(trainingData = trainb,test=testb,trainingLabel1 = trainingLabelb,g=c(150),out_dir_base = "BAD")

#4. IGF1R
traini<-cbind(c_gfp,c_igf1r)
testi<-combat_expr1[,36:ncol(combat_expr1)]
trainingLabeli<-list(control=list(igf1r=1:12),igf1r=13:18)
dir.create( "IGF1R")
# 
assign_easy_multi(trainingData = traini,test=testi,trainingLabel1 = trainingLabeli,g=c(100),out_dir_base = "IGF1R")

#############trying two pathways at a time in multipathway#############
#1. HER2 & AKT
trainha<-cbind(c_gfp,c_akt,c_her2)
testha<-combat_expr1[,36:ncol(combat_expr1)]
trainingLabelha<-list(control=list(akt=1:12,her2=1:12),akt=13:18,her2=19:23)
setwd("~/Dropbox/bild_signatures/multi_tcga_expr_pc/")
dir.create( "Her2_AKT")
# 
assign_easy_multi(trainingData = trainha,test=testha,trainingLabel1 = trainingLabelha,g=c(150,15),out_dir_base = "Her2_AKT/")

#2. HER2 & BAD

trainhb<-cbind(c_gfp,c_bad,c_her2)
testhb<-combat_expr1[,36:90]
trainingLabelhb<-list(control=list(bad=1:12,her2=1:12),bad=13:18,her2=19:23)
dir.create( "Her2_BAD")
# 
assign_easy_multi(trainingData = trainhb,test=testhb,trainingLabel1 = trainingLabelhb,g=c(150,15),out_dir_base = "Her2_BAD")

#3. HER2 & IGF1R
trainhi<-cbind(c_gfp,c_igf1r,c_her2)
testhi<-combat_expr1[,36:90]
trainingLabelhi<-list(control=list(igf1r=1:12,her2=1:12),igf1r=13:18,her2=19:23)
dir.create( "~/Dropbox/bild_signatures/multi_tcga_expr_pc/Her2_IGF1R")
# 
assign_easy_multi(trainingData = trainhi,test=testhi,trainingLabel1 = trainingLabelhi,g=c(100,15),out_dir_base = "~/Dropbox/bild_signatures/multi_tcga_expr_pc/Her2_IGF1R/")

#4. AKT & BAD
trainab<-cbind(c_gfp,c_akt,c_bad)
testab<-combat_expr1[,36:90]
trainingLabelab<-list(control=list(akt=1:12,bad=1:12),akt=13:18,bad=19:24)
dir.create( "~/Dropbox/bild_signatures/multi_tcga_expr_pc/AKT_BAD")
# 
assign_easy_multi(trainingData = trainab,test=testab,trainingLabel1 = trainingLabelab,g=c(150,150),out_dir_base = "~/Dropbox/bild_signatures/multi_tcga_expr_pc/AKT_BAD/")

#5. AKT & IGF1R
trainai<-cbind(c_gfp,c_akt,c_igf1r)
testai<-combat_expr1[,36:90]
trainingLabelai<-list(control=list(akt=1:12,igf1r=1:12),akt=13:18,igf1r=19:24)
dir.create( "AKT_IGF1R")
# 
assign_easy_multi(trainingData = trainai,test=testai,trainingLabel1 = trainingLabelai,g=c(150,100),out_dir_base = "~/Dropbox/bild_signatures/multi_tcga_expr_pc/AKT_IGF1R")

#6. BAD & IGF1R
trainbi<-cbind(c_gfp,c_bad,c_igf1r)
testbi<-combat_expr1[,36:90]
trainingLabelbi<-list(control=list(bad=1:12,igf1r=1:12),bad=13:18,igf1r=19:24)
dir.create( "~/Desktop/tmp/multi_icbp_expr_pc/BAD_IGF1R")
# 
assign_easy_multi(trainingData = trainbi,test=testbi,trainingLabel1 = trainingLabelbi,g=c(150,100),out_dir_base = "~/Desktop/tmp/multi_icbp_expr_pc/BAD_IGF1R")

#############trying three pathways at a time in multipathway#############
#1. HER2, AKT & BAD
trainhab<-cbind(c_gfp,c_akt,c_bad,c_her2)
testhab<-combat_expr1[,36:90]
trainingLabelhab<-list(control=list(akt=1:12,bad=1:12,her2=1:12),akt=13:18,bad=19:24,her2=25:29)
dir.create( "~/Desktop/tmp/multi_icbp_expr_pc/AKT_BAD_HER2")
# 
assign_easy_multi(trainingData = trainhab,test=testhab,trainingLabel1 = trainingLabelhab,g=c(150,150,15),out_dir_base = "~/Desktop/tmp/multi_icbp_expr_pc/AKT_BAD_HER2")

#2. HER2, BAD & IGF1R
trainhbi<-cbind(c_gfp,c_igf1r,c_bad,c_her2)
testhbi<-combat_expr1[,36:90]
trainingLabelhbi<-list(control=list(igf1r=1:12,bad=1:12,her2=1:12),igf1r=13:18,bad=19:24,her2=25:29)
dir.create( "~/Desktop/tmp/multi_icbp_expr_pc/IGF1R_BAD_HER2")
# 
assign_easy_multi(trainingData = trainhbi,test=testhbi,trainingLabel1 = trainingLabelhbi,g=c(100,150,15),out_dir_base = "~/Desktop/tmp/multi_icbp_expr_pc/IGF1R_BAD_HER2")

#3. AKT, BAD & IGF1R
trainabi<-cbind(c_gfp,c_akt,c_bad,c_igf1r)
testabi<-combat_expr1[,36:90]
trainingLabelabi<-list(control=list(akt=1:12,bad=1:12,igf1r=1:12),akt=13:18,bad=19:24,igf1r=25:30)
dir.create( "~/Desktop/tmp/multi_icbp_expr_pc/AKT_BAD_IGF1R")
# 
assign_easy_multi(trainingData = trainhabi,test=testabi,trainingLabel1 = trainingLabelabi,g=c(150,150,100),out_dir_base = "~/Desktop/tmp/multi_icbp_expr_pc/AKT_BAD_IGF1R")

########################trying all four at once#####################
trainhall<-cbind(c_gfp,c_akt,c_bad,c_her2,c_igf1r)
testall<-combat_expr1[,36:ncol(combat_expr1)]
trainingLabel<-list(control=list(akt=1:12,bad=1:12,her2=1:12,igf1r=1:12),akt=13:18, bad=19:24,her2=25:29,igf1r=30:35)
dir.create( "all_4")
# 
assign_easy_multi(trainingData = trainhall,test=testall,trainingLabel1 = trainingLabel,g=c(150,150,15,100),out_dir_base = "all_4")

```
Checking for correlation..

```{r include=FALSE}
setwd("~/Dropbox/bild_signatures/multi_icbp_expr_pc/")
filenames<-system("ls */*/pathway_activity_testset*", intern=TRUE)
filenames

for(i in 1:length(filenames))
  {
   f<-read.csv(filenames[i], header=1,row.names=1) ###reading in the filess one at a time
  colnames(f)<-paste(filenames[i],colnames(f),sep='/')
  if(i==1){
    data<-f
    }
  else{
    data<-cbind(data,f)
    }
  }
#write.table(data,"~/Desktop/multipathway_preds.txt",sep='\t', col.names = NA,quote=F)
```
