#pancan20_rpkmlog<-read.table("/data/TCGA/PANCAN20/PANCAN20.IlluminaHiSeq_RNASeqV2.tumor_Rsubread_RPKMlog.txt", header=1, row.names=1, check.names = F)
#~/PANCAN20.IlluminaHiSeq_RNASeqV2.tumor_Rsubread_TPM_Transposed.txt
pancan20_tpm<-read.table("~/PANCAN20_TPMlog_all.txt", header=1, row.names=1, check.names =F)
#pancan20_tpm<-pancan20_rpkmlog
nrow(pancan20_tpm)
pancan20_tpm_f <- pancan20_tpm[!apply(pancan20_tpm==0,1,mean)==1,]

sample<-read.table("~/TCGA_PANCAN20_batch_number_8121_samples.txt", header=1, row.names=1, check.names = F)
#pancan20_t_rpkmlog_sample<-merge(pancan20_rpkmlog_t,sample,,by.x=0,by.y='Barcode')
print("after removing all genes containing all zeroes remaining gene number is")
nrow(pancan20_tpm_f)
print("number of genes removed")
nrow(pancan20_tpm)-nrow(pancan20_tpm_f)
pancan20_t_tpm<-t(pancan20_tpm_f)
pancan20_t_tpm_sample<-merge(pancan20_t_tpm,sample,by.x=0,by.y='Barcode')
#rownames(pancan20_t_rpkmlog_sample)<-pancan20_t_rpkmlog_sample$Row.names
#pancan20_t_rpkmlog_BRCA<-subset(pancan20_t_rpkmlog_sample[,2:23369],pancan20_t_rpkmlog_sample$Disease=="BRCA")
#write.table(t(pancan20_t_rpkmlog_BRCA),"~/TCGA_PANCAN20_Rsubread_BRCA_RPKMlog.txt", sep='\t',col.names=NA,quote=F)
rownames(pancan20_t_tpm_sample)<-pancan20_t_tpm_sample$Row.names
pancan20_t_tpm_BRCA<-subset(pancan20_t_tpm_sample[,2:ncol(pancan20_t_tpm_sample)],pancan20_t_tpm_sample$Disease=="BRCA")
head(pancan20_t_tpm_BRCA)
#write.table(t(pancan20_t_tpm_BRCA),"~/TCGA_PANCAN20_Rsubread_BRCA_TPM_10_9_after_overall_filter.txt", sep='\t',col.names=NA,quote=F) 
#pca <- prcomp(pancan20_rpkmlog_t, center=T,scale=F)
pca <- prcomp(pancan20_t_tpm, center=T,scale=F)
rownames(sample)<-sample$Barcode
pca_plot_7056<-merge(pca$x,sample, by=0)
head(pca_plot_7056)
sorted_pca_common<-pca_plot_7056[order(pca_plot_7056$Batch),]
print("prcomp is done!!")
blca<-subset(sorted_pca_common,sorted_pca_common$Disease=='BLCA')
brca<-subset(sorted_pca_common,sorted_pca_common$Disease=='BRCA')
coad<-subset(sorted_pca_common,sorted_pca_common$Disease=='COAD')
gbm<-subset(sorted_pca_common,sorted_pca_common$Disease=='GBM')
hnsc<-subset(sorted_pca_common,sorted_pca_common$Disease=='HNSC')
kich<-subset(sorted_pca_common,sorted_pca_common$Disease=='KICH')
kirc<-subset(sorted_pca_common,sorted_pca_common$Disease=='KIRC')
kirp<-subset(sorted_pca_common,sorted_pca_common$Disease=='KIRP')
laml<-subset(sorted_pca_common,sorted_pca_common$Disease=='LAML')
lihc<-subset(sorted_pca_common,sorted_pca_common$Disease=='LIHC')
lgg<-subset(sorted_pca_common,sorted_pca_common$Disease=='LGG')
luad<-subset(sorted_pca_common,sorted_pca_common$Disease=='LUAD')
lusc<-subset(sorted_pca_common,sorted_pca_common$Disease=='LUSC')
ov<-subset(sorted_pca_common,sorted_pca_common$Disease=='OV')
prad<-subset(sorted_pca_common,sorted_pca_common$Disease=='PRAD')
read<-subset(sorted_pca_common,sorted_pca_common$Disease=='READ')
skcm<-subset(sorted_pca_common,sorted_pca_common$Disease=='SKCM')
stad<-subset(sorted_pca_common,sorted_pca_common$Disease=='STAD')
thca<-subset(sorted_pca_common,sorted_pca_common$Disease=='THCA')
ucec<-subset(sorted_pca_common,sorted_pca_common$Disease=='UCEC')

##PCA plot generation
plot(blca[,2:3],col=as.factor(blca$Batch), main = "Batch effect based on batch number in BLCA")
plot(brca[,2:3],col=as.factor(brca$Batch), main = "Batch effect based on batch number in BRCA")
plot(coad[,2:3],col=as.factor(coad$Batch), main = "Batch effect based on batch number in COAD")
plot(gbm[,2:3],col=as.factor(gbm$Batch), main = "Batch effect based on batch number in GBM")
plot(hnsc[,2:3],col=as.factor(hnsc$Batch), main = "Batch effect based on batch number in HNSC")
plot(kich[,2:3],col=as.factor(kich$Batch), main = "Batch effect based on batch number in KICH")
plot(kirc[,2:3],col=as.factor(kirc$Batch), main = "Batch effect based on batch number in KIRC")
plot(kirp[,2:3],col=as.factor(kirp$Batch), main = "Batch effect based on batch number in KIRP")
plot(laml[,2:3],col=as.factor(laml$Batch), main = "Batch effect based on batch number in LAML")
plot(lgg[,2:3],col=as.factor(lgg$Batch), main = "Batch effect based on batch number in LGG")
plot(lihc[,2:3],col=as.factor(lihc$Batch), main = "Batch effect based on batch number in LIHC")
plot(luad[,2:3],col=as.factor(luad$Batch), main = "Batch effect based on batch number in LUAD")
plot(lusc[,2:3],col=as.factor(lusc$Batch), main = "Batch effect based on batch number in LUSC")
plot(ov[,2:3],col=as.factor(ov$Batch), main = "Batch effect based on batch number in OV")
plot(prad[,2:3],col=as.factor(prad$Batch), main = "Batch effect based on batch number in PRAD")
plot(read[,2:3],col=as.factor(read$Batch), main = "Batch effect based on batch number in READ")
plot(skcm[,2:3],col=as.factor(skcm$Batch), main = "Batch effect based on batch number in SKCM")
plot(stad[,2:3],col=as.factor(stad$Batch), main = "Batch effect based on batch number in STAD")
plot(thca[,2:3],col=as.factor(thca$Batch), main = "Batch effect based on batch number in THCA")
plot(ucec[,2:3],col=as.factor(ucec$Batch), main = "Batch effect based on batch number in UCEC")
dev.off()
#write.table(brca,"~/TCGA_PANCAN20_BRCA_tpm_pca_10_9.txt", sep='\t',col.names=NA,quote=F)
#save(pancan20_tpm_t,pancan20_tpm_t_sample,sorted_pca_common,file='.tpmRdata')
#plot(brca_bat_subtype[,2:3],col=as.factor(brca_bat_subtype$Intrinsic.Cluster), main = "batch effect based on subtype in BRCA for subtype available samples")
